### ISSUE TITLE
FunctionInvokerIntegrationTests tests fail

### ISSUE THREAD

**Issue by aareshchanka** [spring-cloud/spring-cloud-function#1027]
**Describe the bug**
try to build project from **main** with tests and you will get an error:
**Sample**
```
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.933 s - in org.springframework.cloud.function.adapter.gcp.FunctionInvokerHttpTests
[INFO] Running org.springframework.cloud.function.adapter.gcp.integration.FunctionInvokerIntegrationTests
[ERROR] Tests run: 4, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.021 s <<< FAILURE! - in org.springframework.cloud.function.adapter.gcp.integration.FunctionInvokerIntegrationTests
[ERROR] testErrorResponse  Time elapsed: 0.017 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:

Expecting value to be true but was false
        at org.springframework.cloud.function.adapter.gcp.integration.FunctionInvokerIntegrationTests.testErrorResponse(FunctionInvokerIntegrationTests.java:64)

[ERROR] testUppercase  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:

Expecting value to be true but was false
        at org.springframework.cloud.function.adapter.gcp.integration.FunctionInvokerIntegrationTests.testUppercase(FunctionInvokerIntegrationTests.java:52)

[ERROR] testSingular  Time elapsed: 0.001 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:

Expecting value to be true but was false
        at org.springframework.cloud.function.adapter.gcp.integration.FunctionInvokerIntegrationTests.testSingular(FunctionInvokerIntegrationTests.java:47)

[ERROR] testFooBar  Time elapsed: 0.002 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:

Expecting value to be true but was false
        at org.springframework.cloud.function.adapter.gcp.integration.FunctionInvokerIntegrationTests.testFooBar(FunctionInvokerIntegrationTests.java:58)

[INFO] 
[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   FunctionInvokerIntegrationTests.testErrorResponse:64 
Expecting value to be true but was false
[ERROR]   FunctionInvokerIntegrationTests.testFooBar:58 
Expecting value to be true but was false
[ERROR]   FunctionInvokerIntegrationTests.testSingular:47 
Expecting value to be true but was false
[ERROR]   FunctionInvokerIntegrationTests.testUppercase:52 
Expecting value to be true but was false
[INFO]
[ERROR] Tests run: 18, Failures: 4, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Spring Cloud Function Dependencies 4.0.3-SNAPSHOT .. SUCCESS [  0.189 s]
[INFO] Spring Cloud Function Parent 4.0.3-SNAPSHOT ........ SUCCESS [01:37 min]
[INFO] Spring Cloud Function Core 4.0.3-SNAPSHOT .......... SUCCESS [  2.520 s]
[INFO] spring-cloud-function-context 4.0.3-SNAPSHOT ....... SUCCESS [ 37.129 s]
[INFO] Spring Cloud Function Web Support 4.0.3-SNAPSHOT ... SUCCESS [ 39.327 s]
[INFO] spring-cloud-starter-starter-function-web 4.0.3-SNAPSHOT SUCCESS [  0.389 s]
[INFO] spring-cloud-starter-function-webflux 4.0.3-SNAPSHOT SUCCESS [  0.402 s]
[INFO] function-sample 4.0.0.RELEASE ...................... SUCCESS [  6.450 s]
[INFO] function-sample-pof 4.0.0.RELEASE .................. SUCCESS [  0.286 s]
[INFO] function-sample-pojo 4.0.0.RELEASE ................. SUCCESS [  7.334 s]
[INFO] spring-cloud-function-adapter-parent 4.0.3-SNAPSHOT  SUCCESS [  0.378 s]
[INFO] spring-cloud-function-adapter-aws 4.0.3-SNAPSHOT ... SUCCESS [ 18.362 s]
[INFO] function-sample-aws 4.0.0.RELEASE .................. SUCCESS [  4.210 s]
[INFO] function-functional-sample-aws 4.0.0.RELEASE ....... SUCCESS [  3.226 s]
[INFO] function-sample-aws-routing 4.0.0.RELEASE .......... SUCCESS [  3.970 s]
[INFO] function-sample-aws-custom 4.0.0.RELEASE ........... SUCCESS [  8.186 s]
[INFO] AWS Custom Runtime - @Bean sample 4.0.0.RELEASE .... SUCCESS [  1.494 s]
[INFO] function-sample-aws-supplier-exporter 4.0.0.RELEASE  SUCCESS [  1.262 s]
[INFO] function-sample-azure 4.0.0.RELEASE ................ SUCCESS [  8.917 s]
[INFO] function-sample-spring-integration 2.0.0.BUILD-SNAPSHOT SUCCESS [  7.832 s]
[INFO] Spring Cloud Function Adapter GCP 4.0.3-SNAPSHOT ... FAILURE [  4.669 s]

```

**Comment by aareshchanka** [comment]
issue still present in all branches, tested on master, 3.2.x, 3.2.10

**Comment by olegz** [comment]
It's been resolved, the test is passing now
