### ISSUE TITLE
Kotlin classes that implement a suspend functional interface throws ClassCastException

### ISSUE THREAD

**Issue by bohnman** [spring-cloud/spring-cloud-function#1041]
Spring Cloud Function 3.2.10

**Describe the bug**
When a Kotlin classes that implements a suspending function, a  ClassCastException like the following is thrown:

```
java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType (java.lang.Class and java.lang.reflect.ParameterizedType are in module java.base of loader 'bootstrap')
	at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.getFunctionRegistration(KotlinLambdaToFunctionAutoConfiguration.java:160) ~[spring-cloud-function-context-3.2.10.jar:3.2.10]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ HTTP POST "/uppercase1" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.getFunctionRegistration(KotlinLambdaToFunctionAutoConfiguration.java:160) ~[spring-cloud-function-context-3.2.10.jar:3.2.10]
		at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.lookup(BeanFactoryAwareFunctionRegistry.java:170) ~[spring-cloud-function-context-3.2.10.jar:3.2.10]
		at org.springframework.cloud.function.context.FunctionCatalog.lookup(FunctionCatalog.java:87) ~[spring-cloud-function-context-3.2.10.jar:3.2.10]
		at org.springframework.cloud.function.web.util.FunctionWebRequestProcessingHelper.doFindFunction(FunctionWebRequestProcessingHelper.java:180) ~[spring-cloud-function-web-3.2.10.jar:3.2.10]
		at org.springframework.cloud.function.web.util.FunctionWebRequestProcessingHelper.findFunction(FunctionWebRequestProcessingHelper.java:61) ~[spring-cloud-function-web-3.2.10.jar:3.2.10]
		at org.springframework.cloud.function.web.function.FunctionEndpointFactory.extract(FunctionEndpointInitializer.java:232) ~[spring-cloud-function-web-3.2.10.jar:3.2.10]
```

Implementing a non-suspending function or registering a suspending function Bean seems to work fine (see samples).  It appears that the cause of this issue is in `FunctionTypeUtils.discoverFunctionTypeFromClass`.  It doesn't handle the case where the class implements Function2 where the second argument type is a Continuation.		

**Sample**

```kotlin
fun main() {
    runApplication<SampleApp>()
}

@SpringBootApplication
class SampleApp

data class Person(val name: String)

// DOESN'T WORK
@Component("uppercase1")
class Sample1 : suspend (Flow<Person>) -> Flow<Person> {
    override suspend fun invoke(flow: Flow<Person>): Flow<Person> = flow.map { it.copy(name = it.name.uppercase()) }
}

// WORKS
@Component("uppercase2")
class Sample2 : (Person) -> Person {
    override fun invoke(p1: Person): Person = p1.copy(name = p1.name.uppercase())
}

// WORKS
@Configuration
class Sample3 {

    @Bean
    fun uppercase3(): suspend (Flow<Person>) -> Flow<Person> = { flow -> flow.map { it.copy(name = it.name.uppercase()) } }
}
```

```bash
curl -v  -XPOST -H'Content-Type: application/json' -d'{"name": "Joe Smith"}'  http://localhost:8080/uppercase1
curl -v  -XPOST -H'Content-Type: application/json' -d'{"name": "Joe Smith"}'  http://localhost:8080/uppercase2
curl -v  -XPOST -H'Content-Type: application/json' -d'{"name": "Joe Smith"}'  http://localhost:8080/uppercase3
```

**Comment by olegz** [comment]
We actually have test cases for Kotlin suspend function - https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-kotlin/src/test/kotlin/org/springframework/cloud/function/kotlin/web/HeadersToMessageSuspendTests.kt

So please take a look and feel free to reopen it if you still believe there is an issue. Providing a small example in Github that reproduces the issue would also help a lot.
