### ISSUE TITLE
AWS Adapter: CustomRuntimeEventLoop sticks with first function definiton header when invoked 

### ISSUE THREAD

**Issue by ArnauAregall** [spring-cloud/spring-cloud-function#1049]
**Describe the bug**

I have a Spring Cloud Function application deployed as an AWS Lamda on a `provided.al2` Runtime (the application is a GraalVM native executable).

The Spring Boot and Spring Cloud dependencies I am using:

````properties
springBootVersion=3.1.0
springCloudVersion=2022.0.3
````

````kotlin
implementation("org.springframework.boot:spring-boot-starter-webflux")
implementation("org.springframework.cloud:spring-cloud-function-context")
implementation("org.springframework.cloud:spring-cloud-function-web")
implementation("org.springframework.cloud:spring-cloud-function-adapter-aws")
````

The application exposes two different functions as `@Bean`s:

````kotlin
@Bean
fun forecast(weatherService: WeatherService): (Message<GeoLocation>) -> Mono<Forecast> = weatherService::getForecast

@Bean
fun question(questionService: QuestionService): (Message<Question>) -> Mono<Answer> = questionService::answerQuestion
````

After deploying the AWS Lambda, I can correctly invoke the "question" function using HTTP message header `spring.cloud.function.definition: question` with a JSON request body that maps successfully as a `Question` domain object, and the application returns the desired response. Everything OK until here.

But after that, if I want to invoke the just the`forecast` function, now with the HTTP header `spring.cloud.function.definition: forecast` and corresponding request body message that can be mapped to a `GeoLocation` object, the `CustomRuntimeEventLoop` detects the resolved function is still `question`.

Therefore then the message conversion fails as it tries to convert the request body to a `Question` object with a body aimed for a `GeoLocation` object. 

Evidences from CloudWatch logs (removed AWS account sensitive parts):

````text
2023/06/19/[$LATEST]c646dfa4d77c49c3a462b769ebf7ebcf 2023-06-19T08:49:02.108000 2023-06-19T08:49:02.108Z  INFO 9 --- [pool-5-thread-1] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Located function question
2023/06/19/[$LATEST]c646dfa4d77c49c3a462b769ebf7ebcf 2023-06-19T08:49:02.108000 2023-06-19T08:49:02.108Z  INFO 9 --- [pool-5-thread-1] o.s.c.f.adapter.aws.AWSLambdaUtils       : Received: {"version":"1.0","resource":"$default","path":"/","httpMethod":"POST","headers":{"Content-Length":"48","Content-Type":"application/json","Host":"XXXXXXXXXX.amazonaws.com","User-Agent":"Apache-HttpClient/4.5.14 (Java/17.0.6)","X-Amzn-Trace-Id":"Root=1-......","X-Forwarded-For":".......","X-Forwarded-Port":"443","X-Forwarded-Proto":"https","accept":"application/json","accept-encoding":"br,deflate,gzip,x-gzip","spring.cloud.function.definition":"forecast"},"multiValueHeaders":{"Content-Length":["48"],"Content-Type":["application/json"],"Host":["XXXXXXXXXX.amazonaws.com"],"User-Agent":["Apache-HttpClient/4.5.14 (Java/17.0.6)"],"X-Amzn-Trace-Id":["Root=1-6490167e-6b78cfea23bc44e72647d12b"],"X-Forwarded-For":["XXXXXXXXXX"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"accept":["application/json"],"accept-encoding":["br,deflate,gzip,x-gzip"],"spring.cloud.function.definition":["forecast"]} ....}

2023/06/19/[$LATEST]c646dfa4d77c49c3a462b769ebf7ebcf 2023-06-19T08:49:02.109000 java.lang.IllegalStateException: Failed to convert. Possible bug as the conversion probably shouldn't have been attempted here
2023/06/19/[$LATEST]c646dfa4d77c49c3a462b769ebf7ebcf 2023-06-19T08:49:02.109000 at org.springframework.cloud.function.json.JacksonMapper.doFromJson(JacksonMapper.java:65) ~[na:na]
2023/06/19/[$LATEST]c646dfa4d77c49c3a462b769ebf7ebcf 2023-06-19T08:49:02.109000 at org.springframework.cloud.function.json.JsonMapper.fromJson(JsonMapper.java:66) ~[aws-lambda-spring-cloud-function:4.0.3]
2023/06/19/[$LATEST]c646dfa4d77c49c3a462b769ebf7ebcf 2023-06-19T08:49:02.109000 at org.springframework.cloud.function.adapter.aws.AWSTypesMessageConverter.convertFromInternal(AWSTypesMessageConverter.java:90)
...
````

Note: after waiting the lambda cooldown period, invoking again just the question function, it works correctly.

I am not sure if it could be somehow related to the heads up of the reference documentation, as I am using `Mono<?>` return types.

https://cloud.spring.io/spring-cloud-function/reference/html/spring-cloud-function.html#_function_routing 

<img width="1006" alt="image" src="https://github.com/spring-cloud/spring-cloud-function/assets/2873901/f9e9d2c7-9673-4c74-acb3-b9e1dcaefee9">

Disclaimer: did not try with a `java17` runtime though.

**Comment by olegz** [comment]
Actually yes, if your function is reactive you can NOT use routing based on headers. The RoutingFunction won't allow that primarily due to the streaming issues where in streaming environments a reactive function is only invoked once.
However, i'll give it another look in the context of AWS.

Also, not a fan of using reactive with AWS since aside from API you are not benefitting from core features of the reactive especially with API gateway or custom runtime where the source request is actually blocking.

**Comment by ArnauAregall** [comment]
Thanks for the advice, now that I have understood a bit better how AWS adapter and custom runtime work I can understand your reasoning here.

**Comment by olegz** [comment]
I just changed to 
```
 @Bean
 public Function<Flux<String>, Flux<String>> echo() {
        return x -> x;
 }
```
will let you know in a few

**Comment by olegz** [comment]
So all works fine with these two requests
```
curl -X POST -H "Content-Type: application/json" -H "spring.cloud.function.definition: echo" -d '"blah"' https://emcdxu5ijj.execute-api.us-east-2.amazonaws.com/question
```
and
```
curl -X POST -H "Content-Type: application/json" -H "spring.cloud.function.definition: forecast" -d '[{"latitude": 41.34, "longitude": 2.78}]' https://emcdxu5ijj.execute-api.us-east-2.amazonaws.com/question

```

**Comment by ArnauAregall** [comment]
Thanks for checking @olegz 

[I added two extra functions](https://github.com/ArnauAregall/aws-lambda-spring-cloud-function-reactive-java/commit/a51a504ed1ef3a74d0f631868f537778f3582ffa) to the sample app to double check it, and I am also not not able to reproduce it again on AWS with that Java sample.

However, the original issue was opened when I managed to reproduce it in another sample project that has roughly the same implementation **but using Kotlin**, and I can still reproduce the issue on AWS with that Kotlin SCF application.

The Kotlin sample app is the following:  https://github.com/ArnauAregall/aws-lambda-spring-cloud-function

_Build instructions are also provided, except `OPENAI_API_KEY` env var can be defined as `foo`, not needed to reproduce the issue._

Once deployed, invoke the function with the following requests:

1. Invoke `forecast` function

````bash
curl -X POST --location "https://xxxxxxxxxx.execute-api.yyyyyyyy.amazonaws.com" \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "spring.cloud.function.definition: forecast" \
    -d "{
          \"latitude\": 41.3874,
          \"longitude\": 2.1686
        }"
````

Response should be the already known Forecast.

2. Invoke a function compositon: `forecast,forecastToQuestion` 

````bash
curl -X POST --location "https://xxxxxxxxxx.execute-api.yyyyyyyy.amazonaws.com" \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "spring.cloud.function.definition: forecast,forecastToQuestion" \
    -d "{
          \"latitude\": 41.3874,
          \"longitude\": 2.1686
        }"
````

The response is still the result of `forecast` only.

The CloudWatch logs 

````
2023-07-14T06:09:51.497Z DEBUG 9 --- [pool-5-thread-1] o.s.c.f.a.aws.CustomRuntimeEventLoop     : New Event received: <200 OK OK,{"version":"1.0","resource":"$default","path":"/","httpMethod":"POST","headers":{"Content-Length":"48","Content-Type":"application/json","Host":"xxxxxxxxxx.execute-api.yyyyyyyy.amazonaws.com","User-Agent":"Apache-HttpClient/4.5.14 (Java/17.0.7)","X-Amzn-Trace-Id":"Root=1-64b0e6af-49bcf7120f153aa960c18ca3","X-Forwarded-For":"90.68.82.53","X-Forwarded-Port":"443","X-Forwarded-Proto":"https","accept":"application/json","accept-encoding":"br,deflate,gzip,x-gzip","spring.cloud.function.definition":"forecast,forecastToQuestion"},"multiValueHeaders":{"Content-Length":["48"],"Content-Type":["application/json"],"Host":["xxxxxxxxxx.execute-api.yyyyyyyy.amazonaws.com"],"User-Agent":["Apache-HttpClient/4.5.14 (Java/17.0.7)"],"X-Amzn-Trace-Id":["Root=1-64b0e6af-49bcf7120f153aa960c18ca3"],"X-Forwarded-For":["90.68.82.53"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"accept":["application/json"],"accept-encoding":["br,deflate,gzip,x-gzip"],"spring.cloud.function.definition":["forecast,forecastToQuestion"]},"queryStringParameters":null,"multiValueQueryStringParameters":null,"requestContext":{"accountId":"741919747208","apiId":"fdwvp3wqoh","domainName":"xxxxxxxxxx.execute-api.yyyyyyyy.amazonaws.com","domainPrefix":"fdwvp3wqoh","extendedRequestId":"ICj7dgoQFiAEJbA=","httpMethod":"POST","identity":{"accessKey":null,"accountId":null,"caller":null,"cognitoAmr":null,"cognitoAuthenticationProvider":null,"cognitoAuthenticationType":null,"cognitoIdentityId":null,"cognitoIdentityPoolId":null,"principalOrgId":null,"sourceIp":"XXXXXXXXXX","user":null,"userAgent":"Apache-HttpClient/4.5.14 (Java/17.0.7)","userArn":null},"path":"/","protocol":"HTTP/1.1","requestId":"ICj7dgoQFiAEJbA=","requestTime":"14/Jul/2023:06:09:51 +0000","requestTimeEpoch":1689314991468,"resourceId":"$default","resourcePath":"$default","stage":"$default"},"pathParameters":null,"stageVariables":null,"body":"{\n  \"latitude\": 41.3874,\n  \"longitude\": 2.1686\n}","isBase64Encoded":false},[Content-Type:"application/json", Lambda-Runtime-Aws-Request-Id:"79b50de9-2708-4c1d-9f02-b869b07f61ed", Lambda-Runtime-Deadline-Ms:"1689315011496", Lambda-Runtime-Invoked-Function-Arn:"XXXXXXXX", Lambda-Runtime-Trace-Id:"Root=1-64b0e6af-2f15c7d95e699a0470759efd;Parent=b160849799657d27;Sampled=1;Lineage=8643e627:0", Date:"Fri, 14 Jul 2023 06:09:51 GMT", Content-Length:"1987"]>
2023-07-14T06:09:51.497Z DEBUG 9 --- [pool-5-thread-1] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Value of DEFAULT_HANDLER env: null
2023-07-14T06:09:51.497Z  INFO 9 --- [pool-5-thread-1] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Located function forecast
````

As you can see the header is received as expected but `"spring.cloud.function.definition":["forecast,forecastToQuestion"]}` but the runtime event loop states `Located function forecast`.

Would be great if you could check, in the meantime I will prepare a simpler Kotlin sample app and try to reproduce it with that one.

**Comment by ArnauAregall** [comment]
I managed to reproduce it it in an isolated sample Kotlin application 😅:

https://github.com/ArnauAregall/aws-spring-cloud-function-kotlin-reactive-sample

````kotlin
import org.springframework.aot.hint.annotation.RegisterReflectionForBinding
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import reactor.core.publisher.Flux

data class Foo(val fooText: String, val fooNumber: Number, val fooBoolean: Boolean)
data class Bar(val barText: String, val barNumber: Number, val barBoolean: Boolean)
data class Baz(val bazText: String, val bazNumber: Number, val bazBoolean: Boolean)

@Configuration
@RegisterReflectionForBinding(classes = [Foo::class, Bar::class, Baz::class])
class Functions {

	@Bean
	fun fooToBar(): (Flux<Foo>) -> Flux<Bar> = {
		it.map { foo -> Bar(foo.fooText, foo.fooNumber, foo.fooBoolean) }
	}

	@Bean
	fun barToBaz(): (Flux<Bar>) -> Flux<Baz> = {
		it.map { bar -> Baz(bar.barText, bar.barNumber, bar.barBoolean) }
	}

}

@SpringBootApplication
class App

fun main(args: Array<String>) {
	runApplication<App>(*args)
}
````

First I invoke "fooToBar" using header definition:

````bash
curl -X POST --location "https://xxxxxxxxxx.execute-api.yyyyyyyy.amazonaws.com" \
    -H "Content-Type: application/json" \
    -H "spring.cloud.function.definition: fooToBar" \
    -d "{
          \"fooText\": \"Hello\", \"fooNumber\": 123, \"fooBoolean\": false
        }"
````

````http
HTTP/1.1 200 OK
Date: Fri, 14 Jul 2023 14:41:49 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 54
Connection: keep-alive
Id: 3deef326-ca5a-5345-3208-9fb66c3617bf
Contenttype: application/json
Timestamp: 1689345708994
Apigw-Requestid: IDu7EiH_liAEMVg=

{"barText":"Hello","barNumber":123,"barBoolean":false}

````

Then I invoke "fooToBar,barToBaz": 

````bash
curl -X POST --location "https://xxxxxxxxxx.execute-api.yyyyyyyy.amazonaws.com" \
    -H "Content-Type: application/json" \
    -H "spring.cloud.function.definition: fooToBar,barToBaz" \
    -d "{
          \"fooText\": \"Hello\", \"fooNumber\": 123, \"fooBoolean\": false
        }"
````

And the response is still the output from "fooToBar"

````http
HTTP/1.1 200 OK
Date: Fri, 14 Jul 2023 14:44:14 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 54
Connection: keep-alive
Id: 9793ef25-32d1-b6e7-ad33-33cba1a01647
Contenttype: application/json
Timestamp: 1689345853997
Apigw-Requestid: IDvRujo1FiAEPqA=

{"barText":"Hello","barNumber":123,"barBoolean":false}
````

So "barToBaz" is not invoked at all.

The logs:

````
2023/07/14/[$LATEST]c58c528f74104e6892d7d3b8bfa753b5 2023-07-14T14:44:13.996000 2023-07-14T14:44:13.996Z DEBUG 9 --- [pool-5-thread-1] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Event message: GenericMessage [payload=byte[1927], headers={User-Agent=Apache-HttpClient/4.5.14 (Java/17.0.7), X-Forwarded-Proto=https, Host=XXXXXX.amazonaws.com, X-Forwarded-Port=443, X-Amzn-Trace-Id=Root=1-64b15f3d-5e0d06555df6d78c15fe1360, X-Forwarded-For=XXXXXX, aws-api-gateway=true, id=4aef7dd3-a9d6-d685-0429-c8df97f2d01c, Content-Length=63, spring.cloud.function.definition=fooToBar,barToBaz, accept-encoding=br,deflate,gzip,x-gzip, Content-Type=application/json, timestamp=1689345853996}]
2023/07/14/[$LATEST]c58c528f74104e6892d7d3b8bfa753b5 2023-07-14T14:44:13.996000 2023-07-14T14:44:13.996Z DEBUG 9 --- [pool-5-thread-1] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Lambda-Runtime-Trace-Id: Root=1-64b15f3d-0b01a9d51aae4fa61a11805f;Parent=8cde833af1d4650d;Sampled=1;Lineage=ed52617d:0
2023/07/14/[$LATEST]c58c528f74104e6892d7d3b8bfa753b5 2023-07-14T14:44:13.996000 2023-07-14T14:44:13.996Z DEBUG 9 --- [pool-5-thread-1] c.f.c.c.BeanFactoryAwareFunctionRegistry : Invoking function fooToBar<reactor.core.publisher.Flux<tech.aaregall.lab.function.Foo>, reactor.core.publisher.Flux<tech.aaregall.lab.function.Bar>>
````

Notice that if the first request is with function `fooToBar,barToBaz`, then it works properly.

**Comment by olegz** [comment]
I was able to track it down. Kotlin type system kind of got in the way, but also helped to discover a small optimisation that actually addresses your issue as a nice side-effect. Will push shortly

**Comment by ArnauAregall** [comment]
Hello @olegz! Thanks a lot for this, I just tested successfully the fix on the sample app deployed to AWS with the nightly build of `4.0.5-SNAPSHOT`.

Keep up the good work! 

Cheers 💪
