### ISSUE TITLE
ClassCastException in AWS Lambda Function Post Upgrade to spring-cloud-function-3.2.11

### ISSUE THREAD

**Issue by randyhbh** [spring-cloud/spring-cloud-function#1057]
**Describe the bug**
Upon upgrading from spring-cloud-function-3.2.8 to spring-cloud-function-3.2.11, our AWS Lambda function, which consumes a stream from DynamoDB, began experiencing failures. The function signature is as follows: 

```kotlin
fun handleDynamoDbEvent(): (Message<DynamodbEvent>) -> Unit = {...}
```

The error message received is a ClassCastException:
```
class [B cannot be cast to class com.amazonaws.services.lambda.runtime.events.DynamodbEvent ([B is in module java.base of loader 'bootstrap'; com.amazonaws.services.lambda.runtime.events.DynamodbEvent is in unnamed module of loader com.amazonaws.services.lambda.runtime.api.client.CustomerClassLoader @2e817b38): java.lang.ClassCastException
```

**Additional Debug Information**
Upon enabling debug logs on AWS, I discovered more information about the issue. The logs indicate a `java.lang.IllegalStateException` with the message "Failed to convert. Possible bug as the conversion probably shouldn't have been attempted here". The error seems to be related to a failure in converting a JSON message, specifically a `java.util.Date` from a floating-point value.

Complete stacktrace
```
java.lang.IllegalStateException: Failed to convert. Possible bug as the conversion probably shouldn't have been attampted here
--
    at org.springframework.cloud.function.json.JacksonMapper.doFromJson(JacksonMapper.java:70) ~[task/:na]
    at org.springframework.cloud.function.json.JsonMapper.fromJson(JsonMapper.java:94) ~[task/:na]
    at org.springframework.cloud.function.context.config.JsonMessageConverter.convertFromInternal(JsonMessageConverter.java:91) ~[task/:na]
    at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:185) ~[task/:na]
    at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:176) ~[task/:na]
    at org.springframework.cloud.function.context.config.SmartCompositeMessageConverter.fromMessage(SmartCompositeMessageConverter.java:63) ~[task/:na]
    at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertInputMessageIfNecessary(SimpleFunctionRegistry.java:1339) ~[task/:na]
    at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertInputIfNecessary(SimpleFunctionRegistry.java:1098) ~[task/:na]
    at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:735) ~[task/:na]
    at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:590) ~[task/:na]
    at org.springframework.cloud.function.adapter.aws.FunctionInvoker.handleRequest(FunctionInvoker.java:85) ~[task/:na]
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
    at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
    at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:379) ~[aws-lambda-java-runtime-interface-client-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
    at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$2.call(EventHandlerLoader.java:903) ~[aws-lambda-java-runtime-interface-client-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
    at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:238) ~[aws-lambda-java-runtime-interface-client-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
    at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:190) ~[aws-lambda-java-runtime-interface-client-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
    at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:185) ~[aws-lambda-java-runtime-interface-client-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.Date` from Floating-point value (token `JsonToken.VALUE_NUMBER_FLOAT`)
    at [Source: (byte[])"{
                            "Records": [
                            {
                            "eventID": "dc1e145db718184b1c809f989335b168",
                            "eventName": "INSERT",
                            "eventVersion": "1.1",
                            "eventSource": "aws:dynamodb",
                            "awsRegion": "eu-central-1",
                            "dynamodb": {
                            "ApproximateCreationDateTime": 1.689335433E9,
                            "Keys": {
                            "version": {
                            "N": "1"
                            },
                            "urlPath": {
                            "S": "image/6037/2023/07/14/1d058d91-c9db-4c6a-aadf-4ab749de95d1.jpg"
                        }
"[truncated 8983 bytes]; line: 10, column: 40] (through reference chain: com.amazonaws.services.lambda.runtime.events.DynamodbEvent["Records"]->java.util.ArrayList[0]->com.amazonaws.services.lambda.runtime.events.DynamodbEvent$DynamodbStreamRecord["dynamodb"]->com.amazonaws.services.lambda.runtime.events.models.dynamodb.StreamRecord["ApproximateCreationDateTime"])
    at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[task/:na]
    at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741) ~[task/:na]
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515) ~[task/:na]
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1420) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseDate(StdDeserializer.java:1247) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateBasedDeserializer._parseDate(DateDeserializers.java:201) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:303) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:281) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[task/:na]
    at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[task/:na]
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[task/:na]
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3723) ~[task/:na]
    at org.springframework.cloud.function.json.JacksonMapper.doFromJson(JacksonMapper.java:60) ~[task/:na]
    ... 19 common frames omitted
2023-07-16 13:41:32.410 DEBUG 16 --- [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : Input type conversion of payload [B@15723761 resulted in 'null'. Will use the original message as input.
2023-07-16 13:41:32.411 DEBUG 16 --- [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : Converted Message: GenericMessage [payload=byte[9483], headers={aws-context=com.amazonaws.services.lambda.runtime.api.client.api.LambdaContext@312afbc7, id=7801f864-037e-88f4-3dc9-ebec42103d3f, timestamp=1689514892305}] to: GenericMessage [payload=byte[9483], headers={aws-context=com.amazonaws.services.lambda.runtime.api.client.api.LambdaContext@312afbc7, id=7801f864-037e-88f4-3dc9-ebec42103d3f, timestamp=1689514892305}]
class [B cannot be cast to class com.amazonaws.services.lambda.runtime.events.DynamodbEvent ([B is in module java.base of loader 'bootstrap'; com.amazonaws.services.lambda.runtime.events.DynamodbEvent is in unnamed module of loader com.amazonaws.services.lambda.runtime.api.client.CustomerClassLoader @2e817b38): java.lang.ClassCastException java.lang.ClassCastException: class [B cannot be cast to class com.amazonaws.services.lambda.runtime.events.DynamodbEvent ([B is in module java.base of loader 'bootstrap'; com.amazonaws.services.lambda.runtime.events.DynamodbEvent is in unnamed module of loader com.amazonaws.services.lambda.runtime.api.client.CustomerClassLoader @2e817b38) 	at com.xxx.xxxxxxx.aws.lambda.ExampleHandler$handleDynamoDbEvent$1.invoke(ExampleHandler.kt:60) 	at com.xxx.xxxxxxx.aws.lambda.ExampleHandler$handleDynamoDbEvent$1.invoke(ExampleHandler.kt:59) 	at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.invoke(KotlinLambdaToFunctionAutoConfiguration.java:124) 	at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.apply(KotlinLambdaToFunctionAutoConfiguration.java:99) 	at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.accept(KotlinLambdaToFunctionAutoConfiguration.java:146) 	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeConsumer(SimpleFunctionRegistry.java:1017) 	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:744) 	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:590) 	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.handleRequest(FunctionInvoker.java:85) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

The Spring Boot and Spring Cloud dependencies I am using:
- spring boot 2.7.13
- spring cloud 2021.0.8
- java 17
- kotlin 1.8.22

AWS dependencies I am using:
```
    implementation("com.amazonaws:aws-lambda-java-core:1.2.2")
    implementation("com.amazonaws:aws-lambda-java-events-sdk-transformer:3.1.0")
    implementation("com.amazonaws:aws-lambda-java-events:3.11.2")
    implementation("software.amazon.awssdk:dynamodb")
    implementation("software.amazon.awssdk:dynamodb-enhanced")
```

**Sample**
The error can be reproduced using the following DynamoDB event. However, it's important to note that the error only manifests when the function is running on AWS:

```
{
  "Records": [
    {
      "eventID": "dc1e145db718184b1c809f989335b168",
      "eventName": "INSERT",
      "eventVersion": "1.1",
      "eventSource": "aws:dynamodb",
      "awsRegion": "eu-central-1",
      "dynamodb": {
        "ApproximateCreationDateTime": 1.689335433E9,
        "Keys": {
          "version": {
            "N": "1"
          },
          "urlPath": {
            "S": "image/6037/2023/07/14/1d058d91-c9db-4c6a-aadf-4ab749de95d1.jpg"
          }
        },
        "NewImage": {
          "createdAt": {
            "N": "1689335427"
          },
          "provider": {
            "S": "XXXXXX"
          },
          "urlPath": {
            "S": "image/6037/2023/07/14/1d058d91-c9db-4c6a-aadf-4ab749de95d1.jpg"
          },
          "version": {
            "N": "1"
          },
          "status": {
            "S": "SUCCESS"
          }
        },
        "SequenceNumber": "1049234200000000032682603273",
        "SizeBytes": 7869,
        "StreamViewType": "NEW_IMAGE"
      },
      "eventSourceARN": "arn:aws:dynamodb:eu-central-1:xxxxxxx:table/example-results/stream/2022-12-06T16:23:45.860"
    }
  ]
}
```

**Comment by olegz** [comment]
That is actually strange as we are testing for that - https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/test/java/org/springframework/cloud/function/adapter/aws/FunctionInvokerTests.java#L79 but i will try reproduce

**Comment by olegz** [comment]
Closing it due to inactivity from the original user

**Comment by randyhbh** [comment]
@olegz sorry for not responding sooner, for some reason I missed your previous messages. I will take a look at what you shared and answer back ASAP
