### ISSUE TITLE
Issue with SNSEvent message conversion

### ISSUE THREAD

**Issue by beccagaspard** [spring-cloud/spring-cloud-function#1067]
**Describe the bug**

Message conversion does not seem to be working correctly for functions that accept an `SNSMessage` when running and testing locally as a spring app.  Fallback json conversion doesn't work either due to property case mismatch.

Versions:
Spring Boot = 3.1.2
Spring Cloud = 2022.0.4
Java 17

**Sample**

Application:
``` java
@SpringBootApplication
public class SpringCloudFunctionTestApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringCloudFunctionTestApplication.class, args);
    }

    @Bean
    public Function<SNSEvent, String> test() {
        return value -> value.getRecords().get(0).getSNS().toString();
    }

}
```
build.gradle:
```groovy
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.cloud:spring-cloud-function-context'
    implementation 'org.springframework.cloud:spring-cloud-starter-function-web'
    implementation 'org.springframework.cloud:spring-cloud-function-adapter-aws'
    implementation 'com.amazonaws:aws-lambda-java-events:3.9.0'
    implementation 'com.amazonaws:aws-lambda-java-serialization:1.0.0'
}
```

http request:
```
POST http://localhost:8080/test
Content-Type: application/json

{
  "Records": [
    {
      "EventVersion": "1.0",
      "EventSubscriptionArn": "arn:aws:sns:EXAMPLE",
      "EventSource": "aws:sns",
      "Sns": {
        "Signature": "EXAMPLE",
        "MessageId": "95df01b4-ee98-5cb9-9903-4c221d41eb5e",
        "Type": "Notification",
        "TopicArn": "arn:aws:sns:EXAMPLE",
        "MessageAttributes": {
          "Test": {
            "Type": "String",
            "Value": "TestString"
          },
          "TestBinary": {
            "Type": "Binary",
            "Value": "TestBinary"
          }
        },
        "SignatureVersion": "1",
        "Timestamp": "2015-06-03T17:43:27.123Z",
        "SigningCertUrl": "EXAMPLE",
        "Message": "Hello from SNS!",
        "UnsubscribeUrl": "EXAMPLE",
        "Subject": "TestInvoke"
      }
    }
  ]
}
```

stacktrace:
```
2023-08-23T21:19:24.017-04:00  WARN 70525 --- [nio-8080-exec-1] s.c.f.c.c.SmartCompositeMessageConverter : Failure during type conversion by org.springframework.cloud.function.adapter.aws.AWSTypesMessageConverter@71b6c7e8. Will try the next converter.

java.lang.ClassCastException: class java.lang.String cannot be cast to class [B (java.lang.String and [B are in module java.base of loader 'bootstrap')
	at org.springframework.cloud.function.adapter.aws.AWSTypesMessageConverter.convertFromInternal(AWSTypesMessageConverter.java:80) ~[spring-cloud-function-adapter-aws-4.0.5.jar:4.0.5]
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:185) ~[spring-messaging-6.0.11.jar:6.0.11]
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:176) ~[spring-messaging-6.0.11.jar:6.0.11]
	at org.springframework.cloud.function.context.config.SmartCompositeMessageConverter.fromMessage(SmartCompositeMessageConverter.java:63) ~[spring-cloud-function-context-4.0.5.jar:4.0.5]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertInputMessageIfNecessary(SimpleFunctionRegistry.java:1358) ~[spring-cloud-function-context-4.0.5.jar:4.0.5]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertInputIfNecessary(SimpleFunctionRegistry.java:1111) ~[spring-cloud-function-context-4.0.5.jar:4.0.5]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:722) ~[spring-cloud-function-context-4.0.5.jar:4.0.5]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:577) ~[spring-cloud-function-context-4.0.5.jar:4.0.5]
	at org.springframework.cloud.function.web.util.FunctionWebRequestProcessingHelper.processRequest(FunctionWebRequestProcessingHelper.java:132) ~[spring-cloud-function-web-4.0.5.jar:4.0.5]
	at org.springframework.cloud.function.web.mvc.FunctionController.post(FunctionController.java:139) ~[spring-cloud-function-web-4.0.5.jar:4.0.5]
```

Let me know if you need any more info - thanks!

**Comment by msailes** [comment]
Hi @beccagaspard,

I think two concepts are being confused here. You have created a function that takes a SNSEvent.

```
@SpringBootApplication
public class SpringCloudFunctionTestApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringCloudFunctionTestApplication.class, args);
    }

    @Bean
    public Function<SNSEvent, String> test() {
        return value -> value.getRecords().get(0).getSNS().toString();
    }
}
```

If you deploy this to AWS and trigger it with a SNS message, or use the console test functionality )with the request you specified), I would expect it to work.

If you wanted to respond to a HTTP request then your function would use an Object which represents a HTTP request.

[APIGatewayV2HTTPEvent.java](https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java) or [APIGatewayProxyRequestEvent.java](https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyRequestEvent.java)

**Comment by soterocra** [comment]
Hi @beccagaspard ,

Maybe you want to simulate real AWS events in your local environment, right?

The type conversion performed in the `AWSTypesMessageConverter.convertFromInternal` class will not allow you to do it the way you are trying, because the way the conversion of bytes is done does not work for String, which is how the message arrives when we have the HTTP requests locally.

For this, the best workaround for local testing is a Custom Converter.

See how I did mine, I'm dealing with Gateway events (APIGatewayProxyRequestEvent), but just replace the class with the SNS class.

```java
package br.com.project.config;

import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.serialization.PojoSerializer;
import com.amazonaws.services.lambda.runtime.serialization.events.LambdaEventSerializers;
import org.springframework.messaging.Message;
import org.springframework.messaging.converter.AbstractMessageConverter;
import org.springframework.stereotype.Component;
import org.springframework.util.MimeType;

@Component
public class LocalWebConverter extends AbstractMessageConverter {

    public LocalWebConverter() {
        super(new MimeType("application", "json-test"));
        this.setStrictContentTypeMatch(true);
    }

    @Override
    protected boolean supports(Class<?> clazz) {
        return (APIGatewayProxyRequestEvent.class.equals(clazz));
    }

    @Override
    protected Object convertFromInternal(Message<?> message, Class<?> targetClass, Object conversionHint) {
        Object payload = message.getPayload();
        PojoSerializer<?> serializer = LambdaEventSerializers.serializerFor(targetClass, Thread.currentThread().getContextClassLoader());
        Object event = serializer.fromJson(payload.toString());
        return (payload instanceof APIGatewayProxyRequestEvent ? payload : event);
    }
    
}

```
See a small detail in the constructor. This converter will only be invoked effectively if the Content-Type of our request is equal to `application/json-test`.

Then in your request add the Header:

`Content-Type: application/json-test`

If you have doubts about my dependencies and want to check if everything is ok in your project, here is what I use in my project, just an example:

```
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.cloud:spring-cloud-function-context'
	implementation 'org.springframework.cloud:spring-cloud-function-adapter-aws'
	implementation 'org.springframework.cloud:spring-cloud-starter-function-web'
	implementation platform ('software.amazon.awssdk:bom:2.20.56')
	implementation 'com.amazonaws:aws-lambda-java-core:1.2.2'
	implementation 'com.amazonaws:aws-lambda-java-serialization:1.1.2'
	implementation 'com.amazonaws:aws-lambda-java-events:3.11.1'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

Hope this helps you.

If someone else has a better suggestion, I'm open to new ideas.

**Comment by msailes** [comment]
@olegz can this be added to the docs?

**Comment by olegz** [comment]
We do have documentation for custom converters, which is at the core of @soterocra explanation.
For local testing @beccagaspard please look at [FunctionInvokerTests](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/test/java/org/springframework/cloud/function/adapter/aws/FunctionInvokerTests.java#L887) where we are doing exactly that. There are 4 tests for SNS event with one of them being almost identical to what @beccagaspard is trying to do.

Passing SNSEvent over HTTP is not a realistic scenario (unless it is @msailes ??) and while you can handle it with custom converter, that is why we have then in the first place as an extension point to the framework.

In any event, it appears there is nothing to do here, so i'll resolve it, but feel free to re-open it if you believe there is stil an issue.

**Comment by sryze** [comment]
I ran into the same problem with `APIGatewayV2HTTPEvent`. It seems that `LambdaEventSerializers` does not support this type?
