### ISSUE TITLE
spring.cloud.function.definition property does not recognize multiple function with the semicolon 

### ISSUE THREAD

**Issue by anthonyvc1** [spring-cloud/spring-cloud-function#1087]
**Describe the bug**
When I specify a single function or add the property as a header it works but in the documentation it says that spring.cloud.function.definition=foo;bar should work
[Documentation](https://docs.spring.io/spring-cloud-function/docs/4.0.5-SNAPSHOT/reference/html/spring-cloud-function.html#_function_filtering_rules) 

```
Failed to lookup function to route based on the value of 'spring.cloud.function.definition' property 'health;testFunction': java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: Failed to lookup function to route based on the value of 'spring.cloud.function.definition' property 'health;testFunction'
        at org.springframework.util.Assert.notNull(Assert.java:204)
        at org.springframework.cloud.function.context.config.RoutingFunction.functionFromDefinition(RoutingFunction.java:207)
        at org.springframework.cloud.function.context.config.RoutingFunction.route(RoutingFunction.java:152)
        at org.springframework.cloud.function.context.config.RoutingFunction.apply(RoutingFunction.java:107)
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:725)
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:577)
        at org.springframework.cloud.function.adapter.aws.FunctionInvoker.handleRequest(FunctionInvoker.java:91)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

**Sample**
I am using 
```
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.1.4</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```

and 

```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2022.0.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

It is a very simple test app that works just fine with the headers

```
import com.capitalone.oao.core.ol.models.TestRequest;
import com.capitalone.oao.core.ol.models.TestResponse;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.messaging.Message;

import java.util.function.Function;
import java.util.function.Supplier;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public Supplier<String> health() {
        return ()-> "ok";
    }

    @Bean
    public Function<Message<TestRequest>, TestResponse> testFunction() {
        return (message) -> {
            System.out.println("headers: " + message.getHeaders());
            return new TestResponse(
                    "Hello, " + message.getPayload().getRequestString(),
                    message.getPayload().getRequestInt() + 1
            );
        };
    }
}
```

**Comment by anthonyvc1** [comment]
On further inspection this works fine when I run the jar and do the curls locally but when I run in aws sam cli I am getting this error

**Comment by anthonyvc1** [comment]
I am seeing this specifically when triggered by an ALB event
