### ISSUE TITLE
spring-cloud-function-adapter-azure-web sample question

### ISSUE THREAD

**Issue by eric950907** [spring-cloud/spring-cloud-function#1103]
I started the project with the README.adoc file of spring-cloud-function-adapter-azure-web, but I had a problem executing the curl -X GET http://localhost:7072/api/AzureWebAdapter/ command。I didn't change any code for the project, I started the project after downloading it, and this problem occurred

[2024-01-17T06:11:07.082Z] Executed 'Functions.AzureWebAdapter' (Failed, Id=b02447f7-bbf4-4768-ba7d-ed2fea4e24ca, Duration=1396ms)
[2024-01-17T06:11:07.082Z] System.Private.CoreLib: Exception while executing function: Functions.AzureWebAdapter. System.Private.CoreLib: Result: Failure
[2024-01-17T06:11:07.082Z] Exception: NullPointerException: Cannot invoke "org.springframework.cloud.function.serverless.web.ProxyMvc.service(jakarta.servlet.http.HttpServletRequest, jakarta.servlet.http.HttpServletResponse)" because "this.mvc" is null
[2024-01-17T06:11:07.082Z] Stack: java.lang.reflect.InvocationTargetException
[2024-01-17T06:11:07.083Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-17T06:11:07.083Z]      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-01-17T06:11:07.083Z]      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-17T06:11:07.083Z]      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2024-01-17T06:11:07.083Z]      at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2024-01-17T06:11:07.084Z]      at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
[2024-01-17T06:11:07.084Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:61)
[2024-01-17T06:11:07.084Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[2024-01-17T06:11:07.084Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2024-01-17T06:11:07.086Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[2024-01-17T06:11:07.086Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[2024-01-17T06:11:07.086Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-01-17T06:11:07.086Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-01-17T06:11:07.087Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-01-17T06:11:07.087Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-01-17T06:11:07.087Z]      at java.base/java.lang.Thread.run(Thread.java:840)
[2024-01-17T06:11:07.088Z] Caused by: java.lang.IllegalStateException: java.lang.NullPointerException: Cannot invoke "org.springframework.cloud.function.serverless.web.ProxyMvc.service(jakarta.servlet.http.HttpServletRequest, jakarta.servlet.http.HttpServletResponse)" because "this.mvc" is null
[2024-01-17T06:11:07.088Z]      at org.springframework.cloud.function.adapter.azure.web.AzureWebProxyInvoker.execute(AzureWebProxyInvoker.java:146)
[2024-01-17T06:11:07.088Z]      ... 16 more
[2024-01-17T06:11:07.088Z] Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.cloud.function.serverless.web.ProxyMvc.service(jakarta.servlet.http.HttpServletRequest, jakarta.servlet.http.HttpServletResponse)" because "this.mvc" is null
[2024-01-17T06:11:07.091Z]      at org.springframework.cloud.function.adapter.azure.web.AzureWebProxyInvoker.execute(AzureWebProxyInvoker.java:127)
[2024-01-17T06:11:07.092Z]      ... 16 more
[2024-01-17T06:11:07.092Z] .

**Comment by BernhardPosselt** [comment]
Has anyone managed to solve this? Still encountering this in 4.3.0
