### ISSUE TITLE
Adding DeserializationFeature.FAIL_ON_TRAILING_TOKENS in ContextFunctionCatalogAutoConfiguration breaks WebTestClient with HypermediaWebTestClientConfigurer

### ISSUE THREAD

**Issue by guerricmerleHUG** [spring-cloud/spring-cloud-function#1148]
**Describe the bug**
We start by migrating our applications to Spring Boot 3.2.6, Spring Cloud 2023.0.2, these applications have these dependencies: spring-boot-starter-hateoas, spring-boot-starter-webflux and 
spring-cloud-stream-test-binder / spring-cloud-starter-bus-amqp / ... any dependency that uses "spring-cloud-function-context", this last dependency breaks all tests because of adding "mapper .configure(DeserializationFeature.FAIL_ON_TRAILING_TOKENS, true);" in ContextFunctionCatalogAutoConfiguration in the version used by 2023.0.2..

No problem with Spring Boot 3.2.6, Spring Cloud 2023.0.1 .

**Sample**
[demo.zip](https://github.com/user-attachments/files/15539033/demo.zip)

Launch test PbHalApplicationTests#createTestAndCheck :
this error is raised :
```
org.springframework.core.codec.DecodingException: JSON decoding error: Trailing token (of type END_OBJECT) found after value (bound as `org.springframework.hateoas.Link`): not allowed as per `DeserializationFeature.FAIL_ON_TRAILING_TOKENS`
	at org.springframework.http.codec.json.AbstractJackson2Decoder.processException(AbstractJackson2Decoder.java:275)
	Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Body from POST /tests [DefaultClientResponse]
Original Stack Trace:
		at org.springframework.http.codec.json.AbstractJackson2Decoder.processException(AbstractJackson2Decoder.java:275)
		at org.springframework.http.codec.json.AbstractJackson2Decoder.decode(AbstractJackson2Decoder.java:211)
		at org.springframework.http.codec.json.AbstractJackson2Decoder.lambda$decodeToMono$2(AbstractJackson2Decoder.java:191)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
		at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
		at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onComplete(FluxPeekFuseable.java:595)
		at reactor.core.publisher.MonoCallable$MonoCallableSubscription.request(MonoCallable.java:159)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.request(FluxPeekFuseable.java:437)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
		at reactor.core.publisher.Operators$BaseFluxToMonoOperator.request(Operators.java:2067)
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.request(FluxFilterFuseable.java:411)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:360)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194)
		at reactor.core.publisher.BlockingSingleSubscriber.onSubscribe(BlockingSingleSubscriber.java:54)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:265)
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onSubscribe(FluxFilterFuseable.java:305)
		at reactor.core.publisher.Operators$BaseFluxToMonoOperator.onSubscribe(Operators.java:2051)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onSubscribe(FluxPeekFuseable.java:471)
		at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:48)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
		at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
		at reactor.core.publisher.Mono.block(Mono.java:1806)
		at org.springframework.test.web.reactive.server.DefaultWebTestClient$DefaultResponseSpec.expectBody(DefaultWebTestClient.java:442)
		at ch.hug.client.notification.PbHalApplicationTests.createTestAndCheck(PbHalApplicationTests.java:59)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:146)
		at reactor.core.publisher.Mono.block(Mono.java:1807)
		at org.springframework.test.web.reactive.server.DefaultWebTestClient$DefaultResponseSpec.expectBody(DefaultWebTestClient.java:442)
		at ch.hug.client.notification.PbHalApplicationTests.createTestAndCheck(PbHalApplicationTests.java:59)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Trailing token (of type END_OBJECT) found after value (bound as `org.springframework.hateoas.Link`): not allowed as per `DeserializationFeature.FAIL_ON_TRAILING_TOKENS`
 at [Source: (org.springframework.core.io.buffer.DataBufferInputStream); line: 1, column: 119] (through reference chain: org.springframework.hateoas.EntityModel["_links"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportTrailingTokens(DeserializationContext.java:1825)
	at com.fasterxml.jackson.databind.ObjectMapper._verifyNoTrailingTokens(ObjectMapper.java:4933)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4806)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:2363)
	at org.springframework.hateoas.mediatype.hal.Jackson2HalModule$HalLinkListDeserializer.deserialize(Jackson2HalModule.java:607)
	at org.springframework.hateoas.mediatype.hal.Jackson2HalModule$HalLinkListDeserializer.deserialize(Jackson2HalModule.java:554)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeWithUnwrapped(BeanDeserializer.java:735)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:347)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
	at org.springframework.http.codec.json.AbstractJackson2Decoder.decode(AbstractJackson2Decoder.java:206)
	at org.springframework.http.codec.json.AbstractJackson2Decoder.lambda$decodeToMono$2(AbstractJackson2Decoder.java:191)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onComplete(FluxPeekFuseable.java:595)
	at reactor.core.publisher.MonoCallable$MonoCallableSubscription.request(MonoCallable.java:159)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.request(FluxPeekFuseable.java:437)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.request(Operators.java:2067)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.request(FluxFilterFuseable.java:411)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:360)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.request(MonoFlatMap.java:194)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.request(FluxOnAssembly.java:649)
	at reactor.core.publisher.BlockingSingleSubscriber.onSubscribe(BlockingSingleSubscriber.java:54)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onSubscribe(FluxOnAssembly.java:633)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:117)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:265)
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onSubscribe(FluxFilterFuseable.java:305)
	at reactor.core.publisher.Operators$BaseFluxToMonoOperator.onSubscribe(Operators.java:2051)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onSubscribe(FluxPeekFuseable.java:471)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:48)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:76)
	at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4568)
	at reactor.core.publisher.Mono.block(Mono.java:1806)
	at org.springframework.test.web.reactive.server.DefaultWebTestClient$DefaultResponseSpec.expectBody(DefaultWebTestClient.java:442)
	at ch.hug.client.notification.PbHalApplicationTests.createTestAndCheck(PbHalApplicationTests.java:59)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by jhengy-work** [comment]
Is there any update on this? I'm facing the same issue as well

**Comment by olegz** [comment]
Looking

**Comment by olegz** [comment]
I'll take that back, apparently you can, so let me remove it and let other users know that they can set it manually as: 
```
spring:
  jackson:
    deserialization: 
      fail-on-trailing-tokens: true
```

**Comment by olegz** [comment]
Related - https://github.com/spring-cloud/spring-cloud-function/issues/1094

**Comment by olegz** [comment]
I am going to revert this change since the problem has nothing to do with s-c-function as it is not even part of the stack trace of the failure. The issue i suspect is that Hateos have provided their own ObjectMapper over the one from boot and we are simply using it. 
We'll configure our own ObjectMapper so it does not interfere with the provided one

**Comment by davidmestr** [comment]
Hi @olegz ,
Are you planning to release a version with this fix?

Thanks

**Comment by snussbaumer** [comment]
Same problem here, the simple fact of including spring-cloud-function changes the behaviour of the default objectMapper  by adding FAIL_ON_TRAILING_TOKENS. I agree that spring cloud function probably needs must have its own objectMapper if you need to change settings ...

@olegz : this issue should be open again if the code that goes with it has been reverted, no ?

**Comment by mgimenoromanadevinta** [comment]
Hello
The fact that a new ObjectMapper is now instantiated is creating numerous issues, for instance when deserialising a payload into a Kotlin object

Is there a plan to fix this here?
Thanks

**Comment by wabrit** [comment]
Apologies if this is not the place to raise this, but I've had numerous issues moving my Spring Boot app from Spring Cloud 2023.0.1 to 2023.0.2/3, all of which seem to be related to the fact that parts of spring cloud are rolling their own fasterxml ObjectMapper and not taking account of spring boot-based customization.

I've hit this with 

- serialization of Optional<X> values to JSON (presence of `jackson-datatype-jdk8` on classpath should gracefully map Optionals to their value or null)
- fail on trailing tokens issues
- received messages being of type byte[] rather than the expected deserialized from JSON java object

If my guess is correct, are all of these related issues going to be addressed in 2024.0.0? TIA

**Comment by TheMorganHub** [comment]
To be blunt, this change broke so many things. Who thought it'd be a good idea to inject your own `ObjectMapper` completely disregarding the one that's already been registered (and possibly already customised) by the user?

**Comment by wojciech-piotrowiak** [comment]
Would be great to inform us when this fix will be released (milestone is not enough for my case).
With that, I can decide if it is better to wait for the next version or maybe try a workaround

**Comment by kubav182** [comment]
https://github.com/spring-cloud/spring-cloud-function/commit/1cd93cb27000c2bfeca43882961edf22c3000655

why isn't this backported to 4.1.x? @olegz

**Comment by ferblaca** [comment]
@olegz It seems that for Spring Cloud 2023.0.4 it seems to fail again. In Spring Cloud 2023.0.3 version it was fixed.

We also have the same problem again with projects using Spring Cloud Bus + Spring Cloud 2023.0.4.

**Comment by kubav182** [comment]
stupid workaround, but works

```
@Component
@RequiredArgsConstructor
@FieldDefaults(level = PRIVATE, makeFinal = true)
public class ContextRefreshedEventListener implements ApplicationListener<ContextRefreshedEvent> {

    ObjectMapper objectMapper;

    @Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
        objectMapper.configure(FAIL_ON_TRAILING_TOKENS, false);
    }

}
```

**Comment by ferblaca** [comment]
> stupid workaround, but works
> 
> ```
> @Component
> @RequiredArgsConstructor
> @FieldDefaults(level = PRIVATE, makeFinal = true)
> public class ContextRefreshedEventListener implements ApplicationListener<ContextRefreshedEvent> {
> 
>     ObjectMapper objectMapper;
> 
>     @Override
>     public void onApplicationEvent(ContextRefreshedEvent event) {
>         objectMapper.configure(FAIL_ON_TRAILING_TOKENS, false);
>     }
> 
> }
> ```

@kubav182 this workaround works correctly! but for Spring Cloud version 2023.0.3 it was not necessary...

**Comment by ferblaca** [comment]
Downgrading only the `spring-cloud-function-context` to  version `4.1.3` is working properly again.

Is it possible that it could be due to this [change](https://github.com/spring-cloud/spring-cloud-function/commit/63cdb68b3a99bd74abecece017ebfef3a846684f#diff-5dbd14fd4b6bd059c012d8337205cfa457c9447cbb1e249c4b4be07bd011d544)?

**Comment by juliojgd** [comment]
> Downgrading only the `spring-cloud-function-context` to version `4.1.3` is working properly again.
> 
> Is it possible that it could be due to this [change](https://github.com/spring-cloud/spring-cloud-function/commit/63cdb68b3a99bd74abecece017ebfef3a846684f#diff-5dbd14fd4b6bd059c012d8337205cfa457c9447cbb1e249c4b4be07bd011d544)?

@olegz maybe this issue should be reopened? It seems to exist a regression as @ferblaca commented.

**Comment by guerricmerleHUG** [comment]
@olegz i confirm that the issue occurs with Spring Boot 3.3.6 and Spring cloud 2023.0.4.

https://github.com/spring-cloud/spring-cloud-function/issues/1148#issuecomment-2154133452
> I am going to revert this change since the problem has nothing to do with s-c-function as it is not even part of the stack trace of the failure. The issue i suspect is that Hateos have provided their own ObjectMapper over the one from boot and we are simply using it. We'll configure our own ObjectMapper so it does not interfere with the provided one

You think that Spring Hateaos should investigate the problem : do you reopen this issue https://github.com/spring-projects/spring-hateoas/issues/2158 ?

**Comment by adamsmith118** [comment]
> stupid workaround, but works

I second this.
