### ISSUE TITLE
isJsonStringRepresentsCollection for random byte[] array can be true

### ISSUE THREAD

**Issue by zd-dalibor** [spring-cloud/spring-cloud-function#1176]
I think this function `org.springframework.cloud.function.json.JsonMapper#isJsonStringRepresentsCollection` can return true for arbitrary byte[] array value.

I have an issue that sometimes my encrypted data (the encryption returns bytes array as the result) is false positive on this method.
Because of this sometimes some of my messages failed even if my bytes array data does not represent jeson array.

This invocation here does not throw exception sometimes if value object is random byte[] array:
https://github.com/spring-cloud/spring-cloud-function/blob/1cd93cb27000c2bfeca43882961edf22c3000655/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/json/JsonMapper.java#L145

**Comment by olegz** [comment]
Similar issues have been reported and we have addressed them the best way we could. But you have to give me some more info and example of your data so we can take a look and see what we can do.

**Comment by zd-dalibor** [comment]
Here is the example of the error:

```java
java.lang.IllegalStateException: Failed to convert. Possible bug as the conversion probably shouldn't have been attempted here
	at org.springframework.cloud.function.json.JacksonMapper.doFromJson(JacksonMapper.java:65) ~[spring-cloud-function-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.function.json.JsonMapper.fromJson(JsonMapper.java:80) ~[spring-cloud-function-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.fluxifyInputIfNecessary(SimpleFunctionRegistry.java:856) ~[spring-cloud-function-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:742) ~[spring-cloud-function-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:592) ~[spring-cloud-function-context-4.1.2.jar:4.1.2]
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:206) ~[spring-cloud-stream-4.1.3.jar:4.1.3]
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 start byte 0xb4 at [Source: (byte[])"\u0009[l????]^??U!l^?e?S?\u0012?%?u?\u0000?0\u001E2V\u000F???[?#?%??\u001B??#j??????A?a?n\u0008O?\u0003?$?2A??? \u0014??]?<C??6\u000B\u0009???i??>??y3\u0003M?h?\u001F??'??G@aJ^?Xg??F??z\u0016?x?u:%m???,????E?`U}?\u0013??z1Z???@F?\u0018x??-l?}????!\u000E?L?\u0019k?%??\u0018E?\u001E???Xb??\u0003:\u001D??r????\u0007}?A?\u0003?YI\u0005?\u000BY?Fz\u0004???\u0006\u000F??\u0005?C\u0004,0-\u001C??,?p???x?{H-?DUm??EP\u000E>\u0018???M?^?`HA????\u0007+??f\u0017?R\u000C?>?@;\u0011?\u000C\u0010???R?bw1?\u00071S&???Qm!T)?O???D\u000EFp\u000F?cvD?K??eeURW?,n?\u0004b";?b?n>%f?\u000C???7?Z?'??z?"?<\u001B'?\u0007?\u0015?~\u000F???~Kk???9?J:\u0014??8?;??\u0017\u001F???ZP???8?z?\u0017!???]N?\u001Fr4??>??=\u0009f?i?????\u0003??z????K#h?\u0010??t7\u00151?l??,\u0009J??w\u0002e\u0013?IM?\u0012"[truncated 4421 bytes]; line: 1, column: 5]
```

@olegz

**Comment by olegz** [comment]
I understand what you are saying, but in order for us to address it we need more info - a sample payload or better a sample Message with content-type header. As I said, this is a very delicate issue  and has been worked on periodically to address edge cases.

**Comment by zd-dalibor** [comment]
@olegz 
The payload of the message is confidential data.
I will stop sending message as byte array, I will do base64 encoding of binary data and sand message as a string.
Yes, it will take some CPU time more and message will be bigger, but it is better than failed message.
