### ISSUE TITLE
AWSLambdaUtils throw NullPointerException when function return type is com.amazonaws.services.lambda.runtime.events

### ISSUE THREAD

**Issue by AnshulRustogi** [spring-cloud/spring-cloud-function#1210]
<h1>AWSLambdaUtils throw NullPointerException when function return type is com.amazonaws.services.lambda.runtime.events</h1>
Any function on AWS returning an object of S3Event/ScheduledEvent (from package: com.amazonaws.services.lambda.runtime.events) is giving null pointer exception 
<br>

```
java.lang.NullPointerException: Cannot invoke "org.springframework.messaging.Message.getPayload()" because "msg" is null

	at org.springframework.cloud.function.adapter.aws.AWSLambdaUtils.extractPayload(AWSLambdaUtils.java:152)
	at org.springframework.cloud.function.adapter.aws.AWSLambdaUtils.generateOutput(AWSLambdaUtils.java:216)
	at org.springframework.cloud.function.adapter.aws.AWSLambdaUtils.generateOutputFromObject(AWSLambdaUtils.java:208)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.handleRequest(FunctionInvoker.java:95)
```

<h3>Test Case for recreate the issue</h3>

[FunctionInvokerTests.class](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/test/java/org/springframework/cloud/function/adapter/aws/FunctionInvokerTests.java#L1681)
```java
@Test
public void testS3EventAsOutput() throws Exception {
    System.setProperty("MAIN_CLASS", S3Configuration.class.getName());
    System.setProperty("spring.cloud.function.definition", "outputS3Event");
    FunctionInvoker invoker = new FunctionInvoker();

    InputStream targetStream = new ByteArrayInputStream(this.s3Event.getBytes());
    ByteArrayOutputStream output = new ByteArrayOutputStream();
    invoker.handleRequest(targetStream, output, null);
    assertNotNull(output.toByteArray());
}
```
Below function can be added in [S3Configuration subclass](https://github.com/spring-cloud/spring-cloud-function/blob/bc39a181b4b61252ac07d9f31cb3fd586012986b/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/test/java/org/springframework/cloud/function/adapter/aws/FunctionInvokerTests.java#L1681) in test class
```java
@Bean
public Function<S3Event, S3Event> outputS3Event() {
	return v -> {
		System.out.println("Received: " + v);
		return v;
	};
}
```

**Comment by AnshulRustogi** [comment]
Hi, is there any update on the issue?

**Comment by AnshulRustogi** [comment]
@olegz  I believe the current added solution works for S3Event, would it be possible to have a more generic solution to work for all AWS events (eg: lambda events) to not give nullPointerException
