### ISSUE TITLE
spring-cloud-function-adapter-azure 4.2 is not compatible with Azure Function Apps due to spring boot 3.4 dependencies

### ISSUE THREAD

**Issue by swnshp** [spring-cloud/spring-cloud-function#1219]
spring-cloud-function-adapter-azure version 4.2

Error on Spring Startup when invoking an Azure Function trigger:

```
[2024-12-15T20:40:14.472Z] Exception: ClassNotFoundException: com.google.gson.Strictness
[2024-12-15T20:40:14.472Z] Stack: java.lang.IllegalStateException: Failed to initialize
[2024-12-15T20:40:14.473Z]      at org.springframework.cloud.function.adapter.azure.AzureFunctionInstanceInjector.getInstance(AzureFunctionInstanceInjector.java:84)
[2024-12-15T20:40:14.473Z]      at com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource.getFunctionInstance(ExecutionContextDataSource.java:103)
[2024-12-15T20:40:14.473Z]      at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:20)
[2024-12-15T20:40:14.473Z]      at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:22)
[2024-12-15T20:40:14.473Z]      at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
[2024-12-15T20:40:14.473Z]      at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
[2024-12-15T20:40:14.473Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invoke(JavaFunctionBroker.java:133)
[2024-12-15T20:40:14.473Z]      at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:124)
[2024-12-15T20:40:14.473Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
[2024-12-15T20:40:14.473Z]      at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[2024-12-15T20:40:14.473Z]      at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
[2024-12-15T20:40:14.473Z]      at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
[2024-12-15T20:40:14.473Z]      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-12-15T20:40:14.473Z]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-12-15T20:40:14.473Z]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-12-15T20:40:14.473Z]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-12-15T20:40:14.473Z]      at java.base/java.lang.Thread.run(Thread.java:840)
```

This appears to be caused as

- spring-cloud-function-adapter-azure 4.2 will cause spring-cloud-function-context 4.2 to be included will cause spring-boot-autoconfigure 3.4 to be included
- spring-boot-autoconfigure 3.4 contains GsonAutoConfiguration.java with a dependency on GsonBuilder.setStrictness and com.google.gson.Strictness which comes in gson 2.11.0
- The Azure Java Functions Worker contains gson 2.9.0 which satisfies the @ConditionalOnClass of the GsonAutoConfiguration class

Attempting to add 2.11.0 as a dependency will move the error on (it can now find com.google.gson.Strictness ) but it won't find the setStrictness method, presumably as gson 2.9.0 is preferred on the class path.

Workarounds are:

- Force spring-boot-autoconfigure 3.3 in the application pom.xml
- Exclude the GsonAutoConfiguration class (e.g `@SpringBootApplication(exclude = {org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration.class})`)

**Comment by olegz** [comment]
Can you please include the relevant part of the exception.
```
Stack: java.lang.IllegalStateException: Failed to initialize
[2024-12-15T20:40:14.473Z]      at org.springframework.cloud.function.adapter.azure.AzureFunctionInstanceInjector.getInstance(AzureFunctionInstanceInjector.java:84)
```
. .  only shows s-c-function re-throwing it as `IllegalStateException`, but there should be additional stack trace that shows where in s-c-function the actual error occured

**Comment by swnshp** [comment]
The full stack trace is below

```
Executed 'Functions.logSomething' (Failed, Id=1454d76a-d7af-4e41-8b9b-7c84fef4d489, Duration=1803ms)
System.Private.CoreLib: Exception while executing function: Functions.logSomething. System.Private.CoreLib: Result: Failure
Exception: ClassNotFoundException: com.google.gson.Strictness
Stack: java.lang.IllegalStateException: Failed to initialize
     at org.springframework.cloud.function.adapter.azure.AzureFunctionInstanceInjector.getInstance(AzureFunctionInstanceInjector.java:84)
     at com.microsoft.azure.functions.worker.binding.ExecutionContextDataSource.getFunctionInstance(ExecutionContextDataSource.java:103)
     at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:20)
     at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:22)
     at com.microsoft.azure.functions.worker.chain.FunctionExecutionMiddleware.invoke(FunctionExecutionMiddleware.java:19)
     at com.microsoft.azure.functions.worker.chain.InvocationChain.doNext(InvocationChain.java:21)
     at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:125)
     at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:34)
     at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
     at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:44)
     at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:94)
     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
     at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: java.lang.NoClassDefFoundError: com/google/gson/Strictness
     at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:823)
     at org.springframework.boot.SpringApplication.run(SpringApplication.java:328)
     at org.springframework.cloud.function.adapter.azure.AzureFunctionInstanceInjector.initialize(AzureFunctionInstanceInjector.java:99)
     at org.springframework.cloud.function.adapter.azure.AzureFunctionInstanceInjector.getInstance(AzureFunctionInstanceInjector.java:70)
     ... 15 more
Caused by: java.lang.NoClassDefFoundError: com/google/gson/Strictness
     at java.base/java.lang.Class.getDeclaredFields0(Native Method)
     at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
     at java.base/java.lang.Class.getDeclaredField(Class.java:2608)
     at org.springframework.boot.context.properties.bind.DefaultBindConstructorProvider$Constructors.isInnerClass(DefaultBindConstructorProvider.java:144)
     at org.springframework.boot.context.properties.bind.DefaultBindConstructorProvider$Constructors.getCandidateConstructors(DefaultBindConstructorProvider.java:134)
     at org.springframework.boot.context.properties.bind.DefaultBindConstructorProvider$Constructors.getConstructors(DefaultBindConstructorProvider.java:103)
     at org.springframework.boot.context.properties.bind.DefaultBindConstructorProvider.getBindConstructor(DefaultBindConstructorProvider.java:55)
     at org.springframework.boot.context.properties.ConfigurationPropertiesBean.deduceBindMethod(ConfigurationPropertiesBean.java:288)
     at org.springframework.boot.context.properties.ConfigurationPropertiesBeanRegistrar.createBeanDefinition(ConfigurationPropertiesBeanRegistrar.java:94)
     at org.springframework.boot.context.properties.ConfigurationPropertiesBeanRegistrar.registerBeanDefinition(ConfigurationPropertiesBeanRegistrar.java:88)
     at org.springframework.boot.context.properties.ConfigurationPropertiesBeanRegistrar.register(ConfigurationPropertiesBeanRegistrar.java:70)
     at org.springframework.boot.context.properties.ConfigurationPropertiesBeanRegistrar.register(ConfigurationPropertiesBeanRegistrar.java:64)
     at java.base/java.lang.Iterable.forEach(Iterable.java:75)
     at org.springframework.boot.context.properties.EnableConfigurationPropertiesRegistrar.registerBeanDefinitions(EnableConfigurationPropertiesRegistrar.java:49)
     at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86)
     at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:387)
     at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
     at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:386)
     at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:149)    
     at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:121)
     at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:430)
     at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:290)
     at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349)
     at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118)
     at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:791)
     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:609)
     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
     at org.springframework.boot.SpringApplication.run(SpringApplication.java:318)
     ... 17 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.Strictness
     at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
     ... 46 more
```

However, you will not find any exception in the s-c package as it's indirectly caused by the spring-cloud-function-adapter-azure 4.2.0 version including Spring Boot 3.4 as a dependency which appears to be incompatible with the Azure Function Java Worker given it packages up an older GSON package which lacks the Strictness functionality used by Spring Boot 3.4.

This project: https://github.com/swnshp/azure-function-template will demonstrate the issue if you replace ` @SpringBootApplication(exclude = {org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration.class})` with `@SpringBootApplication` in com.seanwinship.azurefunctiontemplate.AzureFunctionTemplateApplication

**Comment by olegz** [comment]
It appears that Azure Java Function Worker just bumped the Gson version to 2.11 - https://github.com/Azure/azure-functions-java-worker/commit/5bf24b508604d1118c91d35b014ed0aaa5a6c885

**Comment by olegz** [comment]
So it appears that there is nothing we can do on the function side. You can use your workaround for now until versions catch up.

**Comment by olegz** [comment]
Ok, I am closing it.
