### ISSUE TITLE
Issue running spring-cloud-function-samples

### ISSUE THREAD

**Issue by maheshvra** [spring-cloud/spring-cloud-function#126]
Hi - I am exploring spring-cloud-function to leverage this framework for serverless deployment. I am  facing an issue when running function-sample project. Below is the stacktrace. Please advise.

```
java -jar function-sample-1.0.0.BUILD-SNAPSHOT.jar
Exception in thread "main" java.lang.IllegalStateException: Cannot locate library: /Users/amg871/.m2/repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.7.RELEASE/spring-boot-thin-launcher-1.0.7.RELEASE-exec.jar
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:113)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:90)
```

**Comment by artembilan** [comment]
Works for me.

I cleaned my local Maven repo.
I ran `mvnw clean install`.
That took definitely some time to download a half of the Internet for me, but in the end I'm able to jump into the `function-sample` - `\spring-cloud-function\spring-cloud-function-samples\function-sample\target\` and run the mentioned `java -jar function-sample-1.0.0.BUILD-SNAPSHOT.jar` command.

I get an NPE there though:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compiledUppercase' defined in com.example.SampleApplication: Invocation of init method failed; nested exception
is java.lang.NullPointerException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at com.example.SampleApplication.main(SampleApplication.java:76) [function-sample-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_144]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [spring-boot-thin-launcher-1.0.7.RELEASE-exec.jar:1.0.7.RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [spring-boot-thin-launcher-1.0.7.RELEASE-exec.jar:1.0.7.RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [spring-boot-thin-launcher-1.0.7.RELEASE-exec.jar:1.0.7.RELEASE]
        at org.springframework.boot.loader.thin.ThinJarLauncher.launch(ThinJarLauncher.java:186) [spring-boot-thin-launcher-1.0.7.RELEASE-exec.jar:1.0.7.RELEASE]
        at org.springframework.boot.loader.thin.ThinJarLauncher.main(ThinJarLauncher.java:133) [spring-boot-thin-launcher-1.0.7.RELEASE-exec.jar:1.0.7.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_144]
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:118) [function-sample-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:90) [function-sample-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
Caused by: java.lang.NullPointerException: null
        at org.springframework.cloud.function.compiler.java.RuntimeJavaCompiler.compile(RuntimeJavaCompiler.java:56) ~[spring-cloud-function-compiler-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
        at org.springframework.cloud.function.compiler.AbstractFunctionCompiler.buildAndCompileSourceCode(AbstractFunctionCompiler.java:159) ~[spring-cloud-function-compiler-1.0.0.BUILD-SNAPSHOT.jar:1
.0.0.BUILD-SNAPSHOT]
        at org.springframework.cloud.function.compiler.AbstractFunctionCompiler.compile(AbstractFunctionCompiler.java:116) ~[spring-cloud-function-compiler-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHO
T]
        at org.springframework.cloud.function.compiler.proxy.AbstractLambdaCompilingProxy.afterPropertiesSet(AbstractLambdaCompilingProxy.java:65) ~[spring-cloud-function-compiler-1.0.0.BUILD-SNAPSHOT
.jar:1.0.0.BUILD-SNAPSHOT]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        ... 31 common frames omitted
```

But that may be just a problem of my Windows, not the issue with missed jar in the Maven local.

**Comment by maheshvra** [comment]
@artembilan i am still getting the below error after cleaning up local maven repository.

```java.lang.IllegalStateException: Cannot locate library: /Users/amg871/.m2/repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.7.RELEASE/spring-boot-thin-launcher-1.0.7.RELEASE-exec.jar```

**Comment by artembilan** [comment]
Do you do `mvnw clean install` for the whole project?

**Comment by dsyer** [comment]
Works for me too. What is your environment (OS, version etc.)?

**Comment by maheshvra** [comment]
@dsyer I use Mac OS, java version "1.8.0_74", apache-maven-3.3.9

**Comment by dsyer** [comment]
Still works for me. Are you behind a nasty corporate proxy or something?
