### ISSUE TITLE
ClassNotFoundException: org.springframework.boot.loader.thin.ThinJarLauncher

### ISSUE THREAD

**Issue by rohanliston** [spring-cloud/spring-cloud-function#134]
Following the instructions, I ran `./mvnw clean install` at the root of the project and `java -jar spring-cloud-function-samples/function-sample/target/*.jar`, but got the following error:

```
Exception in thread "main" java.lang.ClassNotFoundException: org.springframework.boot.loader.thin.ThinJarLauncher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:117)
	at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:90)
```

Details:
**Branch:** `master`
**OS:** Ubuntu 16.04 x64
**Output of java -jshowversion:**
```
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

The only difference that I can see from the setup in `.travis.yml` is that I'm using OpenJDK8 as opposed to Oracle JDK8. Is that the likely cause, or should it not matter?

**Comment by dsyer** [comment]
Works for me. Looks like you got a bad jar. Try clearing your maven cache locally (just the `org.springframework.boot.experimental` bit probably).

**Comment by quaff** [comment]
@rohanliston do you fixed it? I have the same problem.

**Comment by ReionChan** [comment]
@quaff It works!
