### ISSUE TITLE
ClassNotFoundException: ServletInputStream with WebFlux

### ISSUE THREAD

**Issue by nurkiewicz** [spring-cloud/spring-cloud-function#169]
Application won't start if Spring Boot 2.x and WebFlux is used. Servlet API is not on CLASSPATH, therefore I get:

        org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fluxHandlerMethodArgumentResolver' defined in class path resource [org/springframework/cloud/function/web/flux/ReactorAutoConfiguration$FluxArgumentResolverConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.function.web.flux.request.FluxHandlerMethodArgumentResolver]: Factory method 'fluxHandlerMethodArgumentResolver' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/servlet/ServletInputStream
                at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:587) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:61) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
                at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
                at com.example.demo.DemoApplication.main(DemoApplication.java:10) [main/:na]
        Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.function.web.flux.request.FluxHandlerMethodArgumentResolver]: Factory method 'fluxHandlerMethodArgumentResolver' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/servlet/ServletInputStream
                at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                ... 18 common frames omitted
        Caused by: java.lang.NoClassDefFoundError: javax/servlet/ServletInputStream
                at org.springframework.cloud.function.web.flux.ReactorAutoConfiguration$FluxArgumentResolverConfiguration.fluxHandlerMethodArgumentResolver(ReactorAutoConfiguration.java:91) ~[spring-cloud-function-web-1.0.0.M5.jar:1.0.0.M5]
                at org.springframework.cloud.function.web.flux.ReactorAutoConfiguration$FluxArgumentResolverConfiguration$$EnhancerBySpringCGLIB$$2e585745.CGLIB$fluxHandlerMethodArgumentResolver$0(<generated>) ~[spring-cloud-function-web-1.0.0.M5.jar:1.0.0.M5]
                at org.springframework.cloud.function.web.flux.ReactorAutoConfiguration$FluxArgumentResolverConfiguration$$EnhancerBySpringCGLIB$$2e585745$$FastClassBySpringCGLIB$$9bc80652.invoke(<generated>) ~[spring-cloud-function-web-1.0.0.M5.jar:1.0.0.M5]
                at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                at org.springframework.cloud.function.web.flux.ReactorAutoConfiguration$FluxArgumentResolverConfiguration$$EnhancerBySpringCGLIB$$2e585745.fluxHandlerMethodArgumentResolver(<generated>) ~[spring-cloud-function-web-1.0.0.M5.jar:1.0.0.M5]
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_141]
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_141]
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_141]
                at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_141]
                at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.5.RELEASE.jar:5.0.5.RELEASE]
                ... 19 common frames omitted
        Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletInputStream
                at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_141]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_141]
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_141]
                at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_141]
                ... 30 common frames omitted

My `build.gradle` is as follows:

	buildscript {
		ext {
			springBootVersion = '2.0.1.RELEASE'
		}
		repositories {
			mavenCentral()
		}
		dependencies {
			classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		}
	}

	apply plugin: 'java'
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'

	sourceCompatibility = 1.8

	repositories {
		mavenCentral()
		maven { url "https://repo.spring.io/milestone" }
	}

	dependencies {
		compile('org.springframework.boot:spring-boot-starter-webflux')
		compile 'org.springframework.cloud:spring-cloud-function-web:1.0.0.M5'
	}

I'm running:

    ./gradlew bootRun

**Comment by dsyer** [comment]
`spring-cloud-function-web` is a servlet API library. You can't use it with WebFlux.

**Comment by regmebaby** [comment]
Are there any plans to provide a webflux compatible version of spring cloud function?

**Comment by dsyer** [comment]
Yes, but not in 1.0. Can you explain why you need it?
