### ISSUE TITLE
NoSuchMethodError when deploying to AWS

### ISSUE THREAD

**Issue by dan-lind** [spring-cloud/spring-cloud-function#177]
My pom looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.com.lumy</groupId>
    <artifactId>rp-client</artifactId>
    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>

    <!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-function-parent -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.2.RELEASE</version>
        <relativePath />
    </parent>


    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <wrapper.version>1.0.11.RELEASE</wrapper.version>
        <aws-lambda-events.version>2.1.0</aws-lambda-events.version>
        <!--<reactor.version>3.1.2.RELEASE</reactor.version>-->
        <spring-cloud-function.version>1.0.0.M6</spring-cloud-function.version>
        <spring-cloud-stream-servlet.version>1.0.0.M6</spring-cloud-stream-servlet.version>
        <start-class>com.lumy.Application</start-class>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-function-adapter-aws -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-function-adapter-aws</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-function-web</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-function-compiler</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>${aws-lambda-events.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>1.2.0</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-function-dependencies</artifactId>
                <version>${spring-cloud-function.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-stream-binder-servlet</artifactId>
                <version>${spring-cloud-stream-servlet.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>


            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>org.springframework.boot.experimental</groupId>
                        <artifactId>spring-boot-thin-layout</artifactId>
                        <version>${wrapper.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                    <shadedClassifierName>aws</shadedClassifierName>
                </configuration>
            </plugin>

        </plugins>
    </build>


    <repositories>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/libs-snapshot-local</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/libs-milestone-local</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-releases</id>
            <name>Spring Releases</name>
            <url>https://repo.spring.io/release</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/libs-snapshot-local</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>false</enabled>
            </releases>
        </pluginRepository>
        <pluginRepository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/libs-milestone-local</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
        <pluginRepository>
            <id>spring-releases</id>
            <name>Spring Releases</name>
            <url>https://repo.spring.io/libs-release-local</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>


</project>
```

Handler
```
public class Handler extends SpringBootRequestHandler<PersonalNumber, Name> {
}
```

Application with Bean definition
```
@SpringBootApplication
public class Application {

    private static final Logger log = LoggerFactory.getLogger(Application.class);

    @Autowired
    CollectClient collectClient;

    @Autowired
    AuthClient authClient;

    @Autowired
    RestTemplate restTemplate;

    public static void main(String args[]) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public Function<PersonalNumber, Name> function() {
        return personalNumber -> {
           ...
        };
    }
```

I have uploaded the -aws.jar , but when testing the Lambda function I'm getting the following exception:
```
java.lang.NoSuchMethodError: org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.setBeanFactory(Lorg/springframework/beans/factory/BeanFactory;)V
	at org.springframework.cloud.function.compiler.config.FunctionProxyApplicationListener.bind(FunctionProxyApplicationListener.java:108)
	at org.springframework.cloud.function.compiler.config.FunctionProxyApplicationListener.onApplicationEvent(FunctionProxyApplicationListener.java:75)
	at org.springframework.cloud.function.compiler.config.FunctionProxyApplicationListener.onApplicationEvent(FunctionProxyApplicationListener.java:48)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:91)
	at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:66)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
	at org.springframework.cloud.function.adapter.aws.SpringFunctionInitializer.initialize(SpringFunctionInitializer.java:91)
	at org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.handleRequest(SpringBootRequestHandler.java:44)
```

What am I doing wrong?

**Comment by dan-lind** [comment]
I realised that RC1 had been released, so changed to 
```
<spring-cloud-function.version>1.0.0.RC1</spring-cloud-function.version>
<spring-cloud-stream-servlet.version>1.0.0.RC1</spring-cloud-stream-servlet.version>
```
But the error remains

**Comment by dan-lind** [comment]
I looked some more into the source
org.springframework.cloud.function.compiler.config.FunctionProxyApplicationListener has this method:
```
private void bind(ConfigurableApplicationContext context) {
		ConfigurationPropertiesBindingPostProcessor post = new ConfigurationPropertiesBindingPostProcessor();
		post.setBeanFactory(new DefaultListableBeanFactory());
		post.setEnvironment(context.getEnvironment());
		post.setApplicationContext(new StaticApplicationContext());
		try {
			post.afterPropertiesSet();
		}
		catch (Exception e) {
			throw new IllegalStateException("Cannot bind properties", e);
		}
		post.postProcessBeforeInitialization(this, getClass().getName());
	}
```

But ConfigurationPropertiesBindingPostProcessor in Spring Boot 2.X no longer has the methods 
setBeanFactory() and setEnvironment();

Perhaps I overlooked something. Does this lib not support Spring Boot 2.X yet?

**Comment by dsyer** [comment]
Why do you need `spring-cloud-function-compiler` in your app? I can't see it being used anywhere.

**Comment by dan-lind** [comment]
Thanks for fixing, and thanks for pointing out the unnecessary dependency 👍
