### ISSUE TITLE
how to run function-sample ?

### ISSUE THREAD

**Issue by power-man** [spring-cloud/spring-cloud-function#192]
When I use the sample project "function sample" that provided on your home page, the project reports an error, the following is the error message.
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.3.RELEASE)

2018-07-26 17:33:02.620  INFO 2056 --- [           main] com.example.SampleApplication            : Starting SampleApplication on bestliu with PID 2056 (C:\Users\bestliu\Desktop\spring-cloud-function-master\spring-cloud-function-samples\function-sample\target\classes started by bestliu in C:\Users\bestliu\Desktop\spring-cloud-function-master\spring-cloud-function-samples\function-sample)
2018-07-26 17:33:02.626  INFO 2056 --- [           main] com.example.SampleApplication            : No active profile set, falling back to default profiles: default
2018-07-26 17:33:02.789  INFO 2056 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@12b0404f: startup date [Thu Jul 26 17:33:02 CST 2018]; root of context hierarchy
2018-07-26 17:33:04.359  INFO 2056 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2018-07-26 17:33:05.025  INFO 2056 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2018-07-26 17:33:05.073  INFO 2056 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-07-26 17:33:05.073  INFO 2056 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.31
2018-07-26 17:33:05.101  INFO 2056 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [D:\Java\jdk1.8.0_151\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;D:/Java/jdk1.8.0_151/bin/../jre/bin/server;D:/Java/jdk1.8.0_151/bin/../jre/bin;D:/Java/jdk1.8.0_151/bin/../jre/lib/amd64;D:\Java\jdk1.8.0_151\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\nssm-2.23\win64;C:\Program Files (x86)\Git\cmd;E:\apache-maven-3.3.9\bin;D:\uc;E:\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\System32\OpenSSH\;D:\Program Files\TortoiseGit\bin;C:\Users\bestliu\AppData\Local\Microsoft\WindowsApps;JAVA_HOME\bin;C:\Users\bestliu\AppData\Roaming\npm;;E:\sts-bundle\sts-3.8.3.RELEASE;;.]
2018-07-26 17:33:05.372  INFO 2056 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-07-26 17:33:05.372  INFO 2056 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2586 ms
2018-07-26 17:33:05.709  INFO 2056 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2018-07-26 17:33:05.723  INFO 2056 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-07-26 17:33:05.724  INFO 2056 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-07-26 17:33:05.724  INFO 2056 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-07-26 17:33:05.724  INFO 2056 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-07-26 17:33:05.879  INFO 2056 --- [           main] o.s.c.f.c.AbstractFunctionCompiler       : Initial code property value :'s -> s.toUpperCase()'
2018-07-26 17:33:05.883  INFO 2056 --- [           main] o.s.c.f.c.AbstractFunctionCompiler       : Processed code property value :
return (Function<String,String> & java.io.Serializable) s -> s.toUpperCase();

2018-07-26 17:33:05.883  INFO 2056 --- [           main] o.s.c.f.c.AbstractFunctionCompiler       : 
package org.springframework.cloud.function.compiler;
import java.util.*;
import java.time.*;
import java.util.function.*;
import reactor.core.publisher.Flux;
public class CompiledUppercaseFunctionFactory implements CompilationResultFactory<Function> {
 public Function<String,String> getResult() {
  return (Function<String,String> & java.io.Serializable) s -> s.toUpperCase();
 }
}

2018-07-26 17:33:05.883  INFO 2056 --- [           main] o.s.c.f.c.java.RuntimeJavaCompiler       : Compiling source for class org.springframework.cloud.function.compiler.CompiledUppercaseFunctionFactory using compiler com.sun.tools.javac.api.JavacTool
2018-07-26 17:33:09.040  WARN 2056 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compiledUppercase' defined in com.example.SampleApplication: Invocation of init method failed; nested exception is org.springframework.cloud.function.compiler.java.CompilationFailedException: ==========
import reactor.core.publisher.Flux;
                             ^^^^^
ERROR:程序包reactor.core.publisher不存在
==========

2018-07-26 17:33:09.044  INFO 2056 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-07-26 17:33:09.059  INFO 2056 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-07-26 17:33:09.071 ERROR 2056 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compiledUppercase' defined in com.example.SampleApplication: Invocation of init method failed; nested exception is org.springframework.cloud.function.compiler.java.CompilationFailedException: ==========
import reactor.core.publisher.Flux;
                             ^^^^^
ERROR:程序包reactor.core.publisher不存在
==========

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1708) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at com.example.SampleApplication.main(SampleApplication.java:76) [classes/:na]
Caused by: org.springframework.cloud.function.compiler.java.CompilationFailedException: ==========
import reactor.core.publisher.Flux;
                             ^^^^^
ERROR:程序包reactor.core.publisher不存在
==========

	at org.springframework.cloud.function.compiler.AbstractFunctionCompiler.compile(AbstractFunctionCompiler.java:126) ~[classes/:na]
	at org.springframework.cloud.function.compiler.proxy.AbstractLambdaCompilingProxy.afterPropertiesSet(AbstractLambdaCompilingProxy.java:65) ~[classes/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1767) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1704) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 16 common frames omitted

**Comment by olegz** [comment]
Hav you gone through [sample projects](https://cloud.spring.io/spring-cloud-function/) provided on our home page?
Also, with your formatting it's very difficult to understand what's going on. You can follow [this cheatsheet](https://stackoverflow.com/questions/tagged/spring-cloud-function) to fix it

**Comment by power-man** [comment]
What's wrong when I use the demo?

**Comment by power-man** [comment]
Is there a problem with my use or is the jar package not introduced?

**Comment by power-man** [comment]
I know why I am getting an error. Because of the order in which the beans are loaded, I added @DependsOn("compiler") to some other beans.

**Comment by power-man** [comment]
iii
