### ISSUE TITLE
How to register filter specially for cors filter specially OPTIONS request

### ISSUE THREAD

**Issue by abhinav-jain09** [spring-cloud/spring-cloud-function#229]
Hi Team,

I am using spring cloud function (inside spring boot )with Azure and GraphQL . Since graphql does not support the OPTIONS method need to write from my own as an filter . I have created the java file as following but it is not working. not sure if I need to do extra configuration 
handler function is as follows

```
public class ContentHandler extends AzureSpringBootRequestHandler<String, ExecutionResult> {
	
	@FunctionName("queryHippoContent1")
	public ExecutionResult run(
			@HttpTrigger(name = "req", methods = {HttpMethod.OPTIONS,
					HttpMethod.POST }, authLevel = AuthorizationLevel.ANONYMOUS)String bar ,
			ExecutionContext context) {
	   	return	handleRequest(bar, context);
	}

```
filter is as follows 
```
@Configuration
public class CorsConfig {
    @Bean
    public FilterRegistrationBean corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("*");
        config.addAllowedHeader("*");
        config.addAllowedMethod("*");
        source.registerCorsConfiguration("/**", config);
        FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
        bean.setOrder(0);
        return bean;
    }
}
```

when I run the above configuation then get following error 

```
itialized context: catalog=org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$BeanFactoryFunctionCatalog@34007a6b
[11/6/2018 1:07:59 PM] value
[11/6/2018 1:07:59 PM] Result: value
Exception: value
Stack: java.lang.NullPointerException: value
[11/6/2018 1:07:59 PM]  at java.util.Objects.requireNonNull(Objects.java:228)
[11/6/2018 1:07:59 PM]  at reactor.core.publisher.FluxJust.<init>(FluxJust.java:60)
[11/6/2018 1:07:59 PM]  at reactor.core.publisher.Flux.just(Flux.java:1184)
[11/6/2018 1:07:59 PM]  at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.extract(AzureSpringBootRequestHandler.java:94)
[11/6/2018 1:07:59 PM]  at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:55)
[11/6/2018 1:07:59 PM]  at com.ns.sdw.querycontent.ContentHandler.run(ContentHandler.java:36)
```

I am not sure what else I have to do inroder to respond to the OPTIONS request

**Comment by olegz** [comment]
I believe this issue has just been resolved as part of another issue (see edba4c42 and 3fed1f1c). Judging by your stack trace it appears you have some form of supplier (null input, some output). 

So, i'll close this issue for now, but please feel free to re-open it if you still think there is work that needs to be done
