### ISSUE TITLE
Detection of Function-Class fails

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-function#234]
I tried the latest snapshot with the riff java-function-invoker and the detection of a plain Java class with a function implementation now fails whether `handler` is specified or not.

Sample app: https://github.com/trisberg/upper

Tried both of these variants when running the java-function-invoker: 

` --function.uri='file:///workspace/app?handler=functions.Upper'`
` --function.uri='file:///workspace/app'`

I get the same error for both:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.function.deployer.FunctionCreatorConfiguration': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Cannot create functions
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.cloud.function.deployer.ContextRunner$1.run(ContextRunner.java:65)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Cannot create functions
	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration.init(FunctionCreatorConfiguration.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 17 more
Caused by: java.lang.IllegalStateException: SpringApplication not available and main class requested: functions.Upper
	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration$BeanCreator.run(FunctionCreatorConfiguration.java:406)
	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration.init(FunctionCreatorConfiguration.java:122)
	... 24 more
```

**Comment by dsyer** [comment]
The s-c-f build was failing yesterday. Should be OK now. Give it another try with `-U`.

**Comment by trisberg** [comment]
It's still an issue. I have created a PR for a test for detecting the function class from META-INF here: https://github.com/projectriff/java-function-invoker/pull/112. We should be good when CI for this PR passes.

**Comment by olegz** [comment]
I've confirmed that it is still an issue as well. Got identical stacktrace

**Comment by olegz** [comment]
Tracked it down to 0287a5d commit. `Function-Class` should not be treated/assumed as the one having a `main(..)`. Fixing it.

I
