### ISSUE TITLE
Issue with basic constructor injection in functional beans when spring-cloud-function auto-configuration is enabled 

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-function#352]
EDITED FROM ORIGINAL DESCRIPTION:
The following doesn't really work albeit very common:
```
@Bean
public String field() {
	return "value";
}

@Component
public static class StringSuppiler implements Supplier<String> {
	private String field;

	public StringSuppiler(@Autowired @Qualifier("field") String field) {
		this.field = field;
	}

	@Override
	public String get() {
		return field;
	}
}
``` 
The result is :
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simpleFunctionRabbitDemoApplication.StringSuppiler' defined in file [/Users/olegz/Downloads/simple-function-rabbit-demo/target/classes/oz/example/simplefunctionrabbitdemo/SimpleFunctionRabbitDemoApplication$StringSuppiler.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [oz.example.simplefunctionrabbitdemo.SimpleFunctionRabbitDemoApplication$StringSuppiler]: No default constructor found; nested exception is java.lang.NoSuchMethodException: oz.example.simplefunctionrabbitdemo.SimpleFunctionRabbitDemoApplication$StringSuppiler.<init>()
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1287) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1181) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:602) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:590) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$BeanFactoryFunctionCatalog.afterPropertiesSet(ContextFunctionCatalogAutoConfiguration.java:102) ~[spring-cloud-function-context-2.1.0.BUILD-SNAPSHOT.jar:2.1.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 30 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [oz.example.simplefunctionrabbitdemo.SimpleFunctionRabbitDemoApplication$StringSuppiler]: No default constructor found; nested exception is java.lang.NoSuchMethodException: oz.example.simplefunctionrabbitdemo.SimpleFunctionRabbitDemoApplication$StringSuppiler.<init>()
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:83) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1279) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 42 common frames omitted
Caused by: java.lang.NoSuchMethodException: oz.example.simplefunctionrabbitdemo.SimpleFunctionRabbitDemoApplication$StringSuppiler.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_121]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[na:1.8.0_121]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:78) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 43 common frames omitted

```

**Comment by Walliee** [comment]
Hey @olegz, I think I figured out what's happening. The issue only happens when a `BeanFactoryPostProcessor` bean that depends on the `FunctionCatalog` is present. 

Due to the order in which `AbstractApplicationContext` executes/registers `BeanFactoryPostProcesor` and `BeanPostProcessor` beans on refresh. This causes `BeanFactoryFunctionCatalog` creation kicks in before `AutowiredAnnotationBeanPostProcessor` has been registered. 

https://github.com/spring-projects/spring-framework/blob/3a0f309e2c9fdbbf7fb2d348be861528177f8555/spring-context/src/main/java/org/springframework/context/support/AbstractApplicationContext.java#L530-L534

Consequently, bean creation for any non-no-arg constructor classes fail. Postponing the catalog building till after the application is ready seems to resolve the issue.

**Comment by Walliee** [comment]
Actually, waiting till `ApplicationReadyEvent` was a little too late and caused some test to fail as the catalog hadn't been constructed yet. 

I switched to use `SmartInitializingSingleton` which seems to be more appropriate.
