### ISSUE TITLE
Local Git deploy of Spring Cloud Function on Azure Function App fails to find Function

### ISSUE THREAD

**Issue by josh-roberts-phision** [spring-cloud/spring-cloud-function#356]
All artifacts make it to site/wwwroot correctly, but when function is triggered get the following error:
```
Result: Failure
Exception: IllegalStateException: No function defined with name=myFunction
Stack: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:54)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:51)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: No function defined with name=myFunction
	at org.springframework.cloud.function.adapter.azure.AzureSpringFunctionInitializer.lookup(AzureSpringFunctionInitializer.java:174)
	at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:54)
	at josh.phision.MyAzureSpringBootHandler.run(MyAzureSpringBootHandler.java:50)
	... 16 more
```
`
Deploying via azure-functions-maven-plugin works as expected.

Noticed in the Invocation Details that the working azure-functions-maven-plugin deploy logs a message: "Initialized context: catalog=org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$BeanFactoryFunctionCatalog@59242e70"

Whereas the Local Git deployed function app logs: "Initialized context: catalog=null"

**Comment by olegz** [comment]
Can you please specify what version of spring-cloud-function you are using?
Also, some details on how to reproduce

**Comment by josh-roberts-phision** [comment]
2.1.0.RELEASE

- Create a Function App in the Azure Portal and setup Local Git deploy in Deployment Center.
- Create a basic Java function, deploy using Local Git
   - package the Function using the azure maven function plugin
   - Clone the git repo from the Function App git url
   - add the appropriate artifacts (everything inside of target/azure-functions)
   - commit + push

**Comment by olegz** [comment]
Sorry, but there is no 2.1.0.RELEASE. We just did RC1 few weeks ago

**Comment by josh-roberts-phision** [comment]
Sorry, that was a typo, 2.0.1.RELEASE

**Comment by olegz** [comment]
Ok, just in case, can you please try with 2.1.0.RC1 while I am investigating it?

**Comment by olegz** [comment]
Closing it as sample was updated, validated and tested on target platform - https://github.com/spring-cloud/spring-cloud-function/issues/431
