### ISSUE TITLE
On AWS with functional bean registration, autowiring Context is not happenning

### ISSUE THREAD

**Issue by kleung** [spring-cloud/spring-cloud-function#368]
Under functional bean registration on AWS Lambda, the following @autowired method was not executed:

@Autowired
@Qualifier("targetExecutionContext")
public void setContext(Context context) {
	LOG.info("context: " + context);
	this.context = context;
}

This causes NullPointerException when the function needs access to the Context object.

**Comment by kleung** [comment]
I tried autowiring it from within the main class and the function class, both are throwing NullPointerException when accessing the context object.

**Comment by olegz** [comment]
@kleung First it would help if you post the stack trace so we can see where the NPE is actually happening.
Also, this I believe have been reported in the past and is related to how the JAR is packaged so @Walliee was kind enough to provide an updated [README](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-adapters/spring-cloud-function-adapter-aws). See if that helps otherwise please provide stack trace

**Comment by kleung** [comment]
Sorry I forgot to leave the stack trace, please see the followings:

2019-05-20 13:30:28.371 INFO 1 --- [or-http-epoll-3] reactor.Flux.MonoRepeatPredicate.1 : onSubscribe(FluxRepeatPredicate.RepeatPredicateSubscriber)
2019-05-20 13:30:28.371 INFO 1 --- [or-http-epoll-3] reactor.Flux.MonoRepeatPredicate.1 : request(256)
2019-05-20 13:30:28.372 ERROR 1 --- [or-http-epoll-3] reactor.Flux.MonoRepeatPredicate.1 : onError(io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: localhost/127.0.0.1:80)
2019-05-20 13:30:28.372 ERROR 1 --- [or-http-epoll-3] reactor.Flux.MonoRepeatPredicate.1 : 

io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: localhost/127.0.0.1:80
at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source) ~[task/:na]
Caused by: io.netty.channel.unix.Errors$NativeConnectException: syscall:getsockopt(..) failed: Connection refused
... 1 common frames omitted

2019-05-20 13:30:28.373 INFO 1 --- [or-http-epoll-3] reactor.Flux.MonoRepeatPredicate.1 : onSubscribe(FluxRepeatPredicate.RepeatPredicateSubscriber)
java.lang.NullPointerException: java.lang.NullPointerException
java.lang.NullPointerException
at com.test.TestAwsLambdaAuthorizer.cloudFunction.AuthorizerFunction.apply(AuthorizerFunction.java:34)
at com.test.TestAwsLambdaAuthorizer.cloudFunction.AuthorizerFunction.apply(AuthorizerFunction.java:15)
at org.springframework.cloud.function.core.FluxFunction.lambda$apply$0(FluxFunction.java:41)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
at reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:99)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
at reactor.core.publisher.BlockingIterable$SubscriberIterator.onSubscribe(BlockingIterable.java:218)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)
at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
at reactor.core.publisher.Flux.subscribe(Flux.java:7799)
at reactor.core.publisher.BlockingIterable.iterator(BlockingIterable.java:80)
at org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.result(SpringBootRequestHandler.java:59)
at org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.handleRequest(SpringBootRequestHandler.java:52)


Note that the Cloud Function throws NullPointerException when it tries to access the Context, which I tried to inject with qualifier targetExecutionContext.

Also, as you can see, the netty error is also logged.

The following is my main class and function:

TestAwsLambdaAuthorizerApplication.java:

--imports--

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.test.TestAwsLambdaAuthorizer.cloudFunction.AuthorizerFunction;
import com.test.TestAwsLambdaAuthorizer.cloudFunction.TestFunction;
import com.test.TestAwsLambdaAuthorizer.model.AuthPolicy;

@SpringBootConfiguration
public class TestAwsLambdaAuthorizerApplication implements ApplicationContextInitializer<GenericApplicationContext> {
	
	private static final Logger LOG = LoggerFactory.getLogger(TestAwsLambdaAuthorizerApplication.class);
	
	private Context context;
	
	@Autowired
	public void setContext(Context context) {
		LOG.info("Context: {}", context);
		
		this.context = context;
	}
	
	public static void main(String[] args) {
		FunctionalSpringApplication.run(TestAwsLambdaAuthorizerApplication.class, args);
	}

	public AuthorizerFunction authorizer() {
		return new AuthorizerFunction();
	}
	
	public TestFunction testFunction() {
		return new TestFunction();
	}
	
	@Override
	  public void initialize(GenericApplicationContext context) {
	    context.registerBean("authorizer", FunctionRegistration.class,
	        () -> 
	        	new FunctionRegistration<>(authorizer())
	            .type(FunctionType.from(APIGatewayProxyRequestEvent.class).to(AuthPolicy.class))
	        );
	    
	    context.registerBean("testFunction", FunctionRegistration.class,
		        () -> 
		        	new FunctionRegistration<>(testFunction())
		            .type(FunctionType.from(String.class).to(String.class))
		        );

	  }
}

AuthorizerFunction.java:
--imports--
public class AuthorizerFunction implements Function<APIGatewayProxyRequestEvent, AuthPolicy> {
	
	private static final Logger LOG = LoggerFactory.getLogger(AuthorizerFunction.class);
	
	private Context context;
	
	public AuthorizerFunction() {
		super();
	}

	@Autowired
	@Qualifier("targetExecutionContext")
	public void setContext(Context context) {
		LOG.info("Context: {}", context);
		this.context = context;
	}
	
	@Override
	public AuthPolicy apply(APIGatewayProxyRequestEvent event) {		
		String functionArn = context.getInvokedFunctionArn();
		LOG.info("ARN: {}", functionArn);
		
		String[] arnPartials = functionArn.split(":");
		String region = arnPartials[3];
		
		APIGatewayProxyRequestEvent.ProxyRequestContext requestContext = event.getRequestContext();
		
		String awsAccountId = requestContext.getAccountId();
    	String restApiId = requestContext.getApiId();
    	String stage = requestContext.getStage();
		
		AuthPolicy result = new AuthPolicy("fake-principal", 
												AuthPolicy.PolicyDocument.getDenyAllPolicy(region, 
																							awsAccountId, 
																							restApiId, 
																							stage));
		
		Map<String, String> headers = event.getHeaders();
		String apiKey = headers.get("x-api-key");
		LOG.info("api key: {}", apiKey);
		
		if((!StringUtils.isEmpty(apiKey)) && ("abcd1234".equalsIgnoreCase(apiKey))) {
			result = new AuthPolicy("fake-principal",
										AuthPolicy.PolicyDocument.getAllowAllPolicy(region, 
																						awsAccountId, 
																						restApiId, 
																						stage));
		}
				
		return result;
	}
}

Since none of the "Context: {}" logs were printed in the aws CloudWatch, I think the autowired methods were never called.

**Comment by kleung** [comment]
Sorry @olegz , any advice?

**Comment by dmartyniuk** [comment]
I've faced with the same issue.
@olegz , can you please assist.

**Comment by kleung** [comment]
@dmartyniuk , I just saw a paragraph in the documentation called "Limitations of Functional Bean Declaration", you might want to give it a try, sorry I stepped away from my lambda project at work for quite some time and stopped being active on this topic...

**Comment by olegz** [comment]
There have been many improvements and enhancements in AWS functionality as well as improvement and enhancements in core functionality, so please give it a shot and if you still have an issue feel free to raise a new one.
