### ISSUE TITLE
NPE for non-existent function in web adapter

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#386]
Create a function with spring-cloud-starter-function-webflux and use `FunctionalSpringApplication`. Run it. POST to /non-existent. Instead of a 404 you get a 500:

```
2019-07-09 13:32:49.401 ERROR 32199 --- [or-http-epoll-2] a.w.r.e.AbstractErrorWebExceptionHandler : [8d54095a] 500 Server Error for HTTP POST "/registration_com.example.functions.Greeter"

java.lang.NullPointerException: null
	at org.springframework.cloud.function.web.RequestProcessor.response(RequestProcessor.java:243) ~[classes/:na]
	at org.springframework.cloud.function.web.RequestProcessor.post(RequestProcessor.java:156) ~[classes/:na]
	at org.springframework.cloud.function.web.function.FunctionEndpointFactory.lambda$null$0(FunctionEndpointInitializer.java:235) ~[classes/:na]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.2.8.RELEASE.jar:3.2.8.RELEASE]
...
```

I don't know if this is a problem with a regular `@SpringBootApplication`, or if it is a problem with MVC. Probably same code path though.

**Comment by olegz** [comment]
It appears to be not just webflux but any non-existent function. I was able to easily reproduce it
