### ISSUE TITLE
Azure Functions Issues after upgrading to Spring Boot 2.2.0.RELEASE

### ISSUE THREAD

**Issue by miller79** [spring-cloud/spring-cloud-function#424]
I have an application using Spring Cloud Function with the following dependencies.

- Spring Boot Parent 2.1.3.RELEASE
- Spring Cloud Dependencies Greenwich.SR1

I upgraded to the following dependencies.

- Spring Boot Parent 2.2.0.RELEASE
- Spring Cloud Dependencies Greenwich.SR1

Now I receive the following error:

```
[11/9/2019 8:26:53 PM] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionCatalog' defined in class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.function.context.FunctionRegistry]: Factory method 'functionCatalog' threw exception; nested exception is java.lang.IllegalStateException: No bean class specified on bean definition
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:645) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:625) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.0.RELEASE.jar:2.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.cloud.function.adapter.azure.AzureSpringFunctionInitializer.initialize(AzureSpringFunctionInitializer.java:149) [spring-cloud-function-adapter-azure-2.0.2.RELEASE.jar:2.0.2.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:52) [spring-cloud-function-adapter-azure-2.0.2.RELEASE.jar:2.0.2.RELEASE]
[11/9/2019 8:26:53 PM] 	at com.jbhunt.security.batch.cas.cleanup.configuration.CasCleanupHandler.execute(CasCleanupHandler.java:13) [batch_security_cas_nonprod_data_cleanup-LOCAL-SNAPSHOT.jar:LOCAL-SNAPSHOT]
[11/9/2019 8:26:53 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22) [azure-functions-java-worker.jar:1.5.2-SNAPSHOT]
[11/9/2019 8:26:53 PM] 	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:54) [azure-functions-java-worker.jar:1.5.2-SNAPSHOT]
[11/9/2019 8:26:53 PM] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:53) [azure-functions-java-worker.jar:1.5.2-SNAPSHOT]
[11/9/2019 8:26:53 PM] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33) [azure-functions-java-worker.jar:1.5.2-SNAPSHOT]
[11/9/2019 8:26:53 PM] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10) [azure-functions-java-worker.jar:1.5.2-SNAPSHOT]
[11/9/2019 8:26:53 PM] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45) [azure-functions-java-worker.jar:1.5.2-SNAPSHOT]
[11/9/2019 8:26:53 PM] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92) [azure-functions-java-worker.jar:1.5.2-SNAPSHOT]
[11/9/2019 8:26:53 PM] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.function.context.FunctionRegistry]: Factory method 'functionCatalog' threw exception; nested exception is java.lang.IllegalStateException: No bean class specified on bean definition
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	... 34 common frames omitted
[11/9/2019 8:26:53 PM] Caused by: java.lang.IllegalStateException: No bean class specified on bean definition
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.AbstractBeanDefinition.getBeanClass(AbstractBeanDefinition.java:423) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.cloud.function.context.config.FunctionContextUtils.findType(FunctionContextUtils.java:70) ~[spring-cloud-function-context-2.0.2.RELEASE.jar:2.0.2.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$ContextFunctionRegistry.findType(ContextFunctionCatalogAutoConfiguration.java:582) ~[spring-cloud-function-context-2.0.2.RELEASE.jar:2.0.2.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$ContextFunctionRegistry.wrap(ContextFunctionCatalogAutoConfiguration.java:455) ~[spring-cloud-function-context-2.0.2.RELEASE.jar:2.0.2.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$ContextFunctionRegistry.lambda$merge$6(ContextFunctionCatalogAutoConfiguration.java:433) ~[spring-cloud-function-context-2.0.2.RELEASE.jar:2.0.2.RELEASE]
[11/9/2019 8:26:53 PM] 	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$ContextFunctionRegistry.merge(ContextFunctionCatalogAutoConfiguration.java:433) ~[spring-cloud-function-context-2.0.2.RELEASE.jar:2.0.2.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration.functionCatalog(ContextFunctionCatalogAutoConfiguration.java:110) ~[spring-cloud-function-context-2.0.2.RELEASE.jar:2.0.2.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$$EnhancerBySpringCGLIB$$4d392568.CGLIB$functionCatalog$1(<generated>) ~[spring-cloud-function-context-2.0.2.RELEASE.jar:2.0.2.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$$EnhancerBySpringCGLIB$$4d392568$$FastClassBySpringCGLIB$$4a1a52d6.invoke(<generated>) ~[spring-cloud-function-context-2.0.2.RELEASE.jar:2.0.2.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$$EnhancerBySpringCGLIB$$4d392568.functionCatalog(<generated>) ~[spring-cloud-function-context-2.0.2.RELEASE.jar:2.0.2.RELEASE]
[11/9/2019 8:26:53 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_232]
[11/9/2019 8:26:53 PM] 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.0.RELEASE.jar:5.2.0.RELEASE]
[11/9/2019 8:26:53 PM] 	... 35 common frames omitted
```

No other changes was made to the application outside of the version update.  Let me know if anyone has any ideas.  I am going to use the older version for now.

**Comment by olegz** [comment]
You specified the same dependencies, so I don' know what you really upgraded from. But just as an FYI, Greenwich cloud BOM is not compatible with boot 2.2. To use boot 2.2 you need to upgrade to Hoxton which is at RC1

**Comment by miller79** [comment]
Sorry I must have copy pasted the dependencies too fast.  I have updated my first comment.  I also wasn’t aware that Greenwich was not compatible with Spring Boot 2.2.0.  I’ll try with Hoxton when I get the chance and see if I have more success.

**Comment by miller79** [comment]
Ok I attempted to use Spring Cloud Hoxton RC1 and I'm not receiving the following error:

```
Stack: java.lang.IllegalStateException: Failed to discover main class. An attempt was made to discover main class as 'MAIN_CLASS' environment variable, system property as well as entry in META-INF/MANIFEST.MF (in that order).
[11/10/2019 10:07:52 PM] 	at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.getStartClass(AbstractSpringFunctionAdapterInitializer.java:288)
[11/10/2019 10:07:52 PM] 	at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.<init>(AbstractSpringFunctionAdapterInitializer.java:100)
[11/10/2019 10:07:52 PM] 	at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.<init>(AzureSpringBootRequestHandler.java:44)
[11/10/2019 10:07:52 PM] 	at com.jbhunt.security.batch.cas.cleanup.configuration.CasCleanupHandler.<init>(CasCleanupHandler.java:9)
[11/10/2019 10:07:52 PM] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11/10/2019 10:07:52 PM] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[11/10/2019 10:07:52 PM] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11/10/2019 10:07:52 PM] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[11/10/2019 10:07:52 PM] 	at java.lang.Class.newInstance(Class.java:442)
[11/10/2019 10:07:52 PM] 	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.lambda$execute$1(JavaMethodExecutor.java:54)
[11/10/2019 10:07:52 PM] 	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:20)
[11/10/2019 10:07:52 PM] 	at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:54)
[11/10/2019 10:07:52 PM] 	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:53)
[11/10/2019 10:07:52 PM] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[11/10/2019 10:07:52 PM] 	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[11/10/2019 10:07:52 PM] 	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[11/10/2019 10:07:52 PM] 	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[11/10/2019 10:07:52 PM] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11/10/2019 10:07:52 PM] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11/10/2019 10:07:52 PM] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11/10/2019 10:07:52 PM] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11/10/2019 10:07:52 PM] 	at java.lang.Thread.run(Thread.java:748)
[11/10/2019 10:07:52 PM] Caused by: java.lang.IllegalArgumentException: Failed to locate main class
[11/10/2019 10:07:52 PM] 	at org.springframework.util.Assert.notNull(Assert.java:198)
[11/10/2019 10:07:52 PM] 	at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.getStartClass(AbstractSpringFunctionAdapterInitializer.java:284)
[11/10/2019 10:07:52 PM] 	... 21 more
[11/10/2019 10:07:52 PM] .
```

Looking into `AbstractSpringFunctionAdapterInitializer`, it appears to be looking for the value `Start-Class` inside the MANIFEST.MF.  Opening up the manifest in the created Jar file, I see that field so I'm not sure why its stating that error.  However when I specify the property MAIN_CLASS, it works fine.  I've tried this both locally and deployed on Azure directly.

**Comment by aropop** [comment]
@miller79 I had the same issue, however when adding Start-Class to the manifest file, the issue was resolved.

**Comment by miller79** [comment]
@aropop I looked into the compiled jar and it already contained the Start-Class in the manifest file (I’m guessing this comes from the spring boot plugin).  I’m not sure why it wouldn’t pick that one up vs placing it there manually.

**Comment by aropop** [comment]
@miller79 I had the same error, however after I (with maven jar plugin) added the Start-Class property, the error was resolved. You could try to debug AbstractSpringFunctionAdapterInitializer.getStartClass your function to see why it is failing.

**Comment by miller79** [comment]
@aropop Yes I went down that path at first.  It's pretty confusing why it won't find that variable.  I am deploying from the jar directly and opening the jar file, the Start-Class is in the manifest so its very confusing why it doesn't work.  I can provide screen shots and examples if you would like to see it.

**Comment by olegz** [comment]
Guys, while it may not affect s-c-functions as much, keep in mind that Greenwich BOM is generally dependent on boot 2.1.x. Hoxton BOM is based on boot 2.2.x

**Comment by olegz** [comment]
I am going to close this as it was already established that boot 2.2.0 is not compatible with spring-cloud BOM below Hoxton.

**Comment by miller79** [comment]
> I am going to close this as it was already established that boot 2.2.0 is not compatible with spring-cloud BOM below Hoxton.

Should we open another issue related to the specific Hoxton issue since there were two separate issues in this thread?

**Comment by olegz** [comment]
Yes, feel free to open a separate Hoxton related issue providing as much details as possible. You can reference this issue as well
