### ISSUE TITLE
AWS Adapter cannot discover 'MAIN_CLASS'

### ISSUE THREAD

**Issue by Schntzlbrmpf** [spring-cloud/spring-cloud-function#439]
**Versions Used**

* Working:
  * Spring Cloud Function 2.1.1.RELEASE
  * Spring Boot 2.2.1.RELEASE
* Not Working
  * Spring Cloud Function 3.0.1.RELEASE
  * Spring Boot 2.2.1.RELEASE

**Problem**

The project works with Spring Cloud Function Version 2.1.1.RELEASE. The issue I have is that when I update to the latest spring-cloud function version, i.e. 3.0.1.RELEASE and then deploy the shaded jar into AWS, the Lambda runtime can no longer find the main-class in the manifest and reports the following:

```
12:52:00.957 [main] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Searching manifests: [jar:file:/var/runtime/lib/LambdaJavaRTEntry-1.0.jar!/META-INF/MANIFEST.MF, jar:file:/var/runtime/lib/aws-lambda-java-core-1.2.0.jar!/META-INF/MANIFEST.MF, file:/var/task/META-INF/MANIFEST.MF]
12:52:00.960 [main] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Searching manifest: jar:file:/var/runtime/lib/LambdaJavaRTEntry-1.0.jar!/META-INF/MANIFEST.MF
12:52:00.967 [main] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Searching manifest: jar:file:/var/runtime/lib/aws-lambda-java-core-1.2.0.jar!/META-INF/MANIFEST.MF
12:52:00.967 [main] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Searching manifest: file:/var/task/META-INF/MANIFEST.MF
12:52:00.980 [main] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Searching manifests: []
...
Failed to discover main class. An attempt was made to discover main class as 'MAIN_CLASS' environment variable, system property as well as entry in META-INF/MANIFEST.MF (in that order).: java.lang.IllegalStateException
java.lang.IllegalStateException: Failed to discover main class. An attempt was made to discover main class as 'MAIN_CLASS' environment variable, system property as well as entry in META-INF/MANIFEST.MF (in that order).
	at org.springframework.cloud.function.utils.FunctionClassUtils.getStartClass(FunctionClassUtils.java:82)
	at org.springframework.cloud.function.utils.FunctionClassUtils.getStartClass(FunctionClassUtils.java:59)
	at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.<init>(AbstractSpringFunctionAdapterInitializer.java:96)
	at org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.<init>(SpringBootRequestHandler.java:44)
	at ch.sbb.cargo.visuelle.wagenkontrolle.mds.server.adapter.aws.SpringBootApiGatewayRequestHandler.<init>(SpringBootApiGatewayRequestHandler.java:69)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Caused by: java.lang.IllegalArgumentException: Failed to locate main class
	at org.springframework.util.Assert.notNull(Assert.java:198)
	at org.springframework.cloud.function.utils.FunctionClassUtils.getStartClass(FunctionClassUtils.java:78)
	... 8 more
...
```
The Manifest file in the shaded jar contains an entry *start-class* and *main-class* containing the Main class which I specified in the maven poms.
I have seen similiar issues like this one https://github.com/spring-cloud/spring-cloud-function/issues/431 for the Azure apapter but none so for for the AWS adapter.
The issue goes way when I set the *MAIN_CLASS* in an environment variable of the Lambda runtime or as a java system property. So I assume it is a shading or resource transformation issue but I cannot find the source.

**Set up**

I have a small maven project which defines functions with spring cloud functions in one maven module and the AWS integration in a sibbling module. Both sibblings inherit from a parent defining common dependencies, properties etc. The parent in turn inherits from spring boot starter parent like so:
```
-> spring-boot-starter-parent
     -> my.parent
          -> my.functions
          -> my.aws.adapter
``` 
Here is the *my-parent* pom:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.2.1.RELEASE</version>
    <relativePath/>
  </parent>

  <modelVersion>4.0.0</modelVersion>

  <groupId>my.spring.functions</groupId>
  <artifactId>my.spring.functions.parent</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <spring-cloud-function.version>2.1.1.RELEASE</spring-cloud-function.version>
  </properties>
  
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-function-context</artifactId>
        <!-- using Version 3.0.0.RELEASE gives us class cast exceptions for all functions not using Flux as input and return type  -->
        <version>${spring-cloud-function.version}</version>
      </dependency>
      <!-- adapter for spring boot -->
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-function-adapter-aws</artifactId>
        <version>${spring-cloud-function.version}</version>
      </dependency>

      <!-- Testing Dependencies -->
      <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>2.6</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <modules>
    <module>my.spring.functions.impl</module>
    <module>my.spring.functions.aws</module>
  </modules>
</project>
``` 
Here is the *my.functions.aws* pom:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>my.spring.functions</groupId>
    <artifactId>my.spring.functions.parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <artifactId>my.spring.functions.aws</artifactId>

  <properties>
    <!-- not pretty to reference this class here - but there is no other way for now -->
    <start-class>my.spring.functions.ServerlessApp</start-class>
  </properties>

  <dependencies>
    <!-- adapter for spring boot -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-function-adapter-aws</artifactId>
    </dependency>
    <!-- aws lambda SDK dependencies are all provided by lambda runtime -->
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-core</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-events</artifactId>
      <version>2.2.7</version>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-log4j2</artifactId>
      <version>1.1.0</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
      <version>1.13</version>
    </dependency>

    <dependency>
      <groupId>my.spring.functions</groupId>
      <artifactId>my.spring.functions.impl</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- Test dependencies -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.junit.vintage</groupId>
          <artifactId>junit-vintage-engine</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
          <annotationProcessorPaths>
            <path>
              <groupId>org.springframework</groupId>
              <artifactId>spring-context-indexer</artifactId>
              <version>${spring-framework.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <dependencies>
          <dependency>
            <groupId>org.springframework.boot.experimental</groupId>
            <artifactId>spring-boot-thin-layout</artifactId>
            <version>1.0.22.RELEASE</version>
          </dependency>
        </dependencies>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <configuration>
          <createDependencyReducedPom>false</createDependencyReducedPom>
          <!-- there is a bug in scs artifactory which makes maven-dependency-plugin request fail most of the time because it cannot find the dependency.
               It uses the build timestamp instead of the snapshot extension of the artifact name. When not using a classifier this issue does not occur. -->
          <!-- different than spring cloud examples: do not attach the shaded artifact this making shaded artifact this module's the main artifact -->
          <!-- artifact containing only the classes will not be installed or deployed -->
          <shadedArtifactAttached>false</shadedArtifactAttached>
          <!-- different than spring cloud examples: do not append a classifier to the artifact and its file name -->
          <!-- <shadedClassifierName>aws</shadedClassifierName>-->
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

Here is the *my.functions.impl* pom:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>my.spring.functions</groupId>
    <artifactId>my.spring.functions.parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <artifactId>my.spring.functions.impl</artifactId>

  <properties>
    <!-- not sure if this reference is actually required -->
    <start-class>my.spring.functions.ServerlessApp</start-class>
    <org.mapstruct.version>1.3.1.Final</org.mapstruct.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-function-context</artifactId>
      <!-- using Version 3.0.0.RELEASE gives us class cast exceptions for all functions not using Flux as input and return type  -->
    </dependency>
    <!-- logging for spring beans and lambda functions -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-log4j2</artifactId>
    </dependency>
    <!-- Bean Validation -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
      <exclusions>
        <exclusion>
          <!-- since we are using spring-boot-starter-log4j2 we must exclude spring-boot-starter-logging -->
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <!-- workaround because we must have the Main Class in this project and instantiate a Jackson2ObjectMapperBuilder here
         most likely a consequence of shading -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
    </dependency>
    <!-- allow jackson to (de)serialize java.time data types -->
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
      <version>2.10.0</version>
    </dependency>
    <!-- to allow mapping code to inspect this class -->
    <dependency>
      <groupId>org.openapitools</groupId>
      <artifactId>jackson-databind-nullable</artifactId>
      <version>0.2.0</version>
    </dependency>

    <!-- database access -->
    <dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-mongodb</artifactId>
      <version>2.2.3.RELEASE</version>
    </dependency>
    <!-- Bean mapping -->
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
      <version>${org.mapstruct.version}</version>
    </dependency>

    <!-- dependency for IDE so it helps with defining the correct properties -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <scope>provided</scope>
      <optional>true</optional>
    </dependency>

    <!-- Test dependencies -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <version>2.2.1.RELEASE</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.junit.vintage</groupId>
          <artifactId>junit-vintage-engine</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.6</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>findbugs</artifactId>
      <version>3.0.1</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
          <!-- generate Mappers at compile time -->
          <annotationProcessorPaths>
            <!-- works only here probably because there already is another processor -->
            <path>
              <groupId>org.springframework</groupId>
              <artifactId>spring-context-indexer</artifactId>
              <version>${spring-framework.version}</version>
            </path>
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${org.mapstruct.version}</version>
            </path>
          </annotationProcessorPaths>
          <compilerArgs>
            <!-- generate Spring Context based component model to access the Mappers -->
            <compilerArg>-Amapstruct.defaultComponentModel=spring</compilerArg>
          </compilerArgs>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

The Main class is defined in this maven module. It is written to the manifest in both sibbling maven modules as *start-class* and *main-class*.  And here is the main class:

```java
package my.spring.functions;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import org.openapitools.jackson.nullable.JsonNullableModule;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.SpringBootConfiguration;

import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;

import org.springframework.http.converter.json.Jackson2ObjectMapperBuilder;

/**
 * Main Class
 */
@SpringBootConfiguration
@Import({FunctionConfiguration.class, ContextFunctionCatalogAutoConfiguration.class})
public class ServerlessApp {

    private static final Logger LOGGER = LogManager.getLogger(ServerlessApp.class);

    public static void main(String[] args) throws Exception {
        LOGGER.info("Starting up");
        SpringApplication.run(ServerlessApp.class, args);
    }

    /**
     * @return a Jackson2ObjectMapperBuilder with default configuration which does everything we need for now
     */
    @Bean
    public Jackson2ObjectMapperBuilder getJackson2ObjectMapperBuilder() {
        Jackson2ObjectMapperBuilder mapperBuilder = new Jackson2ObjectMapperBuilder();
        mapperBuilder.modulesToInstall(new JsonNullableModule());
        return mapperBuilder;
    }

    @Bean
    @ConditionalOnMissingBean({ObjectMapper.class})
    public ObjectMapper objectMapper(Jackson2ObjectMapperBuilder builder) {
        return builder.createXmlMapper(false).build();
    }
}
```

**Comment by olegz** [comment]
@Schntzlbrmpf sorry for the late reply, i guess you know the reason ;)

Yes there was an issue, but it was fixed and in fact there was some additional work as well to simplify a lot of things resulting in a new [Getting Started guide](https://cloud.spring.io/spring-cloud-static/spring-cloud-function/3.0.1.RELEASE/reference/html/aws.html#_getting_started) that would take you step-by-step. Also, the [AWS example](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-aws) was improved as well.
I am also a bit confused about your setup, the two POMs, the fact that you are explicitly importing configurations and the lack of actual function in your app. So can you please look at the example just mentioned. You can also push your project on Github and I can take a look.

**Comment by Schntzlbrmpf** [comment]
Hello, it is good to hear somebody spent the holiday season properly :-) ...

The purpose of having multiple poms is the following:
1. my.parent: common configuration, e.g. java version etc.
2. my.functions: all logic. contains only references to spring-cloud-function but nothing adapter specific
3. my.aws.adapter: all setup for AWS integration, e.g. log settings, API Gateway Integration, deployment scripts etc.
I separated the modules so I can (in theory) deploy to AWS and Azure if I ever have to.

I explicitly imported Configuration classes so I can avoid classpath scanning which is required for AutoConfiguration. This is in my effort to decrease cold startup time and to avoid initializing stuff I know I will not need. Importing _ContextFunctionCatalogAutoConfiguration.class_ was the fastet way I could get spring-cloud-function to initialize properly.

I did already read the new getting started guide for which you provided the link. So there is nothing new there, I think.

I uploaded a drastically reduced version of my actual project - see [my.spring.functions.zip](https://github.com/spring-cloud/spring-cloud-function/files/4052652/my.spring.functions.zip). The only thing missing is spring-data-mongodb and the required setup. The thing is that this version is runnig with both version 2.1.1.RELEASE and 3.0.1.RELEASE. Is it possible that spring-data-mongodb somehow interferes? Or do you consider it more likely that I removed the mistake when I removed not required stuff?

**Comment by Schntzlbrmpf** [comment]
Hello, is there anything I can do to expedite handling this issue?

**Comment by olegz** [comment]
@Schntzlbrmpf the issue with MAIN_CLASS had existed before and was addressed for 3.x. That said I am going to look at this shortly and if it is a bug we'll address it for 3.0.2.
However, you have not answered my question about going through a brand new Getting Started guide for AWS which was partially created to alleviate common user miss-configurations.

**Comment by olegz** [comment]
@Schntzlbrmpf I was just looking at your sample I don't see any code in `my.spring.functions.aws`. What I am looking for is `Handler` implementation, the one you point to when you deploy to AWS. Can you please clarify? I don't see it with either version.

**Comment by Schntzlbrmpf** [comment]
Hello, I think I did answer the question about the new Getting Started guide:

I did already read the new getting started guide for which you provided the link. So there is nothing new there, I think.

I could not find anything in there which pointed me to a potential miss-configuration. I might have missed something though.

**Comment by Schntzlbrmpf** [comment]
The project _my.spring.functions.aws_ is empty in this example. My original project contains: 
- Log configuration for Log4J2
- some mapping code specific to Amazon API Gateway
- a patched version of SpringBootApiGatewayRequestHandler which does some logging and contains the fix for this issue: https://github.com/spring-cloud/spring-cloud-function/issues/249. The fix was merged into version 3.0.x. But since I am stuck with 2.1.1 I had to backport it.

I am using _org.springframework.cloud.function.adapter.aws.SpringBootApiGatewayRequestHandler_ as the handler implementation and I am setting the environment variable "FUNCTION_NAME" to _my.spring.functions.functions.MyFunction_ - see ![image](https://user-images.githubusercontent.com/31515942/73353028-c40bfd80-4292-11ea-99c3-77ae99c28ed0.png)

Does that clarify my set up enough or do you need more information?

**Comment by olegz** [comment]
About Getting Started guide, there is new thing there:
_. . .When ask about handler you specify org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest which is a generic request handler. . ._ - https://cloud.spring.io/spring-cloud-static/spring-cloud-function/3.0.1.RELEASE/reference/html/spring-cloud-function.html#_getting_started_2

Basically we have a new implementation of the request handler which is designed to handle all types of request handlers, so the old once (including the one you're pointing to) are going to be deprecated soon.

That said, I was able to reproduce your issue, sop looking. . .

**Comment by Schntzlbrmpf** [comment]
Yeah - I read about that - I simply thought changing the handler implementation would be best in a follow up step after upgrading. But since I cannot upgrade I did not get that far :-) ...

**Comment by olegz** [comment]
Also, here is what I was able to discover and for that I would suggest going through your POMs and see what is a miss, but. . .
Here is your manifest:
```
Manifest-Version: 1.0
Implementation-Title: my.spring.functions.aws
Implementation-Version: 0.0.1-SNAPSHOT
Start-Class: my.spring.functions.ServerlessApp
Spring-Boot-Classes: 
Build-Jdk-Spec: 1.8
Spring-Boot-Version: 2.2.1.RELEASE
Created-By: Maven Archiver 3.4.0
Main-Class: my.spring.functions.ServerlessApp
```
and here is the manifest from a working and recently updated [AWS sample](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-aws)
```
Manifest-Version: 1.0
Implementation-Title: function-sample-aws
Implementation-Version: 2.0.0.RELEASE
Start-Class: example.FunctionConfiguration
Spring-Boot-Classes: 
Build-Jdk-Spec: 1.8
Spring-Boot-Version: 2.2.2.RELEASE
Created-By: Maven Archiver 3.4.0
Main-Class: org.springframework.boot.loader.wrapper.ThinJarWrapper
```

Notice how Main-Class points to `ThinJarWrapper` and your's not. I am not necessarily saying this is the core issue, but there is definitely some kind of mismatch.

I'll try to look at it some more when I get a chance, but hope you'll get there quicker since you have all the moving parts

**Comment by olegz** [comment]
Ok, i see what the actual issue is. The culprit is in this code which adds additional filtering to which class are considered valid start classes in the context of lambda deployment and we specifically ask for `@SpringBootApplication` while you're using `@SpringBootConfiguration`
```
if (startClass.getDeclaredAnnotation(SpringBootApplication.class) != null) {
		logger.info("Loaded Start Class: " + startClass);
		return startClass;
}
```
I'll fix it and also add more diagnostic information so in the future we have more info to go by.

**Comment by Schntzlbrmpf** [comment]
Thank you. 

Did you follow up on the observation about the Manifest which contains the class instead of the ThinJarWrapper (https://github.com/spring-cloud/spring-cloud-function/issues/439#issuecomment-579732979)?

Do you already know when 3.0.2.RELEASE will be available? Where can I find an early access build containing your fix?

**Comment by olegz** [comment]
No, I did not follow up, but it is probably something to do with versioning of the boot plugin as well as shaded jar. . .
You can check the versions with the POM AWS sample i linked.

The 3.0.2 is next week (i say ~wednesday)

**Comment by Schntzlbrmpf** [comment]
Hello,

I tested my sample project with Spring Cloud Function version 3.0.2 and the old SpringBootApiGatewayRequestHandler. The Main class is found now and the handler is called.

Thank you for fixing this issue.
