### ISSUE TITLE
Non-functional version of AWS custom runtime sample barfs on startup

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-function#466]
If you use `@Configuration` instead of an `ApplicationContextInitializer` the app blows up on startup:

```
2020-03-24 14:47:14.387  INFO 13868 --- [           main] o.s.c.f.web.source.SupplierExporter      : Starting
2020-03-24 14:47:14.395  INFO 13868 --- [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : Looking up function 'origin|' with acceptedOutputTypes: []
2020-03-24 14:47:14.403  WARN 13868 --- [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : !!! Failed to discover function 'origin|' in function catalog. Function available in catalog are: [foobar, origin, functionRouter]
2020-03-24 14:47:14.403  WARN 13868 --- [           main] o.s.c.f.web.source.SupplierExporter      : No such Supplier: origin|
2020-03-24 14:47:14.416  INFO 13868 --- [           main] o.s.c.f.web.source.SupplierExporter      : Stopping
2020-03-24 14:47:14.424  WARN 13868 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'sourceForwarder'; nested exception is reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException
2020-03-24 14:47:14.454  INFO 13868 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-03-24 14:47:14.461 ERROR 13868 --- [           main] o.s.boot.SpringApplication               : Application run failed
...
Caused by: reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException
Caused by: java.lang.NullPointerException: null
        at org.springframework.cloud.function.web.source.SupplierExporter.stop(SupplierExporter.java:136) ~[spring-cloud-function-web-3.0.4.BUILD-SNAPSHOT.jar:3.0.4.BUILD-SNAPSHOT]
        at org.springframework.cloud.function.web.source.SupplierExporter.lambda$start$1(SupplierExporter.java:120) ~[spring-cloud-function-web-3.0.4.BUILD-SNAPSHOT.jar:3.0.4.BUILD-SNAPSHOT]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:243) ~[reactor-core-3.3.2.RELEASE.jar:3.3.2.RELEASE]
...
```

It looks like maybe the `FunctionCatalog` is of the wrong type?

**Comment by olegz** [comment]
I have seen this before and it has to do with the fact that `subscription` is null. Why? Not sure, but may be it's time to look

**Comment by dsyer** [comment]
The NPE is actually only a side effect of the main problem. It occurs on shutdown if the function exporter failed on startup. It's actually the WARN that is the root of the problem. It would be good to fix both of course.
