### ISSUE TITLE
Failed to instantiate [org.springframework.cloud.function.context.FunctionRegistry]: Factory method ‘functionCatalog’

### ISSUE THREAD

**Issue by joaquindiez** [spring-cloud/spring-cloud-function#471]
**Describe the bug**

Starting up a Spring Boot application that use :

  dependencyManagement {
    imports { 
      mavenBom "org.springframework.boot:spring-boot-dependencies:2.1.9.RELEASE"
    }
    imports {
      mavenBom "org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR4"
    }
  }

- 

**Log Output**
Error creating bean with name ‘functionCatalog’ defined in class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.function.context.FunctionRegistry]: Factory method ‘functionCatalog’ threw exception; nested exception is java.lang.IllegalStateException: Bean class name [org.springframework.data.mongodb.repository.support.MongoRepositoryFactoryBean] has not been resolved into an actual Class”,“thrown”:{“commonElementCount”:0,“localizedMessage”:“Error creating bean with name ‘functionCatalog’ defined in class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.function.context.FunctionRegistry]: Factory method ‘functionCatalog’ threw exception; nested exception is java.lang.IllegalStateException: Bean class name [org.springframework.data.mongodb.repository.support.MongoRepositoryFactoryBean] has not been resolved into an actual Class”,“message”:“Error creating bean with name ‘functionCatalog’ defined in class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.function.context.FunctionRegistry]: Factory method ‘functionCatalog’ threw exception; nested exception is java.lang.IllegalStateException: Bean class name 

Checking the dependencies tree i see the following

 org.springframework.cloud:spring-cloud-starter-stream-rabbit  -> 2.1.4.RELEASE

and this brings with the following dependency

org.springframework.cloud:spring-cloud-function-context:2.0.1.RELEASE

**Comment by olegz** [comment]
Can you please provide steps to reproduce it? Also, you're using rather old version of spring-cloud (and all that it brings). Consider upgrading from Greenwich to Hoxton.SR3.

**Comment by joaquindiez** [comment]
I am trying to create a basic project to show you the problem but is not as easy as I expected.

Updgrading to Hoxton.SR3 while using org.springframework.boot:spring-boot-dependencies:2.1.9.RELEASE, gives  a diferent error:



2020-03-29T18:43:45,599|ERROR|org.springframework.boot.SpringApplication|||main|Application run failed| org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bootstrapImportSelectorConfiguration': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/ConfigurationPropertiesBean 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:847) 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:212) 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:117) 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:74) 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76) 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342) 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) 	at ai.clarity.Application.main(Application.java:18) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/ConfigurationPropertiesBean 	at org.springframework.cloud.context.properties.ConfigurationPropertiesBeans.postProcessBeforeInitialization(ConfigurationPropertiesBeans.java:94) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) 	... 34 more Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.properties.ConfigurationPropertiesBean 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) 	... 38 more

**Comment by olegz** [comment]
Hoxton is not compatible with boot 2.1.x. Please use boot 2.2.x

**Comment by joaquindiez** [comment]
I will thanks
