### ISSUE TITLE
Extending AzureSpringBootRequestHandler<String, ?> throws ClassCastException: java.lang.NoClassDefFoundError cannot be cast to java.lang.RuntimeException

### ISSUE THREAD

**Issue by tehyatt** [spring-cloud/spring-cloud-function#523]
**Describe the bug**
Extending the AzureSpringBootRequestHandler with an input type of String throws ClassCastException: java.lang.NoClassDefFoundError cannot be cast to java.lang.RuntimeException when invoking handleRequest("somestring", context).

**Sample**
```java
public class TimerHandler extends AzureSpringBootRequestHandler<String, String> {
    /**
     * This function will be invoked periodically according to the specified schedule.
     */
    @FunctionName("timerTrigger")
    public void run(
        @TimerTrigger(name = "timerInfo", schedule = "0 0-59 * * * *") String timerInfo,
        final ExecutionContext context
    ) {
        context.getLogger().info("Java Timer trigger function executed at: " + LocalDateTime.now());
        context.getLogger().info("Timer info: " + timerInfo);

        handleRequest(timerInfo, context);
    }
}

@SpringBootApplication
public class App 
{
    public static void main( String[] args )
    {
        SpringApplication.run(App.class, args);
    }
    @Bean
    public Function<String, String> timerTrigger() {
        return s -> s + s;
    }
}
```

```
[5/18/2020 6:43:00 PM] Handler processing a request for: timerTrigger
[5/18/2020 6:43:00 PM] 2020-05-18 14:43:00.260  WARN 13072 --- [pool-2-thread-2] c.f.c.c.BeanFactoryAwareFunctionRegistry : !!! Failed to discover function 'function' in function catalog. Function available in catalog are: [timerTrigger, hello, functionRouter]
[5/18/2020 6:43:00 PM] 2020-05-18 14:43:00.260  INFO 13072 --- [pool-2-thread-2] c.f.c.c.BeanFactoryAwareFunctionRegistry : Looking up function 'consumer' with acceptedOutputTypes: []
[5/18/2020 6:43:00 PM] 2020-05-18 14:43:00.260  WARN 13072 --- [pool-2-thread-2] c.f.c.c.BeanFactoryAwareFunctionRegistry : !!! Failed to discover function 'consumer' in function catalog. Function available in catalog are: [timerTrigger, hello, functionRouter]
[5/18/2020 6:43:00 PM] 2020-05-18 14:43:00.261  INFO 13072 --- [pool-2-thread-2] c.f.c.c.BeanFactoryAwareFunctionRegistry : Looking up function 'supplier' with acceptedOutputTypes: []
[5/18/2020 6:43:00 PM] 2020-05-18 14:43:00.261  WARN 13072 --- [pool-2-thread-2] c.f.c.c.BeanFactoryAwareFunctionRegistry : !!! Failed to discover function 'supplier' in function catalog. Function available in catalog are: [timerTrigger, hello, functionRouter]
[5/18/2020 6:43:00 PM] 2020-05-18 14:43:00.261  INFO 13072 --- [pool-2-thread-2] c.f.c.c.BeanFactoryAwareFunctionRegistry : Looking up function 'timerTrigger' with acceptedOutputTypes: []
[5/18/2020 6:43:00 PM] Executed 'Functions.timerTrigger' (Failed, Id=3efc070c-e600-41d0-9f1a-948f7c2bb169)
[5/18/2020 6:43:00 PM] System.Private.CoreLib: Exception while executing function: Functions.timerTrigger. System.Private.CoreLib: Result: Failure
Exception: ClassCastException: java.lang.NoClassDefFoundError cannot be cast to java.lang.RuntimeException
Stack: java.lang.reflect.InvocationTargetException
[5/18/2020 6:43:00 PM]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[5/18/2020 6:43:00 PM]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[5/18/2020 6:43:00 PM]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[5/18/2020 6:43:00 PM]  at java.lang.reflect.Method.invoke(Method.java:498)
[5/18/2020 6:43:00 PM]  at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[5/18/2020 6:43:00 PM]  at com.microsoft.azure.functions.worker.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:54)
[5/18/2020 6:43:00 PM]  at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:53)
[5/18/2020 6:43:00 PM]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[5/18/2020 6:43:00 PM]  at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[5/18/2020 6:43:00 PM]  at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
[5/18/2020 6:43:00 PM]  at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
[5/18/2020 6:43:00 PM]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[5/18/2020 6:43:00 PM]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[5/18/2020 6:43:00 PM]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[5/18/2020 6:43:00 PM]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[5/18/2020 6:43:00 PM]  at java.lang.Thread.run(Thread.java:748)
[5/18/2020 6:43:00 PM] Caused by: java.lang.ClassCastException: java.lang.NoClassDefFoundError cannot be cast to java.lang.RuntimeException
[5/18/2020 6:43:00 PM]  at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:99)
[5/18/2020 6:43:00 PM]  at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:83)
[5/18/2020 6:43:00 PM]  at com.demo.TimerHandler.run(TimerHandler.java:24)
note: line 24 is handleRequest(timerInfo, context);
[5/18/2020 6:43:00 PM]  ... 16 more
[5/18/2020 6:43:00 PM] .

```

Works as long as the input type is not String. (Tried with <Long, String> and <User, Greeting> (from the sample) those both work fine).

**Comment by olegz** [comment]
I am going to close this issue as we have deprecated `AzureSpringBootRequestHandler`
Instead please use [FunctionInvoker](https://docs.spring.io/spring-cloud-function/docs/3.1.2/reference/html/azure.html) as described in the docs.

**Comment by SunilKSingla** [comment]
With Azure blob trigger i am not able to call spring function. But when i changed the trigger to HttpTigger i am able to call spring cloud function.  Getting below issue with Azure BlobTrigger while calling spring cloud function using handleRequest:
java.lang.NullPointerException
[2022-05-15T09:06:39.266Z] 	at org.springframework.cloud.function.adapter.azure.FunctionInvoker.handleRequest(FunctionInvoker.java:129)

[2022-05-15T09:06:39.266Z] java.lang.NullPointerException
[2022-05-15T09:06:39.266Z] 	at org.springframework.cloud.function.adapter.azure.FunctionInvoker.handleRequest(FunctionInvoker.java:129)
[2022-05-15T09:06:39.266Z] 	at com.mgmresorts.betmgmec.nebetmgmec.HelloHandler.execute(HelloHandler.java:27)
[2022-05-15T09:06:39.266Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-05-15T09:06:39.267Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-05-15T09:06:39.267Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-05-15T09:06:39.267Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2022-05-15T09:06:39.267Z] 	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
[2022-05-15T09:06:39.267Z] null
