### ISSUE TITLE
spring-cloud-starter-function-web doesn't work with springCloudVersion of Hoxton.SR4

### ISSUE THREAD

**Issue by bertilmuth** [spring-cloud/spring-cloud-function#529]
I use the following `build.gradle` file:
```
plugins {
  id 'org.springframework.boot' version '2.3.0.RELEASE'
  id 'io.spring.dependency-management' version '1.0.9.RELEASE'
  id 'java'
}

group = 'org.requirementsascode.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
	mavenCentral()
}

ext {
  set('springCloudVersion', "Hoxton.SR4")
}

dependencies {
  implementation 'org.springframework.cloud:spring-cloud-starter-function-web'
  testImplementation('org.springframework.boot:spring-boot-starter-test') {
    exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
  }
}

dependencyManagement {
  imports {
    mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
  }
}
test {
  useJUnitPlatform()
}
```
When I run the application and then issue a POST request as described in the Reference Documentation, Spring shows the following error message:
```
java.lang.ClassNotFoundException: org.json.JSONObject
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.isJson(SimpleFunctionRegistry.java:850) ~[spring-cloud-function-context-3.0.6.RELEASE.jar:3.0.6.RELEASE]
...
```

When I change the version to Hoxton.SR3, everything works fine.

As a side note: I think Spring Cloud Function is a fantastic project. It would greatly appreciate it, and others new to the project might as well, if you could provide working, current build files in the Getting Started section. What do you think?

**Comment by olegz** [comment]
@bertilmuth this is indeed a bug with 3.0.6 release of spring-cloud-function and it has been fixed a while back. We are releasing 3.0.7 of spring-cloud-function today and subsequently Hoxton.SR5 to follow. meanwhile the workaround (for now) is to add this dependency to your pom

```
<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20200518</version>
</dependency>
```
