### ISSUE TITLE
BeanCreationException: Error creating bean with name WebClient$Builder

### ISSUE THREAD

**Issue by Guneetgstar** [spring-cloud/spring-cloud-function#598]
**Describe the bug**

I am using Google Cloud Function to deploy my spring cloud function and as per the function sample [here](https://github.com/spring-cloud/spring-cloud-function/tree/ee0559caac356bcb99bdb6168bcacfae1e00221d/spring-cloud-function-samples/function-sample-gcp-http) which has the following dependency in the `pom.xml`:
https://github.com/spring-cloud/spring-cloud-function/blob/ee0559caac356bcb99bdb6168bcacfae1e00221d/spring-cloud-function-samples/function-sample-gcp-http/pom.xml#L32
And Following another [API reference](https://cloud.spring.io/spring-cloud-static/spring-cloud-function/2.1.1.RELEASE/spring-cloud-function.html#_comparing_functional_with_traditional_bean_definitions), after including the following into my `pom.xml` :
```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-function-webflux</artifactId>
</dependency>
````
which as per the reference, the application should start using server `netty`, I got the following error instead:
```
2020-10-22 20:06:05.074 ERROR 3074 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.reactive.function.client.WebClient$Builder': Unexpected exception during bean creation; nested exception is java.lang.NoClassDefFoundError: org/springframework/http/client/reactive/ClientHttpConnector
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:529) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
        at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.initialize(AbstractSpringFunctionAdapterInitializer.java:117) ~[spring-cloud-function-context-3.0.10.RELEASE.jar:3.0.10.RELEASE]
        at org.springframework.cloud.function.adapter.gcp.FunctionInvoker.init(FunctionInvoker.java:72) ~[spring-cloud-function-adapter-gcp-3.0.10.RELEASE.jar:3.0.10.RELEASE]
        at org.springframework.cloud.function.adapter.gcp.FunctionInvoker.<init>(FunctionInvoker.java:57) ~[spring-cloud-function-adapter-gcp-3.0.10.RELEASE.jar:3.0.10.RELEASE]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]
        at org.springframework.cloud.function.adapter.gcp.GcfJarLauncher.<init>(GcfJarLauncher.java:53) ~[spring-cloud-function-adapter-gcp-3.0.10.RELEASE.jar:3.0.10.RELEASE]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[na:na]
        at com.google.cloud.functions.invoker.NewHttpFunctionExecutor.forClass(NewHttpFunctionExecutor.java:51) ~[na:na]
        at com.google.cloud.functions.invoker.runner.Invoker.servletForDeducedSignatureType(Invoker.java:311) ~[na:na]
        at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:273) ~[na:na]
        at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:135) ~[na:na]
        at com.google.cloud.functions.plugin.RunFunction.execute(RunFunction.java:76) ~[na:na]
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137) ~[maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210) ~[maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156) ~[maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148) ~[maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117) ~[maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81) ~[maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56) ~[maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) ~[maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305) ~[maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192) ~[maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105) ~[maven-core-3.3.9.jar:3.3.9]
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957) ~[maven-embedder-3.3.9.jar:3.3.9]
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289) ~[maven-embedder-3.3.9.jar:3.3.9]
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193) ~[maven-embedder-3.3.9.jar:3.3.9]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282) ~[plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225) ~[plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406) ~[plexus-classworlds-2.5.2.jar:na]
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347) ~[plexus-classworlds-2.5.2.jar:na]
Caused by: java.lang.NoClassDefFoundError: org/springframework/http/client/reactive/ClientHttpConnector
        at org.springframework.web.reactive.function.client.WebClient.builder(WebClient.java:157) ~[spring-webflux-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.cloud.function.web.source.FunctionExporterInitializer.lambda$registerWebClient$0(FunctionExporterInitializer.java:52) ~[spring-cloud-function-web-3.0.10.RELEASE.jar:3.0.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1230) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1172) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        ... 52 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.http.client.reactive.ClientHttpConnector
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
        ... 58 common frames omitted

```
The error goes after excluding the the [test dependancy](https://github.com/spring-cloud/spring-cloud-function/blob/ee0559caac356bcb99bdb6168bcacfae1e00221d/spring-cloud-function-samples/function-sample-gcp-http/pom.xml#L32) I just mentioned above.

**Sample**

Copy [directory](https://github.com/spring-cloud/spring-cloud-function/tree/ee0559caac356bcb99bdb6168bcacfae1e00221d/spring-cloud-function-samples/function-sample-gcp-http) and add 
```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-function-webflux</artifactId>
  </dependency>
```
into the `pom.xml` to see the error.

**Comment by olegz** [comment]
I can't seem to reproduce the error you're describing. I tried to add `spring-cloud-starter-function-webflux` on tope of `spring-web` as well as replace `spring-web` with `spring-cloud-starter-function-webflux` and I get 

```
20:11:48.589 [main] DEBUG org.springframework.web.client.RestTemplate - HTTP POST http://localhost:8080/
20:11:48.595 [main] DEBUG org.springframework.web.client.RestTemplate - Accept=[text/plain, application/json, application/*+json, */*]
20:11:48.597 [main] DEBUG org.springframework.web.client.RestTemplate - Writing [Hello] with org.springframework.http.converter.StringHttpMessageConverter
20:11:48.690 [main] DEBUG org.springframework.web.client.RestTemplate - Response 200 OK
20:11:48.693 [main] DEBUG org.springframework.web.client.RestTemplate - Reading to [java.lang.String] as "application/octet-stream"
```

Could you please check again and provide a more details instructions on how to reproduce?

**Comment by Guneetgstar** [comment]
@olegz Please test [this](https://github.com/Guneetgstar/gcp-error-temp.git) repo.

**Comment by olegz** [comment]
I just did and i see no issues 

```
2020-11-10 07:57:34.940  INFO 3570 --- [           main] in.cernyshop.CernyshopGcpApplication     : Started CernyshopGcpApplication in 0.433 seconds (JVM running for 0.774)
```

**Comment by Guneetgstar** [comment]
I guess you didn't see [this](https://github.com/Guneetgstar/gcp-error-temp/blob/9dc4df198c66a802028897bcecd76624c88865dd/pom.xml#L49). Sorry my bad I should have done that.

**Comment by olegz** [comment]
Yep 
```
. . .
Caused by: java.lang.ClassNotFoundException: org.springframework.http.client.reactive.ClientHttpConnector
```
Sorry about that. Will look at it shortly

**Comment by olegz** [comment]
Ok, I am not sure exactly what you are trying to accomplish here, but here is the answer to your immediate question:
The `spring-web` module is a transitive dependency of `spring-cloud-starter-function-webflux`. Which is why everything works as expected. But then you bring `spring-web` explicitly and lower it's scope to `test` thus making it invisible outside of test environment.

But the bottom line is you don't need to declare it explicitly since it's already part of your classpath. So, remove it and all should be fine.

**Comment by Guneetgstar** [comment]
Thanks for the clarification @olegz . What I was trying to do is to start my spring app using `netty` server for `webflux` using this [sample](https://github.com/spring-cloud/spring-cloud-function/tree/ee0559caac356bcb99bdb6168bcacfae1e00221d/spring-cloud-function-samples/function-sample-gcp-http) so error came when I added `spring-cloud-starter-function-webflux` to the pom.xml not the `spring-web` that you mentioned. It was already there. Now I'll remove it to make it work.
