### ISSUE TITLE
Provide Simple Example to make AWS Lambda work!!!

### ISSUE THREAD

**Issue by kitkars** [spring-cloud/spring-cloud-function#619]
Hey Guys

Look at the maven dependency. I just copied from aws - lambda example.

https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-aws

spring-cloud-function.version changed to 3.0.12.RELEASE as it is said to be stable.

What do I need to make this simple example work?

```
<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<wrapper.version>1.0.17.RELEASE</wrapper.version>
		<aws-lambda-events.version>2.0.2</aws-lambda-events.version>
		<spring-cloud-function.version>3.0.12.RELEASE</spring-cloud-function.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-function-adapter-aws</artifactId>
		</dependency>
<!--
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-function-context</artifactId>
		</dependency>
-->

		<!-- 		<dependency> -->
		<!-- 			<groupId>org.springframework.cloud</groupId> -->
		<!-- 			<artifactId>spring-cloud-starter-function-webflux</artifactId> -->
		<!--  			<scope>provided</scope> -->
		<!-- 		</dependency> -->
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-events</artifactId>
			<version>${aws-lambda-events.version}</version>
			<!-- 			<scope>provided</scope> -->
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-core</artifactId>
			<version>1.1.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-function-dependencies</artifactId>
				<version>${spring-cloud-function.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>org.springframework.boot.experimental</groupId>
						<artifactId>spring-boot-thin-layout</artifactId>
						<version>${wrapper.version}</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.2.4</version>
				<configuration>
					<createDependencyReducedPom>false</createDependencyReducedPom>
					<shadedArtifactAttached>true</shadedArtifactAttached>
					<shadedClassifierName>aws</shadedClassifierName>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
```
**App:**

```
@SpringBootApplication
public class AwsLambdaApplication implements ApplicationContextInitializer<GenericApplicationContext> {

		public static void main(String[] args) throws Exception {
			FunctionalSpringApplication.run(AwsLambdaApplication.class, args);
		}

		public Function<String, String > function() {
		return String::toUpperCase;
		}

		@Override
		public void initialize(GenericApplicationContext context) {
			context.registerBean("function", FunctionRegistration.class,
			() -> new FunctionRegistration<Function<String, String>>(function())
							.type(FunctionType.from(String.class).to(String.class).getType()));
		}

}
```
**Envrioment variable:**

FUNCTION_NAME=function

**application.properties:**

spring.cloud.function.web.export.enabled=true

**Handler:**

org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest

**Actual Result:**
```
Failed to lookup function null: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: Failed to lookup function null
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:133)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:77)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

END RequestId: e61d4b3a-8698-4c69-bf42-1756ad4f30fc
```

**Comment by olegz** [comment]
I am not sure what exactly you are doing but i just tried several times and all is working properly

1. Build the sample project (you can change version of s-c-function to 3.0.12. I tested it with both ) 
2. Go to AWS Dashboard and create Lambda following [these instructions](https://docs.spring.io/spring-cloud-function/docs/3.0.10.RELEASE/reference/html/aws.html#_getting_started)
3. Upload your JAR file - `function-sample-aws-2.0.0.RELEASE-aws.jar`
4. Specify the handler as `org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest`
5 Create test event (in my case `"hello world"`) and execute test

```
The area below shows the result returned by your function execution. Learn more about returning results from your function.
"3.0.12 - HELLO WORLD"
Summary
Code SHA-256
9p5c7pRhkNlKaZAr3987HCjuoDBvd4cYKYnCj11pyAM=
Request ID
fac061d8-4deb-4f46-892e-34bdb4a0aac1
Duration
277.51 ms
Billed duration
278 ms
Resources configured
512 MB
Max memory used
135 MB Init Duration: 3416.48 ms
Log output
The section below shows the logging calls in your code. These correspond to a single row within the CloudWatch log group corresponding to this Lambda function. Click here to view the CloudWatch log group.
START RequestId: fac061d8-4deb-4f46-892e-34bdb4a0aac1 Version: $LATEST
2020-12-10 07:38:52.336  INFO 1 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Incoming JSON for ApiGateway Event: "hello world"
END RequestId: fac061d8-4deb-4f46-892e-34bdb4a0aac1
REPORT RequestId: fac061d8-4deb-4f46-892e-34bdb4a0aac1	Duration: 277.51 ms	Billed Duration: 278 ms	Memory Size: 512 MB	Max Memory Used: 135 MB	Init Duration: 3416.48 ms	
```

P.S. I modified function to explicitly include version hence  `"3.0.12 - HELLO WORLD"`

**Comment by kitkars** [comment]
In your code, try like this. Have 2 beans to replicate.
```
	@Bean
	public Function<String, String > uppercase() {
		return String::toUpperCase;
	}

	@Bean
	public Supplier<String > get() {
		return () -> "hi - ";
	}
```
Lambda console - add this enviroment variable.
```
FUNCTION_NAME=uppercase
```
