### ISSUE TITLE
FunctionCatalog Bean Instantiation Failure 

### ISSUE THREAD

**Issue by akposton** [spring-cloud/spring-cloud-function#631]
Using the following dependencies, I'm getting this error.  This occurs simply in importing `implementation 'org.springframework.cloud:spring-cloud-starter-stream-rabbit'`  I'm having a hell of a time finding out where the dependencies are getting crossed and wonky.

I did debug through startup and notice the failure during the wrapping of registrations to targets.
Possibly important to note this service has the application class in Java source and my rabbit classes are Kotlin source.
This failure does happen on bootRun of just the import prior to the addition of my rabbit binding classes and configs.

Any ideas?

```
org.springframework.boot:spring-boot-dependencies -> 2.1.18.RELEASE
org.springframework.cloud:spring-cloud-dependencies -> Greenwich.SR6
+--- org.springframework.cloud:spring-cloud-starter-netflix-hystrix:2.1.5.RELEASE (c)
+--- org.springframework.cloud:spring-cloud-starter-stream-rabbit:2.1.4.RELEASE (c)
+--- org.springframework.cloud:spring-cloud-starter:2.1.6.RELEASE (c)
+--- org.springframework.cloud:spring-cloud-stream-binder-rabbit:2.1.4.RELEASE (c)
+--- org.springframework.cloud:spring-cloud-function-context:2.0.2.RELEASE (c)
\--- org.springframework.cloud:spring-cloud-function-core:2.0.2.RELEASE (c)
```

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionCatalog' defined in class path resource [org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.function.context.FunctionRegistry]: Factory method 'functionCatalog' threw exception; nested exception is java.lang.IllegalStateException: No bean class specified on bean definition
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:645)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:625)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
        at my.package.MyApplication.main(MyApplication.java:68)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.function.context.FunctionRegistry]: Factory method 'functionCatalog' threw exception; nested exception is java.lang.IllegalStateException: No bean class specified on bean definition
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:640)
        ... 19 common frames omitted
Caused by: java.lang.IllegalStateException: No bean class specified on bean definition
        at org.springframework.beans.factory.support.AbstractBeanDefinition.getBeanClass(AbstractBeanDefinition.java:423)
        at org.springframework.cloud.function.context.config.FunctionContextUtils.findType(FunctionContextUtils.java:70)
        at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$ContextFunctionRegistry.findType(ContextFunctionCatalogAutoConfiguration.java:582)
        at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$ContextFunctionRegistry.wrap(ContextFunctionCatalogAutoConfiguration.java:455)
        at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$ContextFunctionRegistry.lambda$merge$6(ContextFunctionCatalogAutoConfiguration.java:433)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$ContextFunctionRegistry.merge(ContextFunctionCatalogAutoConfiguration.java:433)
        at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration.functionCatalog(ContextFunctionCatalogAutoConfiguration.java:110)
        at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$$EnhancerBySpringCGLIB$$800b5143.CGLIB$functionCatalog$0(<generated>)
        at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$$EnhancerBySpringCGLIB$$800b5143$$FastClassBySpringCGLIB$$27ff84c0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
        at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$$EnhancerBySpringCGLIB$$800b5143.functionCatalog(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 20 common frames omitted

```

**Comment by olegz** [comment]
These are very old version of both function and stream that you are using and I believe they are EOL or close to it. 
For s-c-function we're on 3.0.12.RELEASE as well as 3.1.0.RELEASE - https://spring.io/projects/spring-cloud-function#learn

Similar for s-c-stream - https://spring.io/projects/spring-cloud-stream#learn

**Comment by akposton** [comment]
> These are very old version of both function and stream that you are using and I believe they are EOL or close to it.
> For s-c-function we're on 3.0.12.RELEASE as well as 3.1.0.RELEASE - https://spring.io/projects/spring-cloud-function#learn
> 
> Similar for s-c-stream - https://spring.io/projects/spring-cloud-stream#learn

I tried with newer versions of just `fucntion-core`, `spring-cloud-dependencies`, and `starter-stream-rabbit` but I keep running into this `functionCatalog` instantiation issue.  

I haven't had this happen in any other repositories when pulling this in... could it possibly be conflicting with the dependencies of `hystrix`?  That's the only thing that really stands out to me.  This repo also does have `spring-data-mongodb:2.2.2.RELEASE` and `spring-data-redis:2.2.2.RELEASE`, but I didn't think those would cause my issue.

**Comment by olegz** [comment]
I don't know, it's hard to say without reproducing it. So please consider posting a small project on github which we can use to reproduce and triage the issue

**Comment by akposton** [comment]
Update: issue was the version of mongodb.... It's an enterprise service, so some things just can't be helped 🤦‍♀️ 

Thank you for looking into it!
