### ISSUE TITLE
NullPointerException on SimpleFunctionRegistry::isExtractPayload  when empty list is returned

### ISSUE THREAD

**Issue by pedrorlmarques** [spring-cloud/spring-cloud-function#635]
**Bug**

I'm using **spring-cloud-function-web** and I'm defining a function bean that returns an empty list:

`
    @Bean
    public Function<String, List<String>> emptyStringList() {
        return input -> List.of();
    }
`

When doing calling this function an error is returned.

Rest Call : 
`curl -H "Content-Type: text/plain" localhost:8080/emptyStringList -d test`

**Output** 
`
{
   "message" : "",
   "error" : "Internal Server Error",
   "timestamp" : "2021-01-22T13:53:09.987+00:00",
   "path" : "/emptyStringList",
   "status" : 500
}
`

**StackTrace**

`
java.lang.NullPointerException: null
	at java.base/java.lang.Class.isAssignableFrom(Native Method) ~[na:na]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.isExtractPayload(SimpleFunctionRegistry.java:898) ~[spring-cloud-function-context-3.1.0.jar:3.1.0]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertOutputIfNecessary(SimpleFunctionRegistry.java:915) ~[spring-cloud-function-context-3.1.0.jar:3.1.0]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.lambda$convertOutputPublisherIfNecessary$26(SimpleFunctionRegistry.java:1171) ~[spring-cloud-function-context-3.1.0.jar:3.1.0]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) ~[reactor-co
`

Looking at the implementation, since CollectionUtils::findCommonElementType is returning null when the 
Message.class.isAssignableFrom() is called a null pointer is thrown .

**SimpleFunctionRegistry::isExtractPayload**

`if (payload instanceof Collection&& 
Message.class.isAssignableFrom(CollectionUtils.findCommonElementType((Collection<?>) payload))) {
	return true;
}
`

CollectionUtils::findCommonElementType

`
if (isEmpty(collection)) {
			return null;
}
`

**Sample**
https://github.com/pedrorlmarques/simplefunctionregistry-issue-null-pointer

**Comment by olegz** [comment]
Thanks for reporting, seems like an easy fix.
