### ISSUE TITLE
Supplier doen't work in ApiGateway and AWS Lambda combination

### ISSUE THREAD

**Issue by masatotoro** [spring-cloud/spring-cloud-function#639]
I prepare following supplier class.

```java
@Component
public class ClassSupplier implements Supplier<Message<Output>> {
	@Override
	public Message<Output> get() {
		return new GenericMessage<>(Output.builder().a("alice").build());
	}
}

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
class Output {
	private String a;
}
```

When I execute this function, I get a NullPointerException, so I investigated the cause.

https://github.com/spring-cloud/spring-cloud-function/blob/315ed4612dc87d2653d83f735fdc1acbfd481604/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/AWSLambdaUtils.java#L204

```
	private static boolean isTypeAnApiGatewayRequest(Type type) {
		return isAPIGatewayProxyRequestEventPresent()
				? type.getTypeName().endsWith(APIGatewayProxyRequestEvent.class.getSimpleName())
				: false;
	}
```

In case of  Supplier, the argument "type" of this method seems to be null. So, I don't think type.getTypeName () is appropriate.

**Comment by olegz** [comment]
I see your point. Will address shortly

**Comment by masatotoro** [comment]
Thank you for your prompt response. The log when an error occurs is shown below.

```
2021-02-03 16:21:35.203  INFO 13 --- [           main] lambdainternal.LambdaRTEntry             : No active profile set, falling back to default profiles: default
2021-02-03 16:21:36.115  INFO 13 --- [           main] lambdainternal.LambdaRTEntry             : Started LambdaRTEntry in 1.322 seconds (JVM running for 1.595)
2021-02-03 16:21:36.117  INFO 13 --- [           main] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Starting spring-cloud-function CustomRuntimeEventLoop
2021-02-03 16:21:36.124  INFO 13 --- [           main] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Entering event loop
2021-02-03 16:21:36.160  INFO 13 --- [           main] o.s.c.f.a.aws.CustomRuntimeEventLoop     : Located function classSupplier
2021-02-03 16:21:36.166  INFO 13 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming JSON Event: {"body": null, "headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", "Accept-Encoding": "gzip, deflate", "Accept-Language": "ja,en-US;q=0.7,en;q=0.3", "Connection": "keep-alive", "Host": "127.0.0.1:3000", "Upgrade-Insecure-Requests": "1", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0", "X-Forwarded-Port": "3000", "X-Forwarded-Proto": "http"}, "httpMethod": "GET", "isBase64Encoded": false, "multiValueHeaders": {"Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"], "Accept-Encoding": ["gzip, deflate"], "Accept-Language": ["ja,en-US;q=0.7,en;q=0.3"], "Connection": ["keep-alive"], "Host": ["127.0.0.1:3000"], "Upgrade-Insecure-Requests": ["1"], "User-Agent": ["Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0"], "X-Forwarded-Port": ["3000"], "X-Forwarded-Proto": ["http"]}, "multiValueQueryStringParameters": null, "path": "/supplier", "pathParameters": null, "queryStringParameters": null, "requestContext": {"accountId": "123456789012", "apiId": "1234567890", "domainName": "127.0.0.1:3000", "extendedRequestId": null, "httpMethod": "GET", "identity": {"accountId": null, "apiKey": null, "caller": null, "cognitoAuthenticationProvider": null, "cognitoAuthenticationType": null, "cognitoIdentityPoolId": null, "sourceIp": "127.0.0.1", "user": null, "userAgent": "Custom User Agent String", "userArn": null}, "path": "/supplier", "protocol": "HTTP/1.1", "requestId": "cf7ae9c0-5b82-43ca-b1e2-f52f9bd143cc", "requestTime": "03/Feb/2021:16:21:11 +0000", "requestTimeEpoch": 1612369271, "resourceId": "123456", "resourcePath": "/supplier", "stage": "dev"}, "resource": "/supplier", "stageVariables": null, "version": "1.0"}
2021-02-03 16:21:36.199  INFO 13 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming request is API Gateway
2021-02-03 16:21:36.199  INFO 13 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : type: null  // ★ <- I add debug log
2021-02-03 16:21:36.203  INFO 13 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-02-03 16:21:36.223 ERROR 13 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [task/:na]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) [task/:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [task/:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [task/:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [task/:na]
        at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:85) [task/:na]
        at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:67) [task/:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_265]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_265]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_265]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_265]
        at lambdainternal.EventHandlerLoader.newInstance(EventHandlerLoader.java:390) [LambdaSandboxJava-1.0.jar:na]
        at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.fromMethod(EventHandlerLoader.java:314) [LambdaSandboxJava-1.0.jar:na]
        at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.makeRequestHandler(EventHandlerLoader.java:327) [LambdaSandboxJava-1.0.jar:na]
        at lambdainternal.EventHandlerLoader.getThreeLengthHandler(EventHandlerLoader.java:663) [LambdaSandboxJava-1.0.jar:na]
        at lambdainternal.EventHandlerLoader.getHandlerFromOverload(EventHandlerLoader.java:682) [LambdaSandboxJava-1.0.jar:na]
        at lambdainternal.EventHandlerLoader.loadEventPojoHandler(EventHandlerLoader.java:794) [LambdaSandboxJava-1.0.jar:na]
        at lambdainternal.EventHandlerLoader.loadEventHandler(EventHandlerLoader.java:596) [LambdaSandboxJava-1.0.jar:na]
        at lambdainternal.AWSLambda.findUserMethods(AWSLambda.java:125) [LambdaSandboxJava-1.0.jar:na]
        at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:305) [LambdaSandboxJava-1.0.jar:na]
        at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63) [LambdaSandboxJava-1.0.jar:na]
        at java.lang.Class.forName0(Native Method) [na:1.8.0_265]
        at java.lang.Class.forName(Class.java:348) [na:1.8.0_265]
        at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150) [LambdaJavaRTEntry-1.0.jar:na]
Caused by: java.lang.NullPointerException: null
        at org.springframework.cloud.function.adapter.aws.AWSLambdaUtils.isTypeAnApiGatewayRequest(AWSLambdaUtils.java:207) ~[task/:na]
        at org.springframework.cloud.function.adapter.aws.AWSLambdaUtils.generateMessage(AWSLambdaUtils.java:103) ~[task/:na]
        at org.springframework.cloud.function.adapter.aws.AWSLambdaUtils.generateMessage(AWSLambdaUtils.java:66) ~[task/:na]
        at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:98) ~[task/:na]
        at org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.lambda$initialize$0(CustomRuntimeInitializer.java:49) ~[task/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [task/:na]
        ... 23 common frames omitted

Failed to execute CommandLineRunner: java.lang.IllegalStateException
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
        at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:85)
        at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:67)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Caused by: java.lang.NullPointerException
        at org.springframework.cloud.function.adapter.aws.AWSLambdaUtils.isTypeAnApiGatewayRequest(AWSLambdaUtils.java:207)
        at org.springframework.cloud.function.adapter.aws.AWSLambdaUtils.generateMessage(AWSLambdaUtils.java:103)
        at org.springframework.cloud.function.adapter.aws.AWSLambdaUtils.generateMessage(AWSLambdaUtils.java:66)
        at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:98)
        at org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.lambda$initialize$0(CustomRuntimeInitializer.java:49)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
        ... 10 more

[ERROR] [1612369296228] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403.
Exception in thread "main" java.lang.Error: java.lang.RuntimeException: Runtime unable to report state
        at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:65)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150)
Caused by: java.lang.RuntimeException: Runtime unable to report state
        at lambdainternal.LambdaRuntime.reportDone(Native Method)
        at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:308)
        at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)

```
