### ISSUE TITLE
NPE during non-Message conversion when input is a valid JSON string representing Map

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#640]
@marcingrzejszczak  FYI

java.lang.IllegalArgumentException: Payload must not be null
	at org.springframework.util.Assert.notNull(Assert.java:201) ~[spring-core-5.3.3.jar!/:5.3.3]
	at org.springframework.messaging.support.MessageBuilder.<init>(MessageBuilder.java:57) ~[spring-messaging-5.3.3.jar!/:5.3.3]
	at org.springframework.messaging.support.MessageBuilder.withPayload(MessageBuilder.java:189) ~[spring-messaging-5.3.3.jar!/:5.3.3]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertInputIfNecessary(SimpleFunctionRegistry.java:885) ~[spring-cloud-function-context-3.1.1.jar!/:3.1.1]
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:579) ~[spring-cloud-function-context-3.1.1.jar!/:3.1.1]
	at

**Comment by olegz** [comment]
Basically, when input is not a Message we're attempting to convert using ConversionService and provided type. However if type is something like `?` or `Object.class` there is really nothing to convert it to, so we were returning null when instead we should have just allow input to proceed as is at which point the expectation would be that the user will receive raw input and can do with it whatever.
