### ISSUE TITLE
KafkaNull tombstone support broken for multi input functions

### ISSUE THREAD

**Issue by chringwer** [spring-cloud/spring-cloud-function#661]
**Describe the issue**
If a function consumes multiple input streams, the framework fails to handle `KafkaNull` values properly. The following null pointer expection will occur.

```
2021-01-15 19:52:56.266 ERROR 82040 --- [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : Failed to convert input

java.lang.NullPointerException: The mapper returned a null value.
	at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.FluxMapFuseable] :
	reactor.core.publisher.Flux.map
	org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertInputPublisherIfNecessary(SimpleFunctionRegistry.java:1159)
Error has been observed at the following site(s):
	|_ Flux.map ⇢ at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.convertInputPublisherIfNecessary(SimpleFunctionRegistry.java:1159)
Stack trace:
		at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[na:na]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113) ~[reactor-core-3.4.2.jar:3.4.2]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[reactor-core-3.4.2.jar:3.4.2]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:199) ~[reactor-core-3.4.2.jar:3.4.2]
		at reactor.core.publisher.UnicastManySinkNoBackpressure.tryEmitNext(UnicastManySinkNoBackpressure.java:119) ~[reactor-core-3.4.2.jar:3.4.2]
		at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:97) ~[reactor-core-3.4.2.jar:3.4.2]
		at org.springframework.integration.util.IntegrationReactiveUtils.lambda$null$8(IntegrationReactiveUtils.java:141) ~[spring-integration-core-5.4.3.jar:5.4.3]

```

**To Reproduce**
Here is a little sample project with a repro case also showing the expected behaviour with single input functions.
https://github.com/chringwer/kafka-null-bug-repro

**Version of the framework**
Spring Cloud Stream 3.1.0 / Spring Cloud 2020.0.0

**Comment by olegz** [comment]
After discussing it with Soby and reproducing it wit the demo provided by the reporter we realized the actual issue is in s-c-function, hence the transfer of the issue.

**Comment by olegz** [comment]
@chringwer so the issue was fixed and back-ported. We have a bit of an issue with snapshot publishing but if you pull the latest s-c-function and do a quick `./mvnw clean install -DskipTests` and the same for s-c-stream, you should be able to test it out. There is a fixed test in s-c-stream and i also validated it with the demo provided by you.
