### ISSUE TITLE
Kotlin function fails at run time with java.lang.IllegalArgumentException: Type must be one of Supplier, Function or Consumer

### ISSUE THREAD

**Issue by frayneposset** [spring-cloud/spring-cloud-function#666]
**Describe the bug**

When curling a funtion exposed as an endpoint it fails with a 500. The logs show:

`java.lang.IllegalArgumentException: Type must be one of Supplier, Function or Consumer
        at org.springframework.util.Assert.isTrue(Assert.java:121) ~[spring-core-5.3.4.jar:5.3.4]
        at org.springframework.cloud.function.context.catalog.FunctionTypeUtils.discoverFunctionTypeFromClass(FunctionTypeUtils.java:149) ~[spring-cloud-function-context-3.1.1.jar:3.1.1]
        at org.springframework.cloud.function.context.catalog.FunctionTypeUtils.discoverFunctionType(FunctionTypeUtils.java:257) ~[spring-cloud-function-context-3.1.1.jar:3.1.1]
        at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.lookup(BeanFactoryAwareFunctionRegistry.java:139) ~[spring-cloud-function-context-3.1.1.jar:3.1.1]
        at org.springframework.cloud.function.context.FunctionCatalog.lookup(FunctionCatalog.java:87) ~[spring-cloud-function-context-3.1.1.jar:3.1.1]
        at org.springframework.cloud.function.web.util.FunctionWebUtils.doFindFunction(FunctionWebUtils.java:73) ~[spring-cloud-function-web-3.1.1.jar:3.1.1]
        at org.springframework.cloud.function.web.util.FunctionWebUtils.findFunction(FunctionWebUtils.java:49) ~[spring-cloud-function-web-3.1.1.jar:3.1.1]
`

**Sample**
Write a simple Spring Boot Kotlin application with a simple function exposed as a bean.

Start the application 

`./gradlew build bootRun`

Call the endpoint to run the function via curl

`curl localhost:8080/toUpperCase/f`

Kotlin code:

```
package com.example.functionnative

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.context.annotation.Bean

@SpringBootApplication
class FunctioningApplication {
	@Bean
	fun toUpperCase(): (String) -> String = { it.toUpperCase() }
}


fun main(args: Array<String>) {
	runApplication<FunctioningApplication>(*args)
}
```
build.gradle.kts :

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.springframework.boot.gradle.tasks.bundling.BootBuildImage

plugins {

	id("org.springframework.boot") version "2.4.3"
	id("io.spring.dependency-management") version "1.0.11.RELEASE"
	kotlin("jvm") version "1.4.30"
	kotlin("plugin.spring") version "1.4.30"
	id("org.springframework.experimental.aot") version "0.9.0"
}


group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
	maven { url = uri("https://repo.spring.io/release") }
	mavenCentral()
}

extra["springCloudVersion"] = "2020.0.1"

dependencies {
	implementation("org.springframework.boot:spring-boot-starter")
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	listOf("context","kotlin","web").forEach {
		implementation("org.springframework.cloud:spring-cloud-function-$it")
	}
	testImplementation("org.springframework.boot:spring-boot-starter-test")
}

dependencyManagement {
	imports {
		mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
	}
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "11"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}

tasks.withType<BootBuildImage> {
	builder = "paketobuildpacks/builder:tiny"
	environment = mapOf("BP_NATIVE_IMAGE" to "true")
}

```

**Comment by olegz** [comment]
Please upgrade to the latest snapshot as this has been addressed already

**Comment by frayneposset** [comment]
Upgrading to 2020.0.2-SNAPSHOT fixes it.

**Comment by olegz** [comment]
The release is tomorrow
