### ISSUE TITLE
NPE when GET is executed and no path argument provided

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-function#668]
In `FunctionWebUtils.doFindFunction` we have the following code
```
if (value != null) {
	attributes.put(WebRequestConstants.ARGUMENT, value);
}
```
and then in `RequestProcessor.invokeFunction()`
```
Flux<?> input = Flux.from(wrapper.argument);
```
which results in NPE if no argument is provided in the path

Here is the relevant stack trace 
```
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ HTTP GET "/" [ExceptionHandlingWebHandler]
Stack trace:
		at java.base/java.util.Objects.requireNonNull(Objects.java:221) ~[na:na]
		at reactor.core.publisher.FluxSource.<init>(FluxSource.java:47) ~[reactor-core-3.4.3.jar!/:3.4.3]
		at reactor.core.publisher.Flux.wrap(Flux.java:10076) ~[reactor-core-3.4.3.jar!/:3.4.3]
		at reactor.core.publisher.Flux.from(Flux.java:1088) ~[reactor-core-3.4.3.jar!/:3.4.3]
		at org.springframework.cloud.function.web.RequestProcessor.invokeFunction(RequestProcessor.java:280) ~[spring-cloud-function-web-3.1.2.jar!/:3.1.2]
		at org.springframework.cloud.function.web.RequestProcessor.get(RequestProcessor.java:74) ~[spring-cloud-function-web-3.1.2.jar!/:3.1.2]
		at org.springframework.cloud.function.web.flux.FunctionController.get(FunctionController.java:101) ~[spring-cloud-function-web-3.1.2.jar!/:3.1.2]
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
		at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
. . .
```

**Comment by olegz** [comment]
While the above fix takes care if the NPE, still need to investigate why are we even allowing that

**Comment by olegz** [comment]
It appears that there is some ping-type request coming in and it is outside of scope of s-c-function, so the null check from previous commit should suffice for now. We can revisit it once we refactor it
