### ISSUE TITLE
Spring Boot Azure Functions Project not working with Kotlin

### ISSUE THREAD

**Issue by MBurchard** [spring-cloud/spring-cloud-function#674]
**Describe the bug**
I made a very simple Java Project. This works well when deployed to Azure Cloud, but as soon as it is prepared for Kotlin, it stops working.

```
2021-03-18T14:48:02.582 [Information] .   ____          _            __ _ _
2021-03-18T14:48:02.582 [Information] /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
2021-03-18T14:48:02.582 [Information] ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2021-03-18T14:48:02.582 [Information] \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
2021-03-18T14:48:02.583 [Information] '  |____| .__|_| |_|_| |_\__, | / / / /
2021-03-18T14:48:02.583 [Information] =========|_|==============|___/=/_/_/_/
2021-03-18T14:48:02.585 [Information] :: Spring Boot ::                (v2.4.4)
2021-03-18T14:48:02.686 [Information] 2021-03-18 14:48:02.648  INFO 7412 --- [pool-2-thread-2] o.s.boot.SpringApplication               : Starting application using Java 11.0.7 on dw0-hr0-1876-10 with PID 7412 (C:\home\site\wwwroot\lib\spring-cloud-function-web-3.1.2.jar started by DW0-HR0-1876-10$ in C:\home\site\wwwroot)
2021-03-18T14:48:02.717 [Information] 2021-03-18 14:48:02.664  INFO 7412 --- [pool-2-thread-2] o.s.boot.SpringApplication               : The following profiles are active: test
2021-03-18T14:48:03.004 [Information] 2021-03-18 14:48:02.992  WARN 7412 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2021-03-18T14:48:03.989 [Information] 2021-03-18 14:48:03.976  INFO 7412 --- [pool-2-thread-2] o.s.boot.SpringApplication               : Started application in 2.214 seconds (JVM running for 177.846)
2021-03-18T14:48:04.026 [Information] 2021-03-18 14:48:04.008 DEBUG 7412 --- [pool-2-thread-2] c.u.c.w.UMMServiceBusRegistrationHandler : run function registerToUMMServiceBus with body
2021-03-18T14:48:04.045 [Information] 2021-03-18 14:48:04.039 ERROR 7412 --- [pool-2-thread-2] c.u.c.w.UMMServiceBusRegistrationHandler :
2021-03-18T14:48:04.046 [Information] java.lang.NullPointerException: null
2021-03-18T14:48:04.046 [Information] at org.springframework.cloud.function.adapter.azure.FunctionInvoker.handleRequest(FunctionInvoker.java:124) ~[spring-cloud-function-adapter-azure-3.1.2.jar:3.1.2]
2021-03-18T14:48:04.046 [Information] at com.uniper.comstar.webapi.UMMServiceBusRegistrationHandler.execute(UMMServiceBusRegistrationHandler.kt:25) ~[comstar-azure-functions-0.0.1-SNAPSHOT.jar:na]
```

It is unable to find the Bean with the Function that has to be invoked.

**Sample**
All Details are also described here: https://stackoverflow.com/questions/66693908/spring-boot-azure-functions-project-not-working-with-kotlin

```java
package com.uniper.comstar.webapi;

import com.microsoft.azure.functions.*;
import com.microsoft.azure.functions.annotation.AuthorizationLevel;
import com.microsoft.azure.functions.annotation.FunctionName;
import com.microsoft.azure.functions.annotation.HttpTrigger;
import org.slf4j.Logger;
import org.springframework.cloud.function.adapter.azure.FunctionInvoker;

import java.util.Optional;

import static org.slf4j.LoggerFactory.getLogger;

public class UMMServiceBusRegistrationHandler extends FunctionInvoker<String, String> {
  private static final Logger LOG = getLogger(UMMServiceBusRegistrationHandler.class);
  public static final String UMMServiceBusRegistrationFunctionName = "registerToUMMServiceBus";

  @FunctionName(UMMServiceBusRegistrationFunctionName)
  public HttpResponseMessage execute(
      @HttpTrigger(name = "request", methods = {HttpMethod.GET, HttpMethod.POST}, authLevel = AuthorizationLevel.ANONYMOUS) final HttpRequestMessage<Optional<String>> request,
      final ExecutionContext context) {
    try {
      final var body = request.getBody().orElse("");
      LOG.debug("run function {} with body {}", context.getFunctionName(), body);
      return request.createResponseBuilder(HttpStatus.OK)
          .body(handleRequest(body, context))
          .header("Content-Type", "application/json")
          .build();
    } catch (final Throwable th) {
      LOG.error("", th);
    }
    return request.createResponseBuilder(HttpStatus.BAD_REQUEST).build();
  }
}
```
```java
package com.uniper.comstar;

import org.slf4j.Logger;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.function.Function;

import static com.uniper.comstar.webapi.UMMServiceBusRegistrationHandler.UMMServiceBusRegistrationFunctionName;
import static org.slf4j.LoggerFactory.getLogger;

@SpringBootApplication
public class ComSTARAzureFunctionsApplication {
  private static final Logger LOG = getLogger(ComSTARAzureFunctionsApplication.class);

  public static void main(final String[] args) {
    SpringApplication.run(ComSTARAzureFunctionsApplication.class, args);
  }

  @Bean
  public Function<String, String> test2() {
    return str -> {
      LOG.debug("Got {}", str);
      return "This is another test";
    };
  }

  @Bean(UMMServiceBusRegistrationFunctionName)
  public Function<String, String> test() {
    return str -> {
      LOG.debug("Got {}", str);
      return "This is a test";
    };
  }
}
```
Plain Java Code, as one can see.
It works well with this build.gradle:
```groovy
plugins {
  id 'org.springframework.boot' version "${springBootVersion}"
  id 'io.spring.dependency-management' version '1.0.11.RELEASE'
  id 'com.microsoft.azure.azurefunctions' version "${azureFunctionsPluginVersion}"
  id 'java-library'
  id 'idea'
}

def javaVersion = JavaVersion.VERSION_11

group = 'com.uniper'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = javaVersion
targetCompatibility = javaVersion

configurations {
  compileOnly {
    extendsFrom annotationProcessor
  }
}

repositories {
  mavenCentral()
}

dependencies {
  annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

  implementation 'com.google.code.findbugs:jsr305:3.0.2',
      "org.springframework.cloud:spring-cloud-starter-function-web:${springCloudVersion}",
      "org.springframework.cloud:spring-cloud-function-adapter-azure:${springCloudVersion}",
      "com.microsoft.azure.functions:azure-functions-java-library:${azureFunctionsVersion}"

  testImplementation('org.springframework.boot:spring-boot-starter-test') {
    exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
  }
}

idea {
  project {
    languageLevel = javaVersion.toString()
  }
  module {
    downloadJavadoc = true
    downloadSources = true
  }
}

azurefunctions {
  resourceGroup = 'removed'
  appName = 'removed'
}

jar {
  enabled = true
  manifest {
    attributes 'Main-Class': 'com.uniper.comstar.ComSTARAzureFunctionsApplication'
  }
}

test {
  useJUnitPlatform()
}

wrapper {
  description "Regenerates the Gradle Wrapper files"
  gradleVersion = '6.8.3'
  distributionType = Wrapper.DistributionType.ALL
}
```
The versions are defined in the gradle.properties
```properties
org.gradle.parallel=true

# Spring Boot Versions
springBootVersion=2.4.4
springCloudVersion=3.1.2

#Other Versions
azureFunctionsPluginVersion=1.5.1
azureFunctionsVersion=1.4.2
```
Until here everything works fine.
But when the build.gradle is changed to be able to have Kotlin Code, it stops working.

Add this line to gradle.properties `kotlinVersion=1.4.31`

Change the following lines in the build.gradle
```groovy
// in the id section
id 'org.jetbrains.kotlin.jvm' version "${kotlinVersion}"
id 'org.jetbrains.kotlin.plugin.spring' version "${kotlinVersion}"
id 'org.jetbrains.kotlin.kapt' version "${kotlinVersion}"

// in the dependencies section
implementation 'org.jetbrains.kotlin:kotlin-reflect',
implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8',

// and the compile task
compileKotlin {
  kotlinOptions {
    freeCompilerArgs = ["-Xjsr305=strict"]
    jvmTarget = javaVersion
  }
}
```
Running that code locally with `gradlew azureFunctionsRun` works fine, but when deployed to Azure it shows that NullPointerException.

So is this a bug in Azure and must be fixed by Microsoft or can that be an Issue in `org.springframework.cloud.function.adapter.azure.FunctionInvoker` or with Spring Cloud?

**Comment by olegz** [comment]
FWIW, your SO post didn't have the right tag so I was not notified ;) Basically next time use `spring-cloud-function` tag.

Anyway, i'll look at this

**Comment by MBurchard** [comment]
@olegz thank you.

A lot has happened again. I don't think it's Kotlin or Spring Cloud anymore.  
In the meantime, I have worked my way step by step through Microsoft documentation and tested every little step.  
The whole application worked even with Java only for very simple things.  
When I suddenly integrated the Microsoft Graph API, the NPE came up again and nothing worked anymore.  
I didn't even used the Graph API, I just added the following to build.gradle.

```groovy
dependencies {
  annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

  implementation 'com.google.code.findbugs:jsr305:3.0.2',
      "org.springframework.cloud:spring-cloud-starter-function-web:${springCloudVersion}",
      "org.springframework.cloud:spring-cloud-function-adapter-azure:${springCloudVersion}",
      "com.auth0:java-jwt:${javaJwtVersion}",
      // works fine until the next line is uncommented   
      // "com.microsoft.graph:microsoft-graph:${microsoftGraphVersion}"

  compileOnly "com.microsoft.azure.functions:azure-functions-java-library:${azureFunctionsVersion}"



  testImplementation('org.springframework.boot:spring-boot-starter-test') {
    exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
  }
}
```
The customer plans to open a support requests at Microsoft.

**Comment by olegz** [comment]
@MBurchard Any chance you can provide a full stack trace. This is indeed strange since I could see how spring library may interfere, but non-spring library?

Anyway, the full stack trace could provide more ideas

**Comment by olegz** [comment]
@MBurchard any updates on this?

**Comment by MBurchard** [comment]
We are checking it with Microsoft.
Will come back and report

**Comment by olegz** [comment]
Any more updates on this?

**Comment by MBurchard** [comment]
Thank you @olegz for asking.
Forgot to update this request.
We found the problem.
Unfortunately one has to configure the `MAIN_CLASS` manually via the Webbrowser at the Azure Webinterface.

> Open the Function App > under Settings select Configuration > Application Settings > Add the setting “MAIN_CLASS” with value “com.uniper.comstar.ComSTARAzureFunctionsApplication” > then hit Save

I'm really surprised this is not done automatically during the deployment using the Gradle task provided by Microsoft.
In addition the documentation does not say this... nowhere...
