### ISSUE TITLE
Function Routing not working, but direct bean invocation works

### ISSUE THREAD

**Issue by reaperc9000** [spring-cloud/spring-cloud-function#686]
**Describe the bug**
I have a project that has multiple functions to serve requests from AWS Lambda.  Let's say my function is `save`. I can invoke the function on http://localhost:8080/save and it works just fine. Since I have multiple functions to invoke, I wanted to avoid setting up a lambda per function. I tried use the Function Routing feature to route the  by setting the property `spring.cloud.stream.function.routing.enabled=true` and passing in `spring.cloud.function.definition` as message header. However, this is failing with `java.lang.ClassCastException: java.util.LinkedHashMap incompatible with <Type>`. I have shared the example below

**Sample**

```
package com.example.demo

import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.stereotype.Service

data class Event (
    val id: String,
    val name: String,
    val data: String
)

data class EventResponse(
    val status: String,
    val ids : List<String>
)

@Service
class EventService {
    fun save(events: List<Event>): EventResponse {
        var ids: List<String> = events.map {
            it.id
        }
        return  EventResponse("SUCCESS", ids)
    }
}

@Configuration
class Function {

    @Bean
    fun save(eventService: EventService): (List<Event>) -> EventResponse {
        return {
            eventService.save(it)
        }
    }
}
```

If I use HTTP request to the bean works
```
curl -XPOST 'http://localhost:8080/save' \
-H 'Content-Type: application/json' \
-d '[
    {
    "id": "isddsddwqdcZC",
    "name": "save",
    "data": "blah blah"
    }
]'
```

If I used the function router after setting `spring.cloud.stream.function.routing.enabled=true`, it fails with the stack trace below

```
curl -X POST 'http://localhost:8080/functionRouter' \
-H'spring.cloud.function.definition: save' \
-H'Content-Type: application/json' \
-d'[
    {
    "id": "isddsddwqdcZC",
    "name": "save",
    "data": "blah blah"
    }
]'
```

```
java.lang.ClassCastException: java.util.LinkedHashMap incompatible with com.example.demo.Event
        at com.example.demo.EventService.save(Function.kt:40) ~[classes/:na]
        at com.example.demo.Function$save$1.invoke(Function.kt:34) ~[classes/:na]
        at com.example.demo.Function$save$1.invoke(Function.kt:29) ~[classes/:na]
        at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.invoke(KotlinLambdaToFunctionAutoConfiguration.java:155) ~[spring-cloud-function-kotlin-3.1.2.jar:3.1.2]
        at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.apply(KotlinLambdaToFunctionAutoConfiguration.java:131) ~[spring-cloud-function-kotlin-3.1.2.jar:3.1.2]
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunctionAndEnrichResultIfNecessary(SimpleFunctionRegistry.java:734) ~[spring-cloud-function-context-3.1.2.jar:3.1.2]
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunction(SimpleFunctionRegistry.java:690) ~[spring-cloud-function-context-3.1.2.jar:3.1.2]
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:592) ~[spring-cloud-function-context-3.1.2.jar:3.1.2]
        at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:435) ~[spring-cloud-function-context-3.1.2.jar:3.1.2]
        at org.springframework.cloud.function.context.config.RoutingFunction.route(RoutingFunction.java:166) ~[spring-cloud-function-context-3.1.2.jar:3.1.2]
        at org.springframework.cloud.function.context.config.RoutingFunction.lambda$route$1(RoutingFunction.java:146) ~[spring-cloud-function-context-3.1.2.jar:3.1.2]
        at org.springframework.cloud.function.context.config.RoutingFunction$$Lambda$763/0x0000000000000000.apply(Unknown Source) ~[na:na]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.tryOnNext(FluxMapFuseable.java:309) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.tryOnNext(FluxMapFuseable.java:311) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.fastPath(FluxIterable.java:617) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.request(FluxIterable.java:502) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:354) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:354) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:354) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.request(FluxPeekFuseable.java:437) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:354) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:354) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.request(FluxPeekFuseable.java:437) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.request(FluxMapFuseable.java:354) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onSubscribe(MonoCollectList.java:79) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:263) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onSubscribe(FluxPeekFuseable.java:471) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:263) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:263) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onSubscribe(FluxPeekFuseable.java:471) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:263) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:263) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onSubscribe(FluxMapFuseable.java:263) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:160) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86) ~[reactor-core-3.4.4.jar:3.4.4]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4099) ~[reactor-core-3.4.4.jar:3.4.4]
        at org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler$DeferredResultSubscriber.connect(ReactiveTypeHandler.java:451) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.mvc.method.annotation.ReactiveTypeHandler.handleValue(ReactiveTypeHandler.java:166) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler.handleReturnValue(ResponseBodyEmitterReturnValueHandler.java:154) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[spring-web-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:124) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[tomcat-embed-core-9.0.44.jar:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.44.jar:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.5.jar:5.3.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.5.jar:5.3.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.5.jar:5.3.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.5.jar:5.3.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.5.jar:5.3.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.5.jar:5.3.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at java.base/java.lang.Thread.run(Thread.java:836) ~[na:na]
```

**Comment by olegz** [comment]
The `spring.cloud.stream.function.routing.enabled` has absolutely no effect in spring-cloud-function and is a deprecated property from another project.  Here is the more info specific to [s-c-function routing](https://docs.spring.io/spring-cloud-function/docs/3.1.1/reference/html/spring-cloud-function.html#_function_routing_and_filtering).

**Comment by olegz** [comment]
Also, I just added a test to validate the [condition](https://github.com/spring-cloud/spring-cloud-function/commit/05907134f0477e772a5759690ac8d55f6679d53a#diff-139292c111f929f56ac0e9c71159d30bf5bffb90384cc90cb75cd81490f07cc2R98) you are describing and it passes.

So the best thing you can do is setup a small project with bare minimum that reproduces the issue and push it to GitHub so we can take a look

**Comment by reaperc9000** [comment]
Thanks for looking into this @olegz and sharing the test. I have the demo project with a readme at https://github.com/reaperc9000/scf-issue-686-function-routing. I think the issue is related to usage of a `List<>` in this case. 

P.S. The `EventService`  is immaterial and was added to replicate my project setup as closely as possible. You can ignore that.

**Comment by olegz** [comment]
Perfect, i'll look at it and make sure it os fixed for the next release

**Comment by olegz** [comment]
I am changing it from bug to enhancement, since it actually works if you correct your curl command,  but indeed could be improved.
So here is what I am doing
```
~@oleg$ curl -X POST 'http://localhost:8080/functionRouter' -H'spring.cloud.function.definition: save' -H'Content-Type: application/json' -d'[
    [{
    "id": "isddsddwqdcZC",
    "name": "save",
    "data": "blah blah"
    }]
]'
[{"status":"SUCCESS","ids":["isddsddwqdcZC"]}]~@oleg$ 

```

Notice how  the input is identified as a collection

**Comment by reaperc9000** [comment]
Is this intentional behavior? The Function should be accepting a `List<Event>` whereas in the curl command you have provided, its accepting List of `List<Event>`. Also the response is being returned as a list when the expectation should be to return `EventResponse`.

**Comment by olegz** [comment]
I would not classify it as an intentional, hence I am keeping it open for potential improvement

**Comment by olegz** [comment]
Duplicate to https://github.com/spring-cloud/spring-cloud-function/issues/698 where the issue has been resolved

**Comment by reaperc9000** [comment]
Thanks @olegz . I will test and let you know how it goes

**Comment by YBCoding** [comment]
@olegz Is it really fixed ? I was going to open an issue when I saw this one. I have a simple example (based on version 3.1.3) that shows the problem : 
https://github.com/YBCoding/spring-cloud-function-router-example

**Comment by olegz** [comment]
You seem to be describing a whole other issue as I can't understand what role is plaid by `RequestProcessor` (which is in web module) and `RoutingFunction` in the context of AWS

Can you please raise a new issue and provide additional details?

**Comment by YBCoding** [comment]
@olegz Oh I'm sorry, I was testing with the web module in place of emulating [CustomRuntimeEventLoop ](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/test/java/org/springframework/cloud/function/adapter/aws/CustomRuntimeEventLoopTest.java) (I suppose) for my tests in local. 
Still, as you said, maybe it means there is still a problem with routing and the web module ? I'll open an issue with the provided repository. Thanks for the fast reply =)

**Comment by olegz** [comment]
I know it works in AWS as there is a new [sample](https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-aws-routing) and [docs](https://docs.spring.io/spring-cloud-function/docs/3.1.3/reference/html/aws.html#_aws_function_routing).
So Iam a bit puzzled as to what exactly you are trying to do, but yes feel free to raise a new issue with additional details
