### ISSUE TITLE
ConcurrentModificationException at FunctionInvoker

### ISSUE THREAD

**Issue by brunorgs30** [spring-cloud/spring-cloud-function#707]
**Describe the bug**
I'm using EventHub trigger with spring-cloud-function-adapter-azure 3.1.3 and Spring Boot 2.4.6 with java 8 but when it's the first time spring boot will initialize and have multiple messages to process from event hub, the trigger make multiple async calls. Then spring cloud throws multiple ConcurrentModificationException.

```
Exception: ConcurrentModificationException: 
Stack: java.lang.reflect.InvocationTargetException
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
     at com.microsoft.azure.functions.worker.broker.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:54)
     at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
     at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
     at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
     at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
     at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
     at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1579)
     at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
     at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
     at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
     at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
     at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry.findFunctionInFunctionRegistrations(SimpleFunctionRegistry.java:258)
     at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry.compose(SimpleFunctionRegistry.java:274)
     at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry.doLookup(SimpleFunctionRegistry.java:187)
     at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.lookup(BeanFactoryAwareFunctionRegistry.java:156)
     at org.springframework.cloud.function.context.FunctionCatalog.lookup(FunctionCatalog.java:42)
     at org.springframework.cloud.function.adapter.azure.FunctionInvoker.handleRequest(FunctionInvoker.java:115)
```

**Sample**
```
public class EventHubFunction extends FunctionInvoker<String, String>{

    @FunctionName("receiveEventHubMsg")
    public void receiveEventHubMsg(
            @EventHubTrigger(
                    name = "msg",
                    eventHubName = "eventHubName",
                    cardinality = Cardinality.MANY,
                    connection = "connection",
                    consumerGroup = "consumerGroup"
            ) String msg,
            ExecutionContext context
    ){
        handleRequest(msg, context);
    }
}
```

**Comment by olegz** [comment]
Wsa able to reproduce it

**Comment by MitkoTschimev** [comment]
Can we release a new patch version? We had to update to 3.1.3 do get rid of the null pointer exception but having now this error.
Is there a reason why no new version was published till now?

**Comment by olegz** [comment]
We will be releasing soon
