### ISSUE TITLE
Deploy backgroundFunction in GCP is not working

### ISSUE THREAD

**Issue by Jojoooo1** [spring-cloud/spring-cloud-function#772]
**Describe the bug**
Trying to deploy the sample background function is giving the following error in GCP logs:
```
2021-11-28 14:52:45.436 BRT
function-2 Exception in thread "main" java.lang.RuntimeException: Class com.example.BackgroundFunctionMain must implement one of these interfaces: com.google.cloud.functions.BackgroundFunction, com.google.cloud.functions.RawBackgroundFunction, com.google.cloud.functions.CloudEventsFunction at com.google.cloud.functions.invoker.BackgroundFunctionExecutor.forClass(BackgroundFunctionExecutor.java:113) at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:247) at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:121)
Exception in thread "main" java.lang.RuntimeException: Class com.example.BackgroundFunctionMain must implement one of these interfaces: com.google.cloud.functions.BackgroundFunction, com.google.cloud.functions.RawBackgroundFunction, com.google.cloud.functions.CloudEventsFunction at com.google.cloud.functions.invoker.BackgroundFunctionExecutor.forClass(BackgroundFunctionExecutor.java:113) at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:247) at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:121)
```

**Sample**
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>io.spring.sample</groupId>
	<artifactId>function-sample-gcp-background</artifactId>
	<version>2.0.0.RELEASE</version>
	<packaging>jar</packaging>

	<name>function-sample-gcp-background</name>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<java.version>11</java.version>
		<spring-cloud-function-adapter-gcp.version>3.1.5</spring-cloud-function-adapter-gcp.version>
		<function-maven-plugin.version>0.10.0</function-maven-plugin.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-function-adapter-gcp</artifactId>
			<version>${spring-cloud-function-adapter-gcp.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<outputDirectory>target/deploy</outputDirectory>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.springframework.cloud</groupId>
						<artifactId>spring-cloud-function-adapter-gcp</artifactId>
						<version>${spring-cloud-function-adapter-gcp.version}</version>
					</dependency>
				</dependencies>
			</plugin>

			<plugin>
				<groupId>com.google.cloud.functions</groupId>
				<artifactId>function-maven-plugin</artifactId>
				<version>${function-maven-plugin.version}</version>
				<configuration>
					<functionTarget>org.springframework.cloud.function.adapter.gcp.GcfJarLauncher</functionTarget>
					<port>8081</port>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/libs-snapshot-local</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<releases>
				<enabled>false</enabled>
			</releases>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/libs-milestone-local</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-releases</id>
			<name>Spring Releases</name>
			<url>https://repo.spring.io/release</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/libs-snapshot-local</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<releases>
				<enabled>false</enabled>
			</releases>
		</pluginRepository>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/libs-milestone-local</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-releases</id>
			<name>Spring Releases</name>
			<url>https://repo.spring.io/libs-release-local</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
</project>

```

```
@SpringBootApplication
public class BackgroundFunctionMain {

	public static void main(String[] args) {
		SpringApplication.run(BackgroundFunctionMain.class, args);
	}

	/**
	 * The background function which triggers on an event from Pub/Sub and consumes the Pub/Sub
	 * event message.
	 */
	@Bean
	public Consumer<PubSubMessage> pubSubFunction() {
		return message -> {
			System.out.println("message: " + message);
			String decodedMessage = new String(Base64.getDecoder().decode(message.getData()), StandardCharsets.UTF_8);
			System.out.println("Received Pub/Sub message with data: " + decodedMessage);
		};
	}
}
```

**Comment by Jojoooo1** [comment]
fixed using:

```
@SpringBootApplication
public class BackgroundFunctionMain implements BackgroundFunction<PubSubMessage> {

	public static void main(String[] args) {
		SpringApplication.run(BackgroundFunctionMain.class, args);
	}

	@Override
	public void accept(PubSubMessage message, Context context) {
	}

}
```
