### ISSUE TITLE
Unable to get a valid JSON response from AWS Lambda in Custom Runtime processing requests from ALB

### ISSUE THREAD

**Issue by gergogera** [spring-cloud/spring-cloud-function#785]
I have an AWS Lamdba running in a custom runtime and processing requests forwarded from an AWS Application Load Balancer. The code is utilising spring-cloud-function-adapter-aws.

The problem is Im not able to get a valid JSON response when triggering the lamdba from the ALB.

The requests / responses covering this scenario should be the followings:
`com.amazonaws.services.lambda.runtime.events.ApplicationLoadBalancerRequestEvent`
`com.amazonaws.services.lambda.runtime.events.ApplicationLoadBalancerResponseEvent`

I think there are 2 problems when `org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop` calls `org.springframework.cloud.function.adapter.aws.AWSLambdaUtils`

1) When Im using a simple POJO mapper function declaration like `Function<String, MyDomainModel>`

`AWSLambdaUtils. generateOutput` will remove the double quotes here resulting in invalid JSON- https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/AWSLambdaUtils.java#L196

and this line is doing something else than the name suggests: https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/AWSLambdaUtils.java#L206

When Im testing the lambda through the UI by calling it directly I got valid JSON response most probably because it wont be considered as AWS_API_GATEWAY - https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/AWSLambdaUtils.java#L176

and just returns the payload without removing the quotes.

2) When Im trying to return directly `ApplicationLoadBalancerResponseEvent` with a function declaration like `Function<String, ApplicationLoadBalancerResponseEvent>`

I got exception
```
Exception in thread "pool-2-thread-1" java.lang.ClassCastException: com.amazonaws.services.lambda.runtime.events.ApplicationLoadBalancerResponseEvent cannot be cast to byte[]
at org.springframework.cloud.function.adapter.aws.AWSLambdaUtils.generateOutput(AWSLambdaUtils.java:175)
at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:150)
at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.lambda$run$0(CustomRuntimeEventLoop.java:84)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:829)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

**Comment by olegz** [comment]
Yeah, this is because we do not yet provide direct support for `ApplicationLoadBalancerResponseEvent`. Effectively we're adding support for various AWS events as they are been requested, so I'll mark this as a feature request and we'll get it done.
