### ISSUE TITLE
AWS Custom Bean Runtime not working - directly cloned from samples

### ISSUE THREAD

**Issue by Richardmbs12** [spring-cloud/spring-cloud-function#788]
Good day,

I am trying to use the aws custom bean sample. https://github.com/spring-cloud/spring-cloud-function/tree/v3.2.1/spring-cloud-function-samples/function-sample-aws-custom-bean

I cloned it, on AWS Lambda I chose custom runtime, uploaded the zip. As my handler, I specified "uppercase".

This is the error I am getting:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customRuntimeEventLoop': Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop] from ClassLoader [sun.misc.Launcher$AppClassLoader@4e0e2f2a]
Caused by: java.lang.ClassNotFoundException: org.springframework.web.client.RestTemplate.
```

I was looking at using the custom runtime with a spring native docker image (mvn spring-boot:build-image), as I hoped this would work as an implementation for the lambda custom runtime interface as a native image, as standard aws-lambda-java-runtime-interface-client doesnt work with spring native.

Full logs below:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customRuntimeEventLoop': Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop] from ClassLoader [sun.misc.Launcher$AppClassLoader@4e0e2f2a]
--
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) [spring-boot-2.6.1.jar:2.6.1]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) [spring-boot-2.6.1.jar:2.6.1]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) [spring-boot-2.6.1.jar:2.6.1]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) [spring-boot-2.6.1.jar:2.6.1]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) [spring-boot-2.6.1.jar:2.6.1]
  | 2022-01-10T21:58:46.417+02:00 | at com.example.LambdaApplication.main(LambdaApplication.java:68) [task/:na]
  | 2022-01-10T21:58:46.417+02:00 | Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop] from ClassLoader [sun.misc.Launcher$AppClassLoader@4e0e2f2a]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321) ~[spring-core-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:232) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:210) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:149) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:305) ~[spring-context-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1116) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | ... 14 common frames omitted
  | 2022-01-10T21:58:46.417+02:00 | Caused by: java.lang.NoClassDefFoundError: org/springframework/web/client/RestTemplate
  | 2022-01-10T21:58:46.417+02:00 | at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_201]
  | 2022-01-10T21:58:46.417+02:00 | at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_201]
  | 2022-01-10T21:58:46.417+02:00 | at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_201]
  | 2022-01-10T21:58:46.417+02:00 | at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.3.13.jar:5.3.13]
  | 2022-01-10T21:58:46.417+02:00 | ... 21 common frames omitted
  | 2022-01-10T21:58:46.417+02:00 | Caused by: java.lang.ClassNotFoundException: org.springframework.web.client.RestTemplate
  | 2022-01-10T21:58:46.417+02:00 | at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_201]
  | 2022-01-10T21:58:46.417+02:00 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_201]
  | 2022-01-10T21:58:46.417+02:00 | at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_201]
  | 2022-01-10T21:58:46.417+02:00 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_201]
  | 2022-01-10T21:58:46.417+02:00 | ... 25 common frames omitted
```

**Comment by olegz** [comment]
Right, there is a dependency missing in the example as part of the refactoring of other things. I'll fix it. 
Meanwhile you can add it yourself. Just add this to the POM, rebuild and redeploy
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
</dependency>
```
