### ISSUE TITLE
Aws Lambda serverless functional bean implementation

### ISSUE THREAD

**Issue by Jasper-ui** [spring-cloud/spring-cloud-function#843]
Hello Guys, I am trying to implement a Spring cloud function that I want to host in aws. My target is to integrate this with the AWS API gateway, and as you cna see bellow, I am using a very functional approach, to improve the executions times drastically, and give me full control over the registered beans. But when I deploy on aws lambda, I am able to change the funvtions from 1 to 2, by specifying the spring.cloud.function.definition to the function, but I wish for this to be done trough the request headers as described in documentation  at https://cloud.spring.io/spring-cloud-static/spring-cloud-function/3.0.0.RC1/reference/html/spring-cloud-function.html#_function_catalog_and_flexible_function_signatures

But whenever I use the AWS API gateway request with the headers added, it always results in `null` no function found null pointer exception. Can anybody help please? See code bellow

```
`
package com.example.demo;


import org.springframework.boot.SpringBootConfiguration;
import org.springframework.cloud.function.adapter.aws.FunctionInvoker;
import org.springframework.cloud.function.context.FunctionRegistration;
import org.springframework.cloud.function.context.FunctionalSpringApplication;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.support.GenericApplicationContext;

@SpringBootConfiguration
public class Demo4Application implements ApplicationContextInitializer<GenericApplicationContext> {

  public static void main(String[] args) {
   // FunctionalSpringApplication.run(Demo4Application.class,
                                   // args);

  }


  @Override
  public void initialize(GenericApplicationContext applicationContext) {


    applicationContext.registerBean("function1",
                                           FunctionRegistration.class,
                                           () -> new FunctionRegistration<>(new FunctionClass())
                                             .type(FunctionClass.class));

    applicationContext.registerBean("function2",
                                    FunctionRegistration.class,
                                    () -> new FunctionRegistration<>(new MyFunction2())
                                      .type(MyFunction2.class));

    applicationContext.registerBean(FunctionClass.class);
    applicationContext.registerBean(MyFunction2.class);


  }
}`
```

My POM file

```
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.5</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>demo4</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo4</name>
    <description>demo4</description>
    <properties>
        <java.version>11</java.version>
    </properties>

    <repositories>
        <repository>
            <id>spring-milestone</id>
            <name>Spring Milestone Repository</name>
            <url>https://repo.spring.io/milestone</url>
        </repository>
        <repository>
            <id>spring-repo</id>
            <name>Spring Repository</name>
            <url>https://repo.spring.io/release</url>
        </repository>
        <repository>
            <id>spring-snapshot</id>
            <name>Spring Snapshot Repository</name>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-function-web</artifactId>
            <version>3.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-function-web</artifactId>
            <version>3.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-function-adapter-aws</artifactId>
            <version>3.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-function-context</artifactId>
            <version>3.2.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>3.11.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>1.2.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2020.0.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>



    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>org.springframework.boot.experimental</groupId>
                        <artifactId>spring-boot-thin-layout</artifactId>
                        <version>1.0.27.RELEASE</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                    <shadedClassifierName>aws</shadedClassifierName>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```
```
`
`
public class FunctionClass implements Supplier<String> {
  @Override
  public String get() {
    return "my string";
  }
}
`
```

```
`
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, sdch",
    "Accept-Language": "en-US,en;q=0.8",
    "Cache-Control": "max-age=0",
    "CloudFront-Forwarded-Proto": "https",
    "CloudFront-Is-Desktop-Viewer": "true",
    "CloudFront-Is-Mobile-Viewer": "false",
    "CloudFront-Is-SmartTV-Viewer": "false",
    "CloudFront-Is-Tablet-Viewer": "false",
    "CloudFront-Viewer-Country": "US",
    "Host": "1234567890.execute-api.us-east-1.amazonaws.com",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Custom User Agent String",
    "Via": "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)",
    "X-Amz-Cf-Id": "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA==",
    "X-Forwarded-For": "127.0.0.1, 127.0.0.2",
    "X-Forwarded-Port": "443",
    "X-Forwarded-Proto": "https",
    "spring_cloud_function_definition": "function1",
    "spring.cloud.function.definition": "function1",
    "spring-cloud-function-definition": "function1",
    "function_name": "function1",
    "function-name": "function1",
    "function.name": "function1",
`
```

**Comment by Jasper-ui** [comment]
Adding error 
```
START RequestId: fac1bbd4-77bf-4349-ae45-544f149b8e38 Version: $LATEST
21:29:31.971 [main] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Main class: class com.example.demo.Demo4Application
2022-03-30 21:29:36.671  INFO 9 --- [           main] o.s.c.f.a.aws.CustomRuntimeInitializer   : AWS Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
2022-03-30 21:29:36.830  INFO 9 --- [           main] lambdainternal.AWSLambda                 : Starting AWSLambda using Java 11.0.14.1 on 169.254.27.37 with PID 9 (/var/runtime/lib/aws-lambda-java-runtime-0.2.0.jar started by sbx_user1051 in /var/task)
2022-03-30 21:29:36.831  INFO 9 --- [           main] lambdainternal.AWSLambda                 : No active profile set, falling back to 1 default profile: "default"
2022-03-30 21:29:39.232  INFO 9 --- [           main] lambdainternal.AWSLambda                 : Started AWSLambda in 6.461 seconds (JVM running for 8.796)
2022-03-30 21:29:39.290  INFO 9 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Locating function: 'null'
2022-03-30 21:29:39.310  INFO 9 --- [           main] o.s.c.f.c.c.SimpleFunctionRegistry       : Failed to locate function: 
2022-03-30 21:29:39.311  INFO 9 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : More then one function is available in FunctionCatalog. [com.example.demo.FunctionClass, com.example.demo.MyFunction2, function2, function1] Will default to RoutingFunction, Expecting 'spring.cloud.function.definition' or 'spring.cloud.function.routing-expression' as Message headers. If invocation is over API Gateway, Message headers can be provided as HTTP headers.
2022-03-30 21:29:39.312  INFO 9 --- [           main] o.s.c.f.c.c.SimpleFunctionRegistry       : Failed to locate function: functionRouter
java.lang.NullPointerException: java.lang.NullPointerException
java.lang.NullPointerException
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:206)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:80)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)

END RequestId: fac1bbd4-77bf-4349-ae45-544f149b8e38
REPORT RequestId: fac1bbd4-77bf-4349-ae45-544f149b8e38	Duration: 9117.25 ms	Billed Duration: 9118 ms	Memory Size: 512 MB	Max Memory Used: 50 MB	
Unknown application error occurred
java.lang.NullPointerException
```

**Comment by Jasper-ui** [comment]
For anybody encountering the same issue,

What I did was I created my own version of the FunctionInvoker (very similar), that reads the headers and assigns `this.function` to the value listed in the headers. Which seems to be working just fine!

Would be great if this was somehow implemented in the FunctionInvoker or a different generic handler

**Comment by jaganm2018** [comment]
hi,
i did for aws lambda with spring cloud function. here is the example: https://github.com/jaganm2018/spring-cloud-function-aws

and you have to pass header as spring_cloud_function-defination.

Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker

**Comment by olegz** [comment]
Actually, we do not control API Gateway invocation of a function so it would be nearly impossible for us to do. But what you can do instead is to use RoutingFunction and have an expression to extract function name from message header which in that case would be your HTTP headers. Basically you'll get exactly what you are asking for, just slightly different way.

We actually have an example demonstrating exactly that - https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-aws-routing

Also, here is more info on function routing - https://docs.spring.io/spring-cloud-function/docs/3.2.3/reference/html/spring-cloud-function.html#_function_routing_and_filtering

Please let us know if you need more help with it.

**Comment by olegz** [comment]
Closing it due to lack of followup from the original reporter
