### ISSUE TITLE
ClassCastException when using custom runtime

### ISSUE THREAD

**Issue by Twometer** [spring-cloud/spring-cloud-function#859]
**Describe the bug**
The following error occurs when using spring native and the custom runtime:
```
Exception in thread "pool-4-thread-1" java.lang.ClassCastException: com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent cannot be cast to byte[]
  at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.eventLoop(CustomRuntimeEventLoop.java:150)
  at org.springframework.cloud.function.adapter.aws.CustomRuntimeEventLoop.lambda$run$0(CustomRuntimeEventLoop.java:84)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.lang.Thread.run(Thread.java:829)
  at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
  at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```

The custom runtime just assumes that I return a `byte[]` from the function, which I don't. I think the regular Java runner does automatic conversion to JSON.

Maybe this cast is the problem? It just assumes that a `Message<byte[]>` is returned:
https://github.com/spring-cloud/spring-cloud-function/blob/b73b421366ecd4a939c9fcbc49f451ca98ac823f/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/CustomRuntimeEventLoop.java#L144

**Sample**
Any app with Spring Native + Spring Cloud Function that does not return `byte[]`, running on an AWS custom runtime

**Comment by olegz** [comment]
I believe this was resolved with https://github.com/spring-cloud/spring-cloud-function/commit/2985193fd96b967f212eaf4c2d074432864c3e06 Feel free to reopen if it is not
