### ISSUE TITLE
NullPointerException in StreamBridge with spring-cloud-stream 3.2.3

### ISSUE THREAD

**Issue by shreeshasa** [spring-cloud/spring-cloud-function#868]
We've upgraded `spring-cloud-dependencies` `2021.0.1` --> `2021.0.2`. It seems streamBridge.send() is no longer working with the upgrade and throwing NullPointerException.

Here's the stacktrace -
```
java.lang.NullPointerException
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:99)
	at org.springframework.cloud.function.cloudevent.CloudEventsFunctionInvocationHelper.postProcessResult(CloudEventsFunctionInvocationHelper.java:48)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:232)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:170)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:150)
```

**Comment by shreeshasa** [comment]
![image](https://user-images.githubusercontent.com/28813505/167462012-d4af3514-82d9-4f48-bb67-023fc0d463fa.png)

At line # 99 (and the argument "input" being passed as "null" from StreamBridge.send() which maybe causing NPE)- 
![image](https://user-images.githubusercontent.com/28813505/167462252-98e48ad3-ecc4-4f72-b97d-5fa7258833d9.png)

**Comment by shreeshasa** [comment]
At line # 232 from `StreamBridge`
resultMessage = (Message<?>) this.functionInvocationHelper.postProcessResult(resultMessage, null);

**Comment by olegz** [comment]
I will look, but can you please upgrade s-c-function to 3.2.4 and see if the problem is still there?

**Comment by shreeshasa** [comment]
Well, it worked with `spring-cloud-function-context` `3.2.4`, thanks for your help. I'm closing the issue.
