### ISSUE TITLE
Add native-image support for cloud-function-web

### ISSUE THREAD

**Issue by mhalbritter** [spring-cloud/spring-cloud-function#896]
The [Spring AOT Smoke test for cloud-function-web](https://ci.spring.io/teams/spring-aot-smoke-tests/pipelines/spring-aot-smoke-tests-1.0.x/jobs/cloud-function-web/builds/1) is currently broken. You can find the [smoke test here](https://github.com/spring-projects/spring-aot-smoke-tests/tree/main/cloud-function-web). The reason why it's broken is this exception (which you can find by looking at the Gradle Build Scan at the bottom of the CI log output):

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionCatalog': Instantiation of supplied bean failed	
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1235) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1209) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1156) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:566) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:526) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:930) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:926) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:592) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[cloud-function-web:3.0.0-SNAPSHOT]	
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:729) ~[cloud-function-web:3.0.0-SNAPSHOT]	
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:428) ~[cloud-function-web:3.0.0-SNAPSHOT]	
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[cloud-function-web:3.0.0-SNAPSHOT]	
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[cloud-function-web:3.0.0-SNAPSHOT]	
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[cloud-function-web:3.0.0-SNAPSHOT]	
	at com.example.cloud.function.web.CloudFunctionWebApplication.main(CloudFunctionWebApplication.java:10) ~[cloud-function-web:na]	
Caused by: java.lang.NullPointerException: null	
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry.<init>(SimpleFunctionRegistry.java:121) ~[cloud-function-web:4.0.0-SNAPSHOT]	
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.<init>(BeanFactoryAwareFunctionRegistry.java:64) ~[na:na]	
	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration.functionCatalog(ContextFunctionCatalogAutoConfiguration.java:139) ~[cloud-function-web:4.0.0-SNAPSHOT]	
	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration__BeanDefinitions.lambda$getFunctionCatalogInstance$0(ContextFunctionCatalogAutoConfiguration__BeanDefinitions.java:49) ~[na:na]	
	at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:63) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.util.function.ThrowingFunction.apply(ThrowingFunction.java:51) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	at org.springframework.beans.factory.aot.AutowiredInstantiationArgumentsResolver.resolve(AutowiredInstantiationArgumentsResolver.java:156) ~[na:na]	
	at org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration__BeanDefinitions.getFunctionCatalogInstance(ContextFunctionCatalogAutoConfiguration__BeanDefinitions.java:49) ~[na:na]	
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1224) ~[cloud-function-web:6.0.0-SNAPSHOT]	
	... 18 common frames omitted
```

It would be nice if cloud-function-web would work in a native image.

**Comment by olegz** [comment]
This has been addressed with https://github.com/spring-cloud/spring-cloud-function/commit/e7f4008b1e4313fb802dd11a18a312c4dc3361d4
