### ISSUE TITLE
UnrecognizedPropertyException in ScheduledEvent

### ISSUE THREAD

**Issue by adzubla** [spring-cloud/spring-cloud-function#906]
I have a working application using **Spring Cloud 2020.0.6** that runs in AWS Lambda.

But when I upgraded spring cloud to **2021.0.3** its not starting because of this error:

```
Cannot convert event stream: java.lang.IllegalStateException
java.lang.IllegalStateException: Cannot convert event stream
    at org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler.convertStream(SpringBootStreamHandler.java:87)
    at org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler.handleRequest(SpringBootStreamHandler.java:54)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "version" (class com.amazonaws.services.lambda.runtime.events.ScheduledEvent), not marked as ignorable (8 known properties: "detail", "region", "resources", "detailType", "account", "source", "time", "id"])
 at [Source: (ByteArrayInputStream); line: 1, column: 13] (through reference chain: com.amazonaws.services.lambda.runtime.events.ScheduledEvent["version"])
    at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
    at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)
    at org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler.convertStream(SpringBootStreamHandler.java:83)
    ... 1 more
```

My `pom.xml` is attached:
[pom.txt](https://github.com/spring-cloud/spring-cloud-function/files/9209695/pom.txt)

**Comment by olegz** [comment]
The `SpringBoot*Handlers` were long deprecated in favor of `FunctionInvoker`. Basically there is no longer a need to implement anything other than Java Function. Please look at this Getting Started guide - https://docs.spring.io/spring-cloud-function/docs/current/reference/html/aws.html#_getting_started

**Comment by adzubla** [comment]
For the record, that how I solved this issue:

1. Changed dependency to spring cloud 2021.0.3 
2. Deleted my class that extended org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
3. Changed the handler to "org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest" (in serverless.yml)
4. Removed FUNCTION_NAME environment variable (in serverless.yml)
