### ISSUE TITLE
NPE when getting stream bridge function

### ISSUE THREAD

**Issue by declan782** [spring-cloud/spring-cloud-function#920]
**Describe the bug**
My app has several instances (running with same code and config), but only one of them getting NPE,

Exception stack:
java.lang.NullPointerException
	at org.springframework.cloud.stream.function.StreamBridge.getStreamBridgeFunction(StreamBridge.java:246)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:215)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:170)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:150)

spring-cloud-function version we're using:
spring-cloud-function-context: 3.2.6
spring-cloud-function-core: 3.2.5

**Sample**
N/A

**Comment by declan782** [comment]
it's the same case as described in below issue, any idea why this is happening?
https://github.com/spring-cloud/spring-cloud-stream/issues/2288

**Comment by olegz** [comment]
A small sample that reproduces the issue would help

**Comment by olegz** [comment]
Also, can you provide a full stack trace?

**Comment by declan782** [comment]
hi @olegz, 
Thanks for your reply, and sorry that I cannot provide a sample project that can reproduce the issue, because I cannot reproduce it locally either. Here is the full stack trace:
![image](https://user-images.githubusercontent.com/55685335/187329228-50433150-4fb2-4440-8149-d8eeef08704f.png)

Text version:
java.lang.NullPointerException
	at org.springframework.cloud.stream.function.StreamBridge.getStreamBridgeFunction(StreamBridge.java:246)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:215)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:170)
	at org.springframework.cloud.stream.function.StreamBridge.send(StreamBridge.java:150)
	....
	at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCommit(TransactionSynchronizationUtils.java:135)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerAfterCommit(TransactionSynchronizationUtils.java:123)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerAfterCommit(AbstractPlatformTransactionManager.java:936)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:782)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	...
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	...
	at com.tibco.tibjms.TibjmsxSessionImp._submit(TibjmsxSessionImp.java:4249)
	at com.tibco.tibjms.TibjmsxSessionImp._dispatchAsyncMessage(TibjmsxSessionImp.java:2299)
	at com.tibco.tibjms.TibjmsxSessionImp$Dispatcher.run(TibjmsxSessionImp.java:3754)

**Comment by olegz** [comment]
All, I see is some proxying going on, which could i suppose to cause an issue if component is not properly initilized, but what i will do is add a fail-safe logic with hopes that it will help

**Comment by declan782** [comment]
can you elaborate more how to apply fail-safe logic for this if streamBridge is not autowired properly in the component? Thanks.

**Comment by olegz** [comment]
StreamBridge was never meant to me NOT-autowired, hence my worries about how is it you're getting an instance of it?

**Comment by olegz** [comment]
I am also going to transfer it to s-c-stream
