### ISSUE TITLE
cloud-functions demo project uses springboot 3 which uses spring6 which uses java17 which is not compatible with aws lambda

### ISSUE THREAD

**Issue by arikanorh** [spring-cloud/spring-cloud-function#923]
**Describe the bug**
In [this document ](https://docs.spring.io/spring-cloud-function/docs/current/reference/html/aws.html)  the referenced [github project](https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-aws) uses springboot version 3.0.0-SNAPSHOT which uses spring 6 which uses java 17 which aws lambda does not support

**Sample**
WHen you deploy the project, it gives major minor version error

`Error loading class org.springframework.cloud.function.adapter.aws.FunctionInvoker: org/springframework/core/env/Environment has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0: java.lang.UnsupportedClassVersionError
java.lang.UnsupportedClassVersionError: org/springframework/core/env/Environment has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)`

I could fix the problem by downgrading to spring boot 2.7.3 and spring-cloud-functions to 3.1.0-SNAPSHOT

**Comment by olegz** [comment]
No, this document is pointing to versions 3.2.x which is based on Java 8, bot 2.7 etc. . . You probably using samples from main branch in github which is where the switch to java 17 and boot 3 has happened. 

Also, 3.1.x is EOL and no linger supported. Please use lates release which is 3.2.7.

**Comment by AlbertXingZhang** [comment]
> No, this document is pointing to versions 3.2.x which is based on Java 8, bot 2.7 etc. . . You probably using samples from main branch in github which is where the switch to java 17 and boot 3 has happened.
> 
> Also, 3.1.x is EOL and no linger supported. Please use lates release which is 3.2.7.

Hi @olegz, is 4.0.x compatible with Java 11 or Java 8 since AWS Lambda doesn't support Java 17 currently? Sorry for asking this question here because I think it might be related. Thanks.
