### ISSUE TITLE
Using Kotlin Functions in Spring Cloud Stream broken since 2021.0.4 

### ISSUE THREAD

**Issue by fschlag** [spring-cloud/spring-cloud-function#925]
The new 'lazy' way on how Kotlin functions are initialized which was introduced in 392a1f610343d7dd6313e70e4450c17ca5fef52c breaks the possibility to use a `Function` in Spring Cloud Stream.

**Sample**
In `application.properties` register the following Component as a function as

```properties
spring.cloud.stream.function.definition=myTestConsumer
```

```kotlin
import org.springframework.stereotype.Component
import java.util.function.Function

@Component
class MyTestConsumer : Function<String, String> {
    override fun apply(t: String): String {
        TODO("Not yet implemented")
    }
}
```

This causes the following exception:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'functionBindingRegistrar' defined in class path resource [org/springframework/cloud/stream/function/FunctionConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType (java.lang.Class and java.lang.reflect.ParameterizedType are in module java.base of loader 'bootstrap')
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.3.jar:2.7.3]
	at com.example.springcloudfunctiontest.SpringCloudFunctionTestApplicationKt.main(SpringCloudFunctionTestApplication.kt:13) ~[classes/:na]
Caused by: java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType (java.lang.Class and java.lang.reflect.ParameterizedType are in module java.base of loader 'bootstrap')
	at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.getFunctionRegistration(KotlinLambdaToFunctionAutoConfiguration.java:157) ~[spring-cloud-function-context-3.2.7.jar:3.2.7]
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.lookup(BeanFactoryAwareFunctionRegistry.java:156) ~[spring-cloud-function-context-3.2.7.jar:3.2.7]
	at org.springframework.cloud.function.context.FunctionCatalog.lookup(FunctionCatalog.java:42) ~[spring-cloud-function-context-3.2.7.jar:3.2.7]
	at org.springframework.cloud.stream.function.FunctionConfiguration$FunctionBindingRegistrar.afterPropertiesSet(FunctionConfiguration.java:863) ~[spring-cloud-stream-3.2.5.jar:3.2.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.22.jar:5.3.22]
	... 15 common frames omitted

```

This did work with `org.springframework.cloud:spring-cloud-dependencies:2021.0.3`. An example project that reproduces the issue can be found here: https://github.com/fschlag/SpringCloudFunctionTest

**Comment by olegz** [comment]
Strange, i'll look at it, but meanwhile you can have a workaround with 
```
@Bean
fun myTestConsumer(): (String) -> String {
    return {...}
}
```
and may be make a callback to the actual function. 
Basically it appears that the issue with how the function is processed when defined as `@Component`

**Comment by kubav182** [comment]
@olegz using 2023.0.1 still not working

**Comment by AndreKoepke** [comment]
I had the same problem with `rg.springframework.cloud:spring-cloud-dependencies:2023.0.1`. With the hint from @olegz I was able to solve it.

```kotlin
// working
@Bean
class Consumer : (Message<List<CustomType>>) -> Unit {
    override fun invoke(message: Message<List<CustomType>>) { ... }
}

// not working
@Bean
class Consumer : Consumer<Message<List<CustomType>>> {
    override fun accept(message: Message<List<CustomType>>) { ... }
}
```
