### ISSUE TITLE
FunctionInvoker with FunctionalSpringApplication does not work with AWS lambda events

### ISSUE THREAD

**Issue by LutherWest** [spring-cloud/spring-cloud-function#932]
**Describe the bug**
I'm using Spring Cloud Function and its [AWS adapter](https://docs.spring.io/spring-cloud-function/docs/current/reference/html/aws.html) to develop my AWS Lambda function.
I'm using my lambda function as [API Gateway lambda proxy integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html), thus I expect `APIGatewayProxyRequestEvent` as input and `APIGatewayProxyResponseEvent` as output (from `aws-lambda-java-events` dependency).
Using this setup with [Functional Bean Definitions](https://docs.spring.io/spring-cloud-function/docs/current/reference/html/aws.html#_functional_bean_definitions) leads to `java.lang.ClassCastException` exception.

**Sample**
`pom.xml` (only partially):
```xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.7.4</version>
    <relativePath/> <!-- lookup parent from repository -->
</parent>

<properties>
    <java.version>11</java.version>
    <spring-boot.version>2.7.4</spring-boot.version>
    <spring-cloud-function.version>3.2.7</spring-cloud-function.version>
    <aws-lambda-java-core.version>1.2.1</aws-lambda-java-core.version>
    <aws-lambda-events.version>3.11.0</aws-lambda-events.version>
</properties>
<dependencies>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-function-adapter-aws</artifactId>
    </dependency>
    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-lambda-java-core</artifactId>
        <version>${aws-lambda-java-core.version}</version>
    </dependency>
    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-lambda-java-events</artifactId>
        <version>${aws-lambda-events.version}</version>
    </dependency>

    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-lambda-java-serialization</artifactId>
        <version>1.0.0</version>
    </dependency>
</dependencies>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-function-dependencies</artifactId>
            <version>${spring-cloud-function.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

TestFunction (java.util.function itself):
```java
package com.company;

import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;
import org.springframework.stereotype.Component;

import java.util.function.Function;

@Component
public class TestFunction implements Function<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {
    @Override
    public APIGatewayProxyResponseEvent apply(APIGatewayProxyRequestEvent apiGatewayProxyRequestEvent) {
        return new APIGatewayProxyResponseEvent().withStatusCode(200).withBody("ok");
    }
}
```

First config option with functional bean definitions:
```java
package com.company;

import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.cloud.function.context.FunctionRegistration;
import org.springframework.cloud.function.context.FunctionType;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.context.support.GenericApplicationContext;

@SpringBootConfiguration(proxyBeanMethods = false)
public class FunctionalApplication implements ApplicationContextInitializer<GenericApplicationContext> {

    @Override
    public void initialize(GenericApplicationContext ctx) {
        ctx.registerBean("testFunction", FunctionRegistration.class, () -> new FunctionRegistration<>(new TestFunction())
                .type(FunctionType.from(APIGatewayProxyRequestEvent.class).to(APIGatewayProxyResponseEvent.class)));
    }
}
```

Second config option with regular spring boot application:
```java
package com.company;

import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class RegularApplication {

}
```

Runner class which should be executed to reproduce observed behavior:
```java
package com.company;

import org.springframework.cloud.function.adapter.aws.FunctionInvoker;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

public class Runner {
    public static void main(String[] args) throws IOException {
        final String request = "{\"resource\":\"/my/path\",\"path\":\"/my/path\",\"httpMethod\":\"GET\",\"headers\":{\"header1\":\"value1\",\"header2\":\"value2\"},\"multiValueHeaders\":{\"header1\":[\"value1\"],\"header2\":[\"value1\",\"value2\"]},\"queryStringParameters\":{\"parameter1\":\"value1\",\"parameter2\":\"value\"},\"multiValueQueryStringParameters\":{\"parameter1\":[\"value1\",\"value2\"],\"parameter2\":[\"value\"]},\"requestContext\":{\"accountId\":\"123456789012\",\"apiId\":\"id\",\"authorizer\":{\"claims\":null,\"scopes\":null},\"domainName\":\"id.execute-api.us-east-1.amazonaws.com\",\"domainPrefix\":\"id\",\"extendedRequestId\":\"request-id\",\"httpMethod\":\"GET\",\"identity\":{\"accessKey\":null,\"accountId\":null,\"caller\":null,\"cognitoAuthenticationProvider\":null,\"cognitoAuthenticationType\":null,\"cognitoIdentityId\":null,\"cognitoIdentityPoolId\":null,\"principalOrgId\":null,\"sourceIp\":\"IP\",\"user\":null,\"userAgent\":\"user-agent\",\"userArn\":null,\"clientCert\":{\"clientCertPem\":\"CERT_CONTENT\",\"subjectDN\":\"www.example.com\",\"issuerDN\":\"Example issuer\",\"serialNumber\":\"a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1\",\"validity\":{\"notBefore\":\"May 28 12:30:02 2019 GMT\",\"notAfter\":\"Aug  5 09:36:04 2021 GMT\"}}},\"path\":\"/my/path\",\"protocol\":\"HTTP/1.1\",\"requestId\":\"id=\",\"requestTime\":\"04/Mar/2020:19:15:17 +0000\",\"requestTimeEpoch\":1583349317135,\"resourceId\":null,\"resourcePath\":\"/my/path\",\"stage\":\"$default\"},\"pathParameters\":null,\"stageVariables\":null,\"body\":\"Hello from Lambda!\",\"isBase64Encoded\":false}";
        final ByteArrayInputStream bais = new ByteArrayInputStream(request.getBytes(StandardCharsets.UTF_8));
        final ByteArrayOutputStream baos = new ByteArrayOutputStream();

        new FunctionInvoker().handleRequest(bais, baos, null);

        System.out.println(new String(baos.toByteArray(), StandardCharsets.UTF_8));
    }
}
```

Running `Runner.main` with `MAIN_CLASS=com.company.RegularApplication` environment variable I'm getting:
```
2022-10-05 22:12:31.969  INFO 27272 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Locating function: 'null'
2022-10-05 22:12:31.977  INFO 27272 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Located function: 'testFunction'
2022-10-05 22:12:31.978  INFO 27272 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Received: <omitting>
{"statusCode":200,"headers":null,"multiValueHeaders":null,"body":"ok","isBase64Encoded":null}
```

Running `Runner.main` with `MAIN_CLASS=com.company.FunctionalApplication` environment variable I'm getting:
```
2022-10-05 22:31:40.070  INFO 23484 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Locating function: 'null'
2022-10-05 22:31:40.078  INFO 23484 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Located function: 'testFunction'
2022-10-05 22:31:40.080  INFO 23484 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Received: <omitting>
Exception in thread "main" java.lang.ClassCastException: class [B cannot be cast to class com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent ([B is in module java.base of loader 'bootstrap'; com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent is in unnamed module of loader 'app')
	at com.company.TestFunction.apply(TestFunction.java:9)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunctionAndEnrichResultIfNecessary(SimpleFunctionRegistry.java:928)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeFunction(SimpleFunctionRegistry.java:884)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:745)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:588)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.handleRequest(FunctionInvoker.java:85)
	at com.company.Runner.main(Runner.java:16)
```
_My understanding that this is a bug_, but please confirm what should be an expected result in functional bean definitions case.

**Some notes**
I've tried to find out exact issue for functional bean definitions case and found the following:
- When spring boot application is used ([this case](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/FunctionInvoker.java#L127)), `AWSTypesMessageConverter` MessageConverter from `AWSCompanionAutoConfiguration` is registered and picked up by `ContextFunctionCatalogAutoConfiguration` and its `FunctionRegistry` ([here](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/ContextFunctionCatalogAutoConfiguration.java#L105)). That's why everything works fine in that case.
- When functional bean definitions is used ([this case](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-adapters/spring-cloud-function-adapter-aws/src/main/java/org/springframework/cloud/function/adapter/aws/FunctionInvoker.java#L126)), `AWSCompanionAutoConfiguration` is used as "source", but not parsed since for functional case we [do not load sources](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/FunctionalSpringApplication.java#L169). Additionally, `ContextFunctionCatalogAutoConfiguration` is not used and `FunctionRegistry` is being registered by `ContextFunctionCatalogInitializer` ([here](https://github.com/spring-cloud/spring-cloud-function/blob/main/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/config/ContextFunctionCatalogInitializer.java#L171)), where `AWSTypesMessageConverter` is not used at all. As I understand, that's the reason why AWS event can't be converted.

Thank you in advance for taking a look at this.

**Comment by olegz** [comment]
What made you use FunctionInvoker as such:
```
 new FunctionInvoker().handleRequest(bais, baos, null);
```
You have missed the whole lifecycle and initialization part .

In any event, it was never meant to be used programmatically as some utility class. Was never designed for that.
It was meant to only execute inside of AWS container as an invocation adapter between java functions and AWS handlers as described here - https://docs.spring.io/spring-cloud-function/docs/current/reference/html/aws.html#_getting_started

**Comment by LutherWest** [comment]
Hi @olegz, thanks for your reply.

```
new FunctionInvoker().handleRequest(bais, baos, null);
```
It was just a fastest and easiest way to reproduce observed behavior, that's not how I write lambdas with Spring Cloud Function.

Let me then provide another example how to come across this issue:
`pom.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.4</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.company</groupId>
    <artifactId>test-lambda</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>test-lambda</name>
    <description>test-lambda</description>
    <properties>
        <java.version>11</java.version>
        <spring-boot.version>2.7.4</spring-boot.version>
        <spring-cloud-function.version>3.2.7</spring-cloud-function.version>
        <aws-lambda-java-core.version>1.2.1</aws-lambda-java-core.version>
        <aws-lambda-events.version>3.11.0</aws-lambda-events.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-function-adapter-aws</artifactId>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>${aws-lambda-java-core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>${aws-lambda-events.version}</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-function-dependencies</artifactId>
                <version>${spring-cloud-function.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>org.springframework.boot.experimental</groupId>
                        <artifactId>spring-boot-thin-layout</artifactId>
                        <version>1.0.28.RELEASE</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                    <shadedClassifierName>aws</shadedClassifierName>
                    <artifactSet>
                        <excludes>
                            <exclude>org.projectlombok:lombok:*</exclude>
                        </excludes>
                    </artifactSet>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

`TestFunction.java` and `FunctionalApplication.java` should be the same as in example above.

Now we should build project and run it with [docker-lambda](https://github.com/lambci/docker-lambda):
```
#Windows 10, git bash
./mvnw clean package

unzip -o -q -d ./target/docker ./target/test-lambda-0.0.1-SNAPSHOT-aws.jar

docker run --rm \
  -e MAIN_CLASS=com.company.FunctionalApplication \
  -v "/${PWD}/target/docker":/var/task \
  lambci/lambda:java11 \
  org.springframework.cloud.function.adapter.aws.FunctionInvoker \
  '{"resource":"/my/path","path":"/my/path","httpMethod":"GET","headers":{"header1":"value1","header2":"value2"},"multiValueHeaders":{"header1":["value1"],"header2":["value1","value2"]},"queryStringParameters":{"parameter1":"value1","parameter2":"value"},"multiValueQueryStringParameters":{"parameter1":["value1","value2"],"parameter2":["value"]},"requestContext":{"accountId":"123456789012","apiId":"id","authorizer":{"claims":null,"scopes":null},"domainName":"id.execute-api.us-east-1.amazonaws.com","domainPrefix":"id","extendedRequestId":"request-id","httpMethod":"GET","identity":{"accessKey":null,"accountId":null,"caller":null,"cognitoAuthenticationProvider":null,"cognitoAuthenticationType":null,"cognitoIdentityId":null,"cognitoIdentityPoolId":null,"principalOrgId":null,"sourceIp":"IP","user":null,"userAgent":"user-agent","userArn":null,"clientCert":{"clientCertPem":"CERT_CONTENT","subjectDN":"www.example.com","issuerDN":"Example issuer","serialNumber":"a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1:a1","validity":{"notBefore":"May 28 12:30:02 2019 GMT","notAfter":"Aug  5 09:36:04 2021 GMT"}}},"path":"/my/path","protocol":"HTTP/1.1","requestId":"id=","requestTime":"04/Mar/2020:19:15:17 +0000","requestTimeEpoch":1583349317135,"resourceId":null,"resourcePath":"/my/path","stage":"$default"},"pathParameters":null,"stageVariables":null,"body":"Hello from Lambda!","isBase64Encoded":false}'
```

Result is the same - `class [B cannot be cast to class com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent`

**Comment by olegz** [comment]
Can you please try with s-c-function 3.2.8. I can't seem to reproduce it.

**Comment by olegz** [comment]
Actually reproduced

**Comment by kriehzoo** [comment]
Hi @olegz 
First of all, thanks for your efforts and great work.
I am facing the same issue as described above and after trying around for some hours now I hoped that the fix here should solve it. However, I am using 4.0.5 and the changes are not visible there. So after looking at the git history I realised that some of the changes were undone i the scope of GH-966.
Could it be that GH-932 is now broken again?
Your help would be very much appreciated.

**Comment by kriehzoo** [comment]
To sum up what I am experiencing:
I implemented a functional bean and deployed it to AWS Lambda. It gets triggered by a putObject on an S3 bucket.
In CloudWatch I see that it detects the companion:
`SOURCE: class org.springframework.cloud.function.adapter.aws.AWSCompanionAutoConfiguration
` 
However, it seems that it never uses it and so AWSTypesMessageConverter is never called.
And that would mean, that LambdaEventSerializers.serializerFor is not called either.

IMHO this could be the reason for getting 

```
23:44:29.099 [main] DEBUG o.s.c.f.c.c.JsonMessageConverter - Failed to convert value: {
    "Records": [
        {
            "eventVersion": "2.1",
            "eventSource": "aws:s3",
            "awsRegion": "eu-central-1",
            "eventTime": "2023-11-04T23:44:23.905Z",
            "eventName": "ObjectCreated:Put",
            "userIdentity": {
                "principalId": "AWS:xxxxxxxxxxxxxxxxxxx"
            },
            "requestParameters": {
                "sourceIPAddress": "x.x.x.x"
            },
            "responseElements": {
                "x-amz-request-id": "xxxxxxxxxxxxxxxx",
                "x-amz-id-2": "xxxxxxxxxxxxxxxxxxxx"
            },
            "s3": {
                "s3SchemaVersion": "1.0",
                "configurationId": "xxxxxxxxxxxxxxxxxxxxxxxx",
                "bucket": {
                    "name": "xxxxxxxxxxxxxxx",
                    "ownerIdentity": {
                        "principalId": "xxxxxxxxxxxxxxxxxx"
                    },
                    "arn": "arn:aws:s3:::xxxxxxxxxxxxxxxxx"
                },
                "object": {
                    "key": "xxxxxxxxxxxxxxxx",
                    "size": 6064,
                    "eTag": "xxxxxxxxxxxxx",
                    "sequencer": "xxxxxxxxxxxxxx"
                }
            }
        }
    ]
} to: class com.amazonaws.services.lambda.runtime.events.S3Event

```

and next

`java.lang.IllegalStateException: Failed to convert. Possible bug as the conversion probably shouldn't have been attempted here`

and

`Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.amazonaws.services.lambda.runtime.events.models.s3.S3EventNotification$S3EventNotificationRecord` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)`

I also see

`Failed to convert input '[B@5adb0db3' to type class com.amazonaws.services.lambda.runtime.events.S3Event. Will use it as is.`
