### ISSUE TITLE
Crash with scan Supplier<>

### ISSUE THREAD

**Issue by x539** [spring-cloud/spring-cloud-function#959]
**Describe the bug**
When I have a Kotlin class implementing java.util.function.Supplier<>  I get this error: (eg. when calling /actuator/functions)

```
2022-11-17 21:07:56.795 ERROR 66602 --- [oundedElastic-1] a.w.r.e.AbstractErrorWebExceptionHandler : [2f12c31e-1]  500 Server Error for HTTP GET "/actuator/functions"

java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType (java.lang.Class and java.lang.reflect.ParameterizedType are in module java.base of loader 'bootstrap')
        at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.getFunctionRegistration(KotlinLambdaToFunctionAutoConfiguration.java:160) ~[spring-cloud-function-context-3.2.8.jar:3.2.8]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ Handler org.springframework.boot.actuate.endpoint.web.reactive.AbstractWebFluxEndpointHandlerMapping$ReadOperationHandler#handle(ServerWebExchange) [DispatcherHandler]
        *__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/actuator/functions" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at org.springframework.cloud.function.context.config.KotlinLambdaToFunctionAutoConfiguration$KotlinFunctionWrapper.getFunctionRegistration(KotlinLambdaToFunctionAutoConfiguration.java:160) ~[spring-cloud-function-context-3.2.8.jar:3.2.8]
                at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry.lookup(BeanFactoryAwareFunctionRegistry.java:170) ~[spring-cloud-function-context-3.2.8.jar:3.2.8]
                at org.springframework.cloud.function.context.FunctionCatalog.lookup(FunctionCatalog.java:42) ~[spring-cloud-function-context-3.2.8.jar:3.2.8]
                at org.springframework.cloud.function.actuator.FunctionsEndpoint.listAll(FunctionsEndpoint.java:51) ~[spring-cloud-function-context-3.2.8.jar:3.2.8]
```

**Sample**
src/main/kotlin/com/example/demo/DemoApplication.kts
```kotlin
package com.example.demo

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class DemoApplication

fun main(args: Array<String>) {
	runApplication<DemoApplication>(*args)
}
////////
```

src/main/kotlin/com/example/demo/funs/Test.kt
```kotlin
package com.example.demo.funs
import java.util.function.Supplier
open class Test : Supplier<String> {
	override fun get(): String = "Test"
}
```
src/main/resources/appliaction.yaml
```yaml
spring.cloud.function.scan.packages: com.example.demo.funs
management.endpoints.web.exposure.include: "*"
```

build.gradle.kts
```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "2.7.5"
	id("io.spring.dependency-management") version "1.0.15.RELEASE"
	kotlin("jvm") version "1.6.21"
	kotlin("plugin.spring") version "1.6.21"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

repositories {
	mavenCentral()
}

extra["springCloudVersion"] = "2021.0.5"

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-actuator")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("org.springframework.cloud:spring-cloud-starter-function-webflux")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
}

dependencyManagement {
	imports {
		mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
	}
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "17"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}
```

**Comment by x539** [comment]
Probably the same as/related to #956, #964
