### ISSUE TITLE
Error during the process-aot goal

### ISSUE THREAD

**Issue by oclay1st** [spring-cloud/spring-cloud-function#966]
This error is from the `process-aot` goal:
Environment:
```
OS: Linux
JDK: OpenJDK 17
Spring Boot: 3.0.0
Spring Cloud Function: 4.0.0-RC2
```
Step to reproduce:
- `mvn spring-boot:process-aot`

  ```
  Exception in thread "main" java.lang.IllegalStateException: No constructor or factory method candidate found for Root bean: class [org.springframework.cloud.function.adapter.aws.AWSTypesMessageConverter]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null and argument types []
        at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorOrFactoryMethod(ConstructorResolver.java:939)
        at org.springframework.beans.factory.support.RegisteredBean.resolveConstructorOrFactoryMethod(RegisteredBean.java:197)
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGenerator.<init>(BeanDefinitionMethodGenerator.java:79)
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:102)
        at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:118)
        at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:45)
        at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:35)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.getContributions(BeanFactoryInitializationAotContributions.java:67)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:49)
        at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:44)
        at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
        at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
        at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
        at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
        at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
        at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
        at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:76)

  ```

**Comment by andrew2184** [comment]
Got the same issue with version 4.0.0-RC3

**Comment by brettryan** [comment]
As `process-aot` is bound to the native build, at this time this version is not able to produce native build images.

**Comment by brettryan** [comment]
Actually, this isn't a fault of `spring-cloud-function`. This is a result of no `ObjectMapper` being auto-configured as per - [spring-boot-starter-json cannot be used standalone](https://github.com/spring-projects/spring-boot/issues/10031).

The reason we are seeing this is due to `AWSCompanionAutoConfiguration` naively falling back to `JsonMapper` implementation if no jackson `ObjectMapper` bean is present.

You can resolve this by ensuring you have either `ObjectMapper` or `JsonMapper` beans present.

**Comment by brettryan** [comment]
Crap, my bad, that didn't resolve it, sorry.

**Comment by brettryan** [comment]
Steps to reproduce:

1. Start with [this initializr project](https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.0.0&packaging=jar&jvmVersion=19&groupId=com.telstra.ctg.car&artifactId=car-lambda-demo&name=car-lambda-demo&description=CAR%20Lambda%20Demo&packageName=com.telstra.ctg.car.car-lambda-demo&dependencies=native,cloud-function)
2. Add dependency for `spring-cloud-function-adapter-aws`
```xml
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-function-adapter-aws</artifactId>
    </dependency>
```
3. Attempt to build and process AOT, or; build native:
```bash
mvn clean package spring-boot:process-aot
```

**Comment by brettryan** [comment]
Just for a test, I added a no-args constructor to `AWSTypesMessageConverter` and successfully got my app compiled and running as a native image.

```java
public AWSTypesMessageConverter() {
    this(new JacksonMapper(new ObjectMapper()), new MimeType("application", "json"), new MimeType(CloudEventMessageUtils.APPLICATION_CLOUDEVENTS.getType(),
            CloudEventMessageUtils.APPLICATION_CLOUDEVENTS.getSubtype() + "+json"));
}
```

Obviously this is not the correct fix. I have no idea how the AOT processor works and not sure where to start looking to solve this.

**Comment by olegz** [comment]
So the fix is in. Please give it a shot and let us know as the GA release is coming soon

**Comment by andrew2184** [comment]
Works now. Thanks!

**Comment by brettryan** [comment]
Confirmed fixed, thanks so much @olegz . I nearly did exactly what you did but thought I was going to be undoing original work. Thank you.

**Comment by LtTempletonPeck** [comment]
Working for me with Spring Boot 3 and native image AWS lambda.
